### ISSUE TITLE
f2b exception

### ISSUE THREAD

**Issue by lexa500** [fail2ban/fail2ban#1010]
Hello i have an issue on my gentoo system, with python3.4 (the same with puthon2.7 and 3.3)
F2b just crashes, but does not add iptables rules
here is the log2015-04-02 11:17:12,359 fail2ban.server         [5211]: INFO    Changed logging target to /var/log/fail2ban.log for Fail2ban v0.9.1
2015-04-02 11:17:12,360 fail2ban.database       [5211]: INFO    Connected to fail2ban persistent database '/var/lib/fail2ban/fail2ban.sqlite3'
2015-04-02 11:17:12,365 fail2ban.jail           [5211]: INFO    Creating new jail 'ssh-iptables'
2015-04-02 11:17:12,367 fail2ban.jail           [5211]: INFO    Jail 'ssh-iptables' uses poller
2015-04-02 11:17:12,378 fail2ban.filter         [5211]: INFO    Set jail log file encoding to UTF-8
2015-04-02 11:17:12,378 fail2ban.jail           [5211]: INFO    Initiated 'polling' backend
2015-04-02 11:17:12,381 fail2ban.filter         [5211]: INFO    Set findtime = 300
2015-04-02 11:17:12,382 fail2ban.filter         [5211]: INFO    Set jail log file encoding to UTF-8
2015-04-02 11:17:12,382 fail2ban.actions        [5211]: INFO    Set banTime = 600
2015-04-02 11:17:12,382 fail2ban.filter         [5211]: INFO    Set maxRetry = 3
2015-04-02 11:17:12,385 fail2ban.filter         [5211]: INFO    Added logfile = /var/log/messages
2015-04-02 11:17:12,385 fail2ban.filter         [5211]: INFO    Set maxlines = 10
2015-04-02 11:17:12,420 fail2ban.server         [5211]: INFO    Jail ssh-iptables is not a JournalFilter instance
2015-04-02 11:17:12,446 fail2ban.jail           [5211]: INFO    Jail 'ssh-iptables' started
2015-04-02 11:20:15,260 fail2ban                [5211]: CRITICAL Unhandled exception in Fail2Ban:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/fail2ban/server/jailthread.py", line 64, in run_with_except_hook
    run(*args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/fail2ban/server/filterpoll.py", line 95, in run
    self.getFailures(filename)
  File "/usr/lib64/python3.4/site-packages/fail2ban/server/filter.py", line 682, in getFailures
    self.processLineAndAdd(line)
  File "/usr/lib64/python3.4/site-packages/fail2ban/server/filter.py", line 421, in processLineAndAdd
    if self.inIgnoreIPList(ip):
  File "/usr/lib64/python3.4/site-packages/fail2ban/server/filter.py", line 364, in inIgnoreIPList
    s[1] = int(s[1])
ValueError: invalid literal for int() with base 10: '8,'

**Comment by sebres** [comment]
see https://github.com/fail2ban/fail2ban/issues/880#issuecomment-65794315 for the same problem...
short: use spaces instead of `,` in `ignoreip`

**Comment by lexa500** [comment]
thanx! it helped greatly!
