### ISSUE TITLE
Several issue tunning fail2ban test while packaging

### ISSUE THREAD

**Issue by weberhofer** [fail2ban/fail2ban#1046]
Packaging fail2ban 0.9.2 for openSUSE I have started to run the test-scripts, Unfortunately many of them fail, see the log below.

Some of the problems seem to be related to timezone-setting (as I'm in Europe/Vienna). Maybe you can help me to solve those and the other issues?

Johannes

```
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.5cT6uF
+ umask 022
+ cd /home/abuild/rpmbuild/BUILD
+ cd fail2ban-0.9.2
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ ./fail2ban-testcases-all --no-network
Testing using /usr/bin/python2.7
Fail2ban 0.9.2 test suite. Python 2.7.8 (default, Sep 30 2014, 15:34:38) [GCC]. Please wait...
........................s..........................................................................................................FEE...........F.F...F..............F................F.F....FF.......FF.....F.F...F.....FFFFFFFFFFFFFF...s..
======================================================================
ERROR: testNewChangeViaGetFailures_rewrite (fail2ban.tests.filtertestcase.LogFileMonitor)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/filtertestcase.py", line 438, in testNewChangeViaGetFailures_rewrite
_assert_correct_last_attempt(self, self.filter, GetFailures.FAILURES_01)
File "./fail2ban/tests/filtertestcase.py", line 119, in _assert_correct_last_attempt
found = _ticket_tuple(filter_.failManager.toBan())
File "./fail2ban/server/failmanager.py", line 153, in toBan
raise FailManagerEmpty
FailManagerEmpty

======================================================================
ERROR: testNewChangeViaGetFailures_simple (fail2ban.tests.filtertestcase.LogFileMonitor)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/filtertestcase.py", line 430, in testNewChangeViaGetFailures_simple
_assert_correct_last_attempt(self, self.filter, GetFailures.FAILURES_01)
File "./fail2ban/tests/filtertestcase.py", line 119, in _assert_correct_last_attempt
found = _ticket_tuple(filter_.failManager.toBan())
File "./fail2ban/server/failmanager.py", line 153, in toBan
raise FailManagerEmpty
FailManagerEmpty

======================================================================
FAIL: testNewChangeViaGetFailures_move (fail2ban.tests.filtertestcase.LogFileMonitor)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/filtertestcase.py", line 458, in testNewChangeViaGetFailures_move
self.assertEqual(self.filter.failManager.getFailTotal(), 2)
AssertionError: 0 != 2

======================================================================
FAIL: testGetTime (fail2ban.tests.datedetectortestcase.DateDetectorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/datedetectortestcase.py", line 64, in testGetTime
self.assertEqual(datelog, dateUnix)
AssertionError: 1106517599.0 != 1106513999.0

======================================================================
FAIL: testVariousTimes (fail2ban.tests.datedetectortestcase.DateDetectorTest)
Test detection of various common date/time formats f2b should understand
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/datedetectortestcase.py", line 111, in testVariousTimes
self.assertEqual(logUnix, dateUnix, "getTime comparison failure for %s: \"%s\" is not \"%s\"" % (sdate, logUnix, dateUnix))
AssertionError: getTime comparison failure for Jan 23 21:59:59: "1106517599.0" is not "1106513999.0"

======================================================================
FAIL: testSampleRegexsAPACHE-BADBOTS (fail2ban.tests.samplestestcase.FilterSamplesRegex)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/samplestestcase.py", line 132, in testFilter
fail2banTime - jsonTime, logFile.filename(), logFile.filelineno(), line ) )
AssertionError: UTC Time  mismatch fail2ban 1173101961 (2007-03-05T13:39:21) != failJson 1173105561.0 (2007-03-05T14:39:21)  (diff -3600.000 seconds) on: ./fail2ban/tests/files/logs/apache-badbots:2 '1.2.3.4 - - [05/Mar/2007:14:39:21 +0100] "POST /123.html/trackback/ HTTP/1.0" 301 459 "http://www.mydomain.tld/123.html/trackback" "TrackBack/1.02"\n':

======================================================================
FAIL: testSampleRegexsDOVECOT (fail2ban.tests.samplestestcase.FilterSamplesRegex)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/samplestestcase.py", line 132, in testFilter
fail2banTime - jsonTime, logFile.filename(), logFile.filelineno(), line ) )
AssertionError: UTC Time  mismatch fail2ban 1284616260 (2010-09-16T05:51:00) != failJson 1284623460.0 (2010-09-16T07:51:00)  (diff -7200.000 seconds) on: ./fail2ban/tests/files/logs/dovecot:2 '@400000004c91b044077a9e94 imap-login: Info: Aborted login (auth failed, 1 attempts): user=<martin@waschbuesch.de>, method=CRAM-MD5, rip=80.187.101.33, lip=80.254.129.240, TLS\n':

======================================================================
FAIL: testSampleRegexsNGINX-BOTSEARCH (fail2ban.tests.samplestestcase.FilterSamplesRegex)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/samplestestcase.py", line 132, in testFilter
fail2banTime - jsonTime, logFile.filename(), logFile.filelineno(), line ) )
AssertionError: UTC Time  mismatch fail2ban 1421780008 (2015-01-20T18:53:28) != failJson 1421783608.0 (2015-01-20T19:53:28)  (diff -3600.000 seconds) on: ./fail2ban/tests/files/logs/nginx-botsearch:2 '12.34.56.78 - - [20/Jan/2015:19:53:28 +0100] "GET //phpMyAdmin-2.8.2.3/scripts/setup.php HTTP/1.1" 404 47 "-" "-" "-"\n':

======================================================================
FAIL: testSampleRegexsNSD (fail2ban.tests.samplestestcase.FilterSamplesRegex)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/samplestestcase.py", line 132, in testFilter
fail2banTime - jsonTime, logFile.filename(), logFile.filelineno(), line ) )
AssertionError: UTC Time  mismatch fail2ban 1387288694.0 (2013-12-17T13:58:14) != failJson 1387292294.0 (2013-12-17T14:58:14)  (diff -3600.000 seconds) on: ./fail2ban/tests/files/logs/nsd:2 '[1387288694] nsd[7745]: info: ratelimit block example.com. type any target 192.0.2.0/24 query 192.0.2.105 TYPE255\n':

======================================================================
FAIL: testSampleRegexsPHP-URL-FOPEN (fail2ban.tests.samplestestcase.FilterSamplesRegex)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/samplestestcase.py", line 132, in testFilter
fail2banTime - jsonTime, logFile.filename(), logFile.filelineno(), line ) )
AssertionError: UTC Time  mismatch fail2ban 1238075060 (2009-03-26T13:44:20) != failJson 1238078660.0 (2009-03-26T14:44:20)  (diff -3600.000 seconds) on: ./fail2ban/tests/files/logs/php-url-fopen:2 '66.185.212.172 - - [26/Mar/2009:08:44:20 -0500] "GET /index.php?n=http://eatmyfood.hostinginfive.com/pizza.htm? HTTP/1.1" 200 114 "-" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)"\n':

======================================================================
FAIL: testSampleRegexsPORTSENTRY (fail2ban.tests.samplestestcase.FilterSamplesRegex)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/samplestestcase.py", line 132, in testFilter
fail2banTime - jsonTime, logFile.filename(), logFile.filelineno(), line ) )
AssertionError: UTC Time  mismatch fail2ban 1403884279.0 (2014-06-27T15:51:19) != failJson 1403891479.0 (2014-06-27T17:51:19)  (diff -7200.000 seconds) on: ./fail2ban/tests/files/logs/portsentry:2 '1403884279 - 06/27/2014 17:51:19 Host: 192.168.56.1/192.168.56.1 Port: 1 TCP Blocked\n':

======================================================================
FAIL: testSampleRegexsROUNDCUBE-AUTH (fail2ban.tests.samplestestcase.FilterSamplesRegex)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/samplestestcase.py", line 132, in testFilter
fail2banTime - jsonTime, logFile.filename(), logFile.filelineno(), line ) )
AssertionError: UTC Time  mismatch fail2ban 1358886501 (2013-01-22T20:28:21) != failJson 1358890101.0 (2013-01-22T21:28:21)  (diff -3600.000 seconds) on: ./fail2ban/tests/files/logs/roundcube-auth:2 '[22-Jan-2013 22:28:21 +0200]: FAILED login for user1 from 192.0.43.10\n':

======================================================================
FAIL: testSampleRegexsSELINUX-SSH (fail2ban.tests.samplestestcase.FilterSamplesRegex)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/samplestestcase.py", line 132, in testFilter
fail2banTime - jsonTime, logFile.filename(), logFile.filelineno(), line ) )
AssertionError: UTC Time  mismatch fail2ban 1373330717.0 (2013-07-09T00:45:17) != failJson 1373337917.0 (2013-07-09T02:45:17)  (diff -7200.000 seconds) on: ./fail2ban/tests/files/logs/selinux-ssh:8 'type=USER_ERR msg=audit(1373330717.000:4070): user pid=12000 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg=\'op=PAM:bad_ident acct="?" exe="/usr/sbin/sshd" hostname=173.242.116.187 addr=173.242.116.187 terminal=ssh res=failed\'\n':

======================================================================
FAIL: testSampleRegexsSQUID (fail2ban.tests.samplestestcase.FilterSamplesRegex)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/samplestestcase.py", line 132, in testFilter
fail2banTime - jsonTime, logFile.filename(), logFile.filelineno(), line ) )
AssertionError: UTC Time  mismatch fail2ban 1386543323.0 (2013-12-08T22:55:23) != failJson 1386546923.0 (2013-12-08T23:55:23)  (diff -3600.000 seconds) on: ./fail2ban/tests/files/logs/squid:4 '1386543323.000      4 91.188.124.227 TCP_DENIED/403 4099 GET http://www.proxy-listen.de/azenv.php - HIER_NONE/- text/html\n':

======================================================================
FAIL: testSampleRegexsSSHD (fail2ban.tests.samplestestcase.FilterSamplesRegex)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/samplestestcase.py", line 132, in testFilter
fail2banTime - jsonTime, logFile.filename(), logFile.filelineno(), line ) )
AssertionError: UTC Time  mismatch fail2ban 1429207370 (2015-04-16T18:02:50) != failJson 1429214570.0 (2015-04-16T20:02:50)  (diff -7200.000 seconds) on: ./fail2ban/tests/files/logs/sshd:154 '2015-04-16T18:02:50.321974+00:00 host sshd[2716]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=222.186.21.217  user=root\n':

======================================================================
FAIL: testSampleRegexsTINE20 (fail2ban.tests.samplestestcase.FilterSamplesRegex)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/samplestestcase.py", line 132, in testFilter
fail2banTime - jsonTime, logFile.filename(), logFile.filelineno(), line ) )
AssertionError: UTC Time  mismatch fail2ban 1389589342 (2014-01-13T05:02:22) != failJson 1389592942.0 (2014-01-13T06:02:22)  (diff -3600.000 seconds) on: ./fail2ban/tests/files/logs/tine20:3 '78017 00cff -- none -- - 2014-01-13T05:02:22+00:00 WARN (4): Tinebase_Controller::login::106 Login with username sdfsadf from 127.0.0.1 failed (-1)!\n':

======================================================================
FAIL: test_delLogPath (fail2ban.tests.filtertestcase.MonitorFailures<FilterPoll>(/tmp/monitorfailures_FilterPolldhwieRfail2ban))
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/filtertestcase.py", line 658, in test_delLogPath
self.assert_correct_last_attempt(GetFailures.FAILURES_01)
File "./fail2ban/tests/filtertestcase.py", line 532, in assert_correct_last_attempt
self.assertTrue(self.isFilled(20)) # give Filter a chance to react
AssertionError: False is not true

======================================================================
FAIL: test_grow_file (fail2ban.tests.filtertestcase.MonitorFailures<FilterPoll>(/tmp/monitorfailures_FilterPolldhwieRfail2ban))
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/filtertestcase.py", line 548, in test_grow_file
self.assertTrue(self.isFilled(6))
AssertionError: False is not true

======================================================================
FAIL: test_move_file (fail2ban.tests.filtertestcase.MonitorFailures<FilterPoll>(/tmp/monitorfailures_FilterPolldhwieRfail2ban))
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/filtertestcase.py", line 590, in test_move_file
self.assertEqual(self.filter.failManager.getFailTotal(), 2)
AssertionError: 0 != 2

======================================================================
FAIL: test_move_into_file (fail2ban.tests.filtertestcase.MonitorFailures<FilterPoll>(/tmp/monitorfailures_FilterPolldhwieRfail2ban))
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/filtertestcase.py", line 632, in test_move_into_file
self._test_move_into_file(interim_kill=False)
File "./fail2ban/tests/filtertestcase.py", line 610, in _test_move_into_file
self.assert_correct_last_attempt(GetFailures.FAILURES_01)
File "./fail2ban/tests/filtertestcase.py", line 532, in assert_correct_last_attempt
self.assertTrue(self.isFilled(20)) # give Filter a chance to react
AssertionError: False is not true

======================================================================
FAIL: test_move_into_file_after_removed (fail2ban.tests.filtertestcase.MonitorFailures<FilterPoll>(/tmp/monitorfailures_FilterPolldhwieRfail2ban))
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/filtertestcase.py", line 637, in test_move_into_file_after_removed
self._test_move_into_file(interim_kill=True)
File "./fail2ban/tests/filtertestcase.py", line 610, in _test_move_into_file
self.assert_correct_last_attempt(GetFailures.FAILURES_01)
File "./fail2ban/tests/filtertestcase.py", line 532, in assert_correct_last_attempt
self.assertTrue(self.isFilled(20)) # give Filter a chance to react
AssertionError: False is not true

======================================================================
FAIL: test_new_bogus_file (fail2ban.tests.filtertestcase.MonitorFailures<FilterPoll>(/tmp/monitorfailures_FilterPolldhwieRfail2ban))
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/filtertestcase.py", line 643, in test_new_bogus_file
self.assert_correct_last_attempt(GetFailures.FAILURES_01)
File "./fail2ban/tests/filtertestcase.py", line 532, in assert_correct_last_attempt
self.assertTrue(self.isFilled(20)) # give Filter a chance to react
AssertionError: False is not true

======================================================================
FAIL: test_rewrite_file (fail2ban.tests.filtertestcase.MonitorFailures<FilterPoll>(/tmp/monitorfailures_FilterPolldhwieRfail2ban))
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/filtertestcase.py", line 569, in test_rewrite_file
self.assert_correct_last_attempt(GetFailures.FAILURES_01)
File "./fail2ban/tests/filtertestcase.py", line 532, in assert_correct_last_attempt
self.assertTrue(self.isFilled(20)) # give Filter a chance to react
AssertionError: False is not true

======================================================================
FAIL: test_delLogPath (fail2ban.tests.filtertestcase.MonitorFailures<FilterPyinotify>(/tmp/monitorfailures_FilterPyinotifyLrlRttfail2ban))
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/filtertestcase.py", line 658, in test_delLogPath
self.assert_correct_last_attempt(GetFailures.FAILURES_01)
File "./fail2ban/tests/filtertestcase.py", line 532, in assert_correct_last_attempt
self.assertTrue(self.isFilled(20)) # give Filter a chance to react
AssertionError: False is not true

======================================================================
FAIL: test_grow_file (fail2ban.tests.filtertestcase.MonitorFailures<FilterPyinotify>(/tmp/monitorfailures_FilterPyinotifyLrlRttfail2ban))
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/filtertestcase.py", line 548, in test_grow_file
self.assertTrue(self.isFilled(6))
AssertionError: False is not true

======================================================================
FAIL: test_move_file (fail2ban.tests.filtertestcase.MonitorFailures<FilterPyinotify>(/tmp/monitorfailures_FilterPyinotifyLrlRttfail2ban))
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/filtertestcase.py", line 590, in test_move_file
self.assertEqual(self.filter.failManager.getFailTotal(), 2)
AssertionError: 0 != 2

======================================================================
FAIL: test_move_into_file (fail2ban.tests.filtertestcase.MonitorFailures<FilterPyinotify>(/tmp/monitorfailures_FilterPyinotifyLrlRttfail2ban))
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/filtertestcase.py", line 632, in test_move_into_file
self._test_move_into_file(interim_kill=False)
File "./fail2ban/tests/filtertestcase.py", line 610, in _test_move_into_file
self.assert_correct_last_attempt(GetFailures.FAILURES_01)
File "./fail2ban/tests/filtertestcase.py", line 532, in assert_correct_last_attempt
self.assertTrue(self.isFilled(20)) # give Filter a chance to react
AssertionError: False is not true

======================================================================
FAIL: test_move_into_file_after_removed (fail2ban.tests.filtertestcase.MonitorFailures<FilterPyinotify>(/tmp/monitorfailures_FilterPyinotifyLrlRttfail2ban))
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/filtertestcase.py", line 637, in test_move_into_file_after_removed
self._test_move_into_file(interim_kill=True)
File "./fail2ban/tests/filtertestcase.py", line 610, in _test_move_into_file
self.assert_correct_last_attempt(GetFailures.FAILURES_01)
File "./fail2ban/tests/filtertestcase.py", line 532, in assert_correct_last_attempt
self.assertTrue(self.isFilled(20)) # give Filter a chance to react
AssertionError: False is not true

======================================================================
FAIL: test_new_bogus_file (fail2ban.tests.filtertestcase.MonitorFailures<FilterPyinotify>(/tmp/monitorfailures_FilterPyinotifyLrlRttfail2ban))
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/filtertestcase.py", line 643, in test_new_bogus_file
self.assert_correct_last_attempt(GetFailures.FAILURES_01)
File "./fail2ban/tests/filtertestcase.py", line 532, in assert_correct_last_attempt
self.assertTrue(self.isFilled(20)) # give Filter a chance to react
AssertionError: False is not true

======================================================================
FAIL: test_rewrite_file (fail2ban.tests.filtertestcase.MonitorFailures<FilterPyinotify>(/tmp/monitorfailures_FilterPyinotifyLrlRttfail2ban))
----------------------------------------------------------------------
Traceback (most recent call last):
File "./fail2ban/tests/filtertestcase.py", line 569, in test_rewrite_file
self.assert_correct_last_attempt(GetFailures.FAILURES_01)
File "./fail2ban/tests/filtertestcase.py", line 532, in assert_correct_last_attempt
self.assertTrue(self.isFilled(20)) # give Filter a chance to react
AssertionError: False is not true

----------------------------------------------------------------------
Ran 238 tests in 268.471s

FAILED (failures=28, errors=2, skipped=2)
E: Failed with  /usr/bin/python2.7
```

**Comment by sebres** [comment]
Hmm... very strange. I see many fails, that theoretically indicate a time offset (may be). 
But I have executed without any problem in time zone Europe/Berlin (CET), would be equal with Europe/Vienna also. But on debian's distro.
Seconds I believe fail2ban works in many test cases with unixtime (UTC or GMT).

I think if you will try out to change anything (system / env etc), you should first begin with DateDetectorTest. Because both unixtime are:
1106517599 = 23.01.2005 21:59:59
1106513999 = 23.01.2005 20:59:59

Without this test is successful, you will not have prospect of success.

So next time can just try:
```
cd /path/to/fail2ban
PYTHONPATH=. bin/fail2ban-testcase DateDetectorTest
```

**Comment by yarikoptic** [comment]
yeah -- too many failures ;)

here is the way I run "as built" while building debian package (makefile syntax)

    cd build && LC_ALL=C.UTF-8 FAIL2BAN_CONFIG_DIR="$(CURDIR)/config" PYTHONPATH="$(CURDIR)/.pybuild/pythonX.Y_$(PYVERSION)/build/" scripts-*/fail2ban-testcases --no-network

hope this helps
-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by weberhofer** [comment]
@sebres that's what I get:
fail2ban-0.9.2> bin/fail2ban-testcases DateDetectorTest
Fail2ban 0.9.2 test suite. Python 2.7.8 (default, Sep 30 2014, 15:34:38) [GCC]. Please wait...
....F.F
======================================================================
FAIL: testGetTime (fail2ban.tests.datedetectortestcase.DateDetectorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/datedetectortestcase.py", line 64, in testGetTime
    self.assertEqual(datelog, dateUnix)
AssertionError: 1106517599.0 != 1106513999.0

======================================================================
FAIL: testVariousTimes (fail2ban.tests.datedetectortestcase.DateDetectorTest)
Test detection of various common date/time formats f2b should understand
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/datedetectortestcase.py", line 111, in testVariousTimes
    self.assertEqual(logUnix, dateUnix, "getTime comparison failure for %s: \"%s\" is not \"%s\"" % (sdate, logUnix, dateUnix))
AssertionError: getTime comparison failure for Jan 23 21:59:59: "1106517599.0" is not "1106513999.0"

----------------------------------------------------------------------
Ran 7 tests in 0.021s

FAILED (failures=2)


I have tried to run prior to execute the test, but that does not make any difference: "export set TZ=Etc/GMT"

**Comment by yarikoptic** [comment]
On Thu, 07 May 2015, Johannes Weberhofer wrote:

>    @sebres that's what I get:
>    fail2ban-0.9.2> bin/fail2ban-testcases DateDetectorTest
>    Fail2ban 0.9.2 test suite. Python 2.7.8 (default, Sep 30 2014, 15:34:38)
>    [GCC]. Please wait...

>                                     ....F.F

> FAIL: testGetTime (fail2ban.tests.datedetectortestcase.DateDetectorTest)

>    Traceback (most recent call last):
>    File "./fail2ban/tests/datedetectortestcase.py", line 64, in testGetTime
>    self.assertEqual(datelog, dateUnix)
>    AssertionError: 1106517599.0 != 1106513999.0

FWIW
which is difference of 3600 i.e. one hour -- clearly a time zone/day
light savings madness somehow :-(

>    AssertionError: getTime comparison failure for Jan 23 21:59:59:
>    "1106517599.0" is not "1106513999.0"

>      ----------------------------------------------------------------------

>    Ran 7 tests in 0.021s

>    FAILED (failures=2)

>    I have tried to run prior to execute the test, but that does not make any
>    difference: "export set TZ=Etc/GMT"

not sure if matters but should be just 
"export " not "export set"

but what is your current timezone?

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by weberhofer** [comment]
@yarikoptic it does not make any difference what I set in the TZ variable (my timezone is Europe/Vienna, I have tried Etc/UTC, too), and yes you are right the syntax was incorrect.
LC_ALL=C.UTF-8 cant be correctly set, it causes some errors:
```
fail2ban-0.9.2> locale 
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=POSIX
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=C.UTF-8
```

**Comment by sebres** [comment]
What I mean was not a `export TZ=Etc/GMT`, I just wanted to help you *faster* find a solution, because if DateDetectorTest does not work, another test cases using times will fail.
I believe, directly It has nothing to do with GMT system zone in itself.
What this test case will do, is to read Date "Jan 23 21:59:59" and it should be definitive 1106513999 as unixtime (that is in GMT) and you have in GMT exact one hour more (what is definitive wrong for GMT in you current TZ is CET resp. CEST).

Also, try to call following and compare with my results:
```bash
$ python -c "import datetime; d = datetime.datetime; print(d.fromtimestamp(1106513999)); print(d.utcfromtimestamp(1106513999));"
```
```
2005-01-23 21:59:59
2005-01-23 20:59:59
```

```bash
$ python -c "import time; print(time.tzname); print('daylight: %d' % time.daylight);"
```
```
('CET', 'CEST')
daylight: 1
```

**Comment by sebres** [comment]
It should be something else, just checked:
```
$ TZ=America/New_York python -c "import time; print(time.tzname); print('daylight: %d' % time.daylight);"
```
returns
```
('EST', 'EDT')
daylight: 1
```
But both tests bellow returns ```OK```:
```
TZ=America/New_York bin/fail2ban-testcases testGetTime
# or
export TZ=America/New_York
bin/fail2ban-testcases testGetTime
```

So, the test cases seem to be environment (TZ) independent.

I'm with my Latin on the ropes...

**Comment by sebres** [comment]
@weberhofer Wiesen Sie denn, evtl. ob irgendwelche System-Einstellungen was das Datum/Zeitzonen angeht, auf Ihrem Server zusätzlich gemacht worden? Ist es standart python von openSuse, was Sie da verwenden (oder irgendeine custom build)? Weil ich inzwischen wirklich am Ende mit meinem Latein bin, vor allem ich es (das Testen) bereits zig-mal auf allerlei Plattformen gemacht habe... :(

**Comment by leeclemens** [comment]
I noticed the other day that most sample logs are UTC +1 and some are UTC +2 - apparently based upon the month to offset daylight savings.

**Comment by weberhofer** [comment]
@sebres I have executed the code in my local build-environment. This environment contains a plain opensuse system without any modifications. You may have a look on the current build results in https://build.opensuse.org/package/show/home:weberho:branches:security/fail2ban ; you can click on each distribution to see a build-log showing the problem. Also the spec file and some patches are located in this repository.

These are the results to your command requested
```bash
$ python -c "import datetime; d = datetime.datetime; print(d.fromtimestamp(1106513999)); print(d.utcfromtimestamp(1106513999));"
2005-01-23 20:59:59
2005-01-23 20:59:59
```
```bash
$ python -c "import time; print(time.tzname); print('daylight: %d' % time.daylight);"
('UTC', 'UTC')
daylight: 0
```

**Comment by weberhofer** [comment]
I have found a solution for the problem: I have to explicitly install the "timezone" package to make the tests run correctly! Many thanks to everybody who helped me and directed me in the right direction. Btw. I'll soon update the staging repository mentioned above.

**Comment by sebres** [comment]
timezone package is not automatically on board in suse? strange...

**Comment by weberhofer** [comment]
Obviously not in the OBS build-environment.
