### ISSUE TITLE
Tests fail in build-environment

### ISSUE THREAD

**Issue by weberhofer** [fail2ban/fail2ban#1047]
Does those tests require a syslogd running? Or a network-interface? On the virtualized build environment on openSUSE I have non of them. Maybe the tests should be excluded when running with --no-network.

```
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ ./fail2ban-testcases-all --no-network
Testing using /usr/bin/python2.7
Fail2ban 0.9.2 test suite. Python 2.7.8 (default, Sep 30 2014, 15:34:38) [GCC]. Please wait...
........................s..................................................................................................................................................................................................................F.F
======================================================================
FAIL: testLogTargetSYSLOG (fail2ban.tests.servertestcase.TransmitterLogging)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/servertestcase.py", line 787, in testLogTargetSYSLOG
    self.setGetTest("logtarget", "SYSLOG")
  File "./fail2ban/tests/servertestcase.py", line 88, in setGetTest
    self.assertEqual(v(self.transm.proceed(setCmd)), v((outCode, outValue)))
AssertionError: Tuples differ: (1, error(111, 'Connection ref... != (0, 'SYSLOG')

First differing element 0:
1
0

- (1, error(111, 'Connection refused'))
+ (0, 'SYSLOG')

======================================================================
FAIL: testSyslogSocketNOK (fail2ban.tests.servertestcase.TransmitterLogging)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/servertestcase.py", line 805, in testSyslogSocketNOK
    }[platform.system() in ('Linux',) and os.path.exists('/dev/log')]
  File "./fail2ban/tests/servertestcase.py", line 88, in setGetTest
    self.assertEqual(v(self.transm.proceed(setCmd)), v((outCode, outValue)))
AssertionError: Tuples differ: (1, error(111, 'Connection ref... != (0, 'SYSLOG')

First differing element 0:
1
0

- (1, error(111, 'Connection refused'))
+ (0, 'SYSLOG')

----------------------------------------------------------------------
Ran 238 tests in 79.446s

FAILED (failures=2, skipped=1)
E: Failed with  /usr/bin/python2.7

**Comment by weberhofer** [comment]
After checking the sources, I don't think the issue is related to a network problem but the two tests check for existence of /dev/log ...

**Comment by weberhofer** [comment]
After comparing the different VMs in the build environment I see that on the failing machines /dev/log is present but no daemon in working. On the other machines /dev/log is not present and no tests fail.

**Comment by leeclemens** [comment]
what is `/dev/log` with no daemon running, an orphaned socket?

**Comment by weberhofer** [comment]
It seems to be automatically created from systemd-journald; in newer versions of opensuse it's no longer present - so I keep the related two tests possibly patched out;

**Comment by leeclemens** [comment]
so `/dev/log` exists, what is it (`stat /dev/log`)?

Otherwise the errors you provided would not have occurred during those two tests:

		if not os.path.exists("/dev/log") and sys.version_info >= (2, 7):
			raise unittest.SkipTest("'/dev/log' not present")
		elif not os.path.exists("/dev/log"):
			====> return

Can you also provide the output from `python -c "import platform; print(platform.system())"`

**Comment by weberhofer** [comment]
@leeclemens here are the requested infos from the build-environments:
```
stat /dev/log
File: '/dev/log'
Size: 0         	Blocks: 0          IO Block: 4096   socket
Device: 5h/5d	Inode: 121         Links: 1
Access: (0666/srw-rw-rw-)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-06-08 13:05:27.564000000 +0000
Modify: 2015-06-08 13:05:27.564000000 +0000
Change: 2015-06-08 13:05:27.564000000 +0000
Birth: -
python -c 'import platform; print(platform.system())'
Linux

**Comment by leeclemens** [comment]
It seems like your system is in a bad state, where the socket exists but is not accessible (orphaned?).

**Comment by weberhofer** [comment]
Thanks for looking at it. I'll report upstream to the opensuse-build-server devels.
