### ISSUE TITLE
Socket error

### ISSUE THREAD

**Issue by leeclemens** [fail2ban/fail2ban#1103]
I'm just putting this here for now:

> testSocket (fail2ban.tests.sockettestcase.Socket) ... 2015-07-07 08:33:57,152 Unexpected communication error: invalid load key, '<'.
2015-07-07 08:33:57,154 ['Traceback (most recent call last):', '  File "/pythonenv/3.4.3/lib/python3.4/asyncore.py", line 108, in readwrite', 'obj.handle_read_event()', '  File > "/pythonenv/3.4.3/lib/python3.4/asyncore.py", line 442, in handle_read_event', ' self.handle_read()', '  File "/pythonenv/3.4.3/lib/python3.4/asynchat.py", line 171, in handle_read', '    self.found_terminator()', 'File "/devpath/fail2ban/build/lib/fail2ban/server/asyncserver.py", line 71, in found_terminator', '
    message = loads(CSPROTO.EMPTY.join(buf))', "_pickle.UnpicklingError: invalid load key, '<'."]

Maybe related to https://github.com/fail2ban/fail2ban/pull/1099 ? Or has been occurring, and silently erroring for some time?

**Comment by sebres** [comment]
Yep, close message fails by deserialization (should not). Fix it now.

**Comment by sebres** [comment]
ready https://travis-ci.org/fail2ban/fail2ban/builds/70030899, merge now.
