### ISSUE TITLE
fail2ban-regex raises UnicodeDecodeError

### ISSUE THREAD

**Issue by CarstenGrohmann** [fail2ban/fail2ban#1200]
Hi,

today I've installed and tested fail2ban on RHEL7.  

A short test with `fail2ban-regex` failed with an UnicodeDecodeError, because the file `/var/log/messages`is an UTF-8 encoded file:
```python
# fail2ban-regex /var/log/messages /etc/fail2ban/filter.d/sshd.conf

Running tests
=============

Use   failregex filter file : sshd, basedir: /etc/fail2ban
Use         maxlines : 10
Use         log file : /var/log/messages
Use         encoding : UTF-8

Traceback (most recent call last):
  File "/bin/fail2ban-regex", line 581, in <module>
    fail2banRegex.process(test_lines)
  File "/bin/fail2ban-regex", line 373, in process
    line_datetimestripped, ret = fail2banRegex.testRegex(line)
  File "/bin/fail2ban-regex", line 332, in testRegex
    line, ret = self._filter.processLine(line, date, checkAllRegex=True)
  File "/usr/lib/python2.7/site-packages/fail2ban/server/filter.py", line 414, in processLine
    tupleLine, date, returnRawHost, checkAllRegex)
  File "/usr/lib/python2.7/site-packages/fail2ban/server/filter.py", line 494, in findFailure
    failRegex.search(self.__lineBuffer)
  File "/usr/lib/python2.7/site-packages/fail2ban/server/failregex.py", line 79, in search
    "\n".join("".join(value[::2]) for value in tupleLines) + "\n")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd2 in position 84: ordinal not in range(128)
```

I've hacked `/usr/lib/python2.7/site-packages/fail2ban/server/failregex.py` to get more information. 

My changes are:
```python
        def search(self, tupleLines):
                try:
                        self._matchCache = self._regexObj.search(
                                "\n".join("".join(value[::2]) for value in tupleLines) + "\n")
                except UnicodeDecodeError, e:
                        import pdb
                        pdb.set_trace()
                if self.hasMatched():
                        # Find start of the first line where the match was found
                        try:
                                self._matchLineStart = self._matchCache.string.rindex(
                                        "\n", 0, self._matchCache.start() +1 ) + 1
                        except ValueError:
                                self._matchLineStart = 0
```

New run with debugger:
```python
# fail2ban-regex /var/log/messages /etc/fail2ban/filter.d/sshd.conf

Running tests
=============

Use   failregex filter file : sshd, basedir: /etc/fail2ban
Use         maxlines : 10
Use         log file : /var/log/messages
Use         encoding : UTF-8

> /usr/lib/python2.7/site-packages/fail2ban/server/failregex.py(84)search()
-> if self.hasMatched():
(Pdb) list
 79                             self._matchCache = self._regexObj.search(
 80                                     "\n".join("".join(value[::2]) for value in tupleLines) + "\n")
 81                     except UnicodeDecodeError, e:
 82                             import pdb
 83                             pdb.set_trace()
 84  ->                 if self.hasMatched():
 85                             # Find start of the first line where the match was found
 86                             try:
 87                                     self._matchLineStart = self._matchCache.string.rindex(
 88                                             "\n", 0, self._matchCache.start() +1 ) + 1
 89                             except ValueError:
(Pdb) e
UnicodeDecodeError('ascii', ' mysrv1 kernel: ACPI: XSDT 00000000bdde1880 000BC (v01 HP     ProLiant 00000002   \xd2? 0000162E)', 84, 85, 'ordinal not in range(128)')
(Pdb) tupleLines
[(u'', u'Sep 23 10:38:43', u' mysrv1 kernel: init_memory_mapping: [mem 0x00000000-0x000fffff]'), (u'', u'Sep 23 10:38:43', u' mysrv1 kernel: init_memory_mapping: [mem 0x83fc00000-0x83fdfffff]'), (u'', u'Sep 23 10:38:43', u' mysrv1 kernel: init_memory_mapping: [mem 0x83c000000-0x83fbfffff]'), (u'', u'Sep 23 10:38:43', u' mysrv1 kernel: init_memory_mapping: [mem 0x800000000-0x83bffffff]'), (u'', u'Sep 23 10:38:43', u' mysrv1 kernel: init_memory_mapping: [mem 0x00100000-0xbddddfff]'), (u'', u'Sep 23 10:38:43', u' mysrv1 kernel: init_memory_mapping: [mem 0x100000000-0x7ffffffff]'), (u'', u'Sep 23 10:38:43', u' mysrv1 kernel: init_memory_mapping: [mem 0x83fe00000-0x83fffefff]'), (u'', u'Sep 23 10:38:43', u' mysrv1 kernel: RAMDISK: [mem 0x360d6000-0x37062fff]'), (u'', u'Sep 23 10:38:43', u' mysrv1 kernel: ACPI: RSDP 00000000000f4ee0 00024 (v02 HP    )'), ('', 'Sep 23 10:38:43', ' mysrv1 kernel: ACPI: XSDT 00000000bdde1880 000BC (v01 HP     ProLiant 00000002   \xd2? 0000162E)')]
(Pdb)
```
It looks like the the file encoding of `/var/log/messages`is detected well, but the code doesn't handle the encoding infomation.

Installed version:
```
# fail2ban-client -V
Fail2Ban v0.9.2

Copyright (c) 2004-2008 Cyril Jaquier, 2008- Fail2Ban Contributors
Copyright of modifications held by their respective authors.
Licensed under the GNU General Public License v2 (GPL).

Written by Cyril Jaquier <cyril.jaquier@fail2ban.org>.
Many contributions by Yaroslav O. Halchenko <debian@onerussian.com>.
```

Operating System:
```
# uname -a
Linux mysrv1 3.10.0-229.4.2.el7.x86_64 #1 SMP Fri Apr 24 15:26:38 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.1 (Maipo)
```

Regards,
Carsten

**Comment by sebres** [comment]
Use an option `-e` or  `--encoding` to specify the encoding of your log file, to test it with `fail2ban-regex`. Default it should be a system locale.
```bash
# usage:
fail2ban-regex --help
```
