### ISSUE TITLE
Fail2ban v0.9.3  not updating tables

### ISSUE THREAD

**Issue by gurvinderdadyala** [fail2ban/fail2ban#1228]
I have CentOS release 6.7 (Final) and have installed Fail2ban version 0.9.3 from EPEL report. When i am starting fail2ban, it is not updating fail2ban chain for ssh in IPTABLES.

Following is what i am getting in fail2ban log

2015-10-21 17:16:39,759 fail2ban.action         [29349]: DEBUG   iptables -w -N f2b-sshd
iptables -w -A f2b-sshd -j RETURN
iptables -w -I INPUT -p tcp -m multiport --dports ssh -j f2b-sshd
2015-10-21 17:16:39,759 fail2ban.filterpyinotify[29349]: DEBUG   pyinotifier started for sshd.
2015-10-21 17:16:39,771 fail2ban.jail           [29349]: INFO    Jail 'sshd' started
2015-10-21 17:16:39,862 fail2ban.action         [29349]: ERROR   iptables -w -N f2b-sshd
iptables -w -A f2b-sshd -j RETURN
iptables -w -I INPUT -p tcp -m multiport --dports ssh -j f2b-sshd -- stdout: ''
2015-10-21 17:16:39,862 fail2ban.action         [29349]: ERROR   iptables -w -N f2b-sshd
iptables -w -A f2b-sshd -j RETURN
iptables -w -I INPUT -p tcp -m multiport --dports ssh -j f2b-sshd -- stderr: "iptables v1.4.7: option `-w' requires an argument\nTry `iptables -h' or 'iptables --help' for more information.\niptables v1.4.7: option `-w' requires an argument\nTry `iptables -h' or 'iptables --help' for more information.\niptables v1.4.7: option `-w' requires an argument\nTry `iptables -h' or 'iptables --help' for more information.\n"
2015-10-21 17:16:39,862 fail2ban.action         [29349]: ERROR   iptables -w -N f2b-sshd
iptables -w -A f2b-sshd -j RETURN
iptables -w -I INPUT -p tcp -m multiport --dports ssh -j f2b-sshd -- returned 2
2015-10-21 17:16:39,862 fail2ban.actions        [29349]: ERROR   Failed to start jail 'sshd' action 'iptables-multiport': Error starting action
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/fail2ban/server/actions.py", line 221, in run
    action.start()
  File "/usr/lib/python2.6/site-packages/fail2ban/server/action.py", line 281, in start
    raise RuntimeError("Error starting action")
RuntimeError: Error starting action

**Comment by opoplawski** [comment]
Please see https://bugzilla.redhat.com/show_bug.cgi?id=1272681

**Comment by gurvinderdadyala** [comment]
@opoplawski Updating to Fail2ban version 0.9.3-1.el6.1 from EPEL repo has fixed the issue. I can now see fail2ban chain in iptables, which was there before.

Thanx for the help

**Comment by sebres** [comment]
Great, that works.
