### ISSUE TITLE
sshd jail does not find valid matches in the journal

### ISSUE THREAD

**Issue by goeranu** [fail2ban/fail2ban#1341]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): 0.9.3-1.fc23
- OS, including release name/version: Fedora 23
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:
For some reason, the _sshd_ jail isn't finding the matches it ought to find.  I have configured fail2ban to use the systemd backend by default, and it seems to work for example for the _dovecot_ jail, but not for _sshd_.  I've tried to match the strings from `journalctl` commands, and the expressions do match.  But nothing is banned, and no matches show up in `fail2ban.log`.

#### Steps to reproduce
Enable the _sshd_ jail and wait for attacks.

#### Expected behavior
Matches listed in `/var/log/fail2ban.log`, and after a few matches from the same host, that host being banned.

#### Observed behavior
No obvious action from fail2ban.

### Configuration, dump and another helpful excerpts
This is the status of the jail:
```
mimmi$ sudo fail2ban-client status sshd
[sudo] password for root: 
Status for the jail: sshd
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     0
|  `- Journal matches:  _SYSTEMD_UNIT=sshd.service + _COMM=sshd
`- Actions
   |- Currently banned: 0
   |- Total banned:     0
   `- Banned IP list:
```
#### Any customizations done to /etc/fail2ban/ configuration
I've done these relevant customizations in `jail.local`
```
[DEFAULT]
bantime = 86400
backend = systemd
…
[sshd]
enabled = true
…
```
(Several other jails are also enabled, excluded here.)
#### Relevant parts of /var/log/fail2ban.log file:
The only thing that shows up are the standard messages at startup, like these:
```
2016-02-29 19:00:05,535 fail2ban.jail           [24435]: INFO    Creating new jail 'sshd'
2016-02-29 19:00:05,558 fail2ban.jail           [24435]: INFO    Jail 'sshd' uses systemd
2016-02-29 19:00:05,581 fail2ban.jail           [24435]: INFO    Initiated 'systemd' backend
2016-02-29 19:00:06,902 fail2ban.filter         [24435]: INFO    Set maxRetry = 5
2016-02-29 19:00:06,905 fail2ban.actions        [24435]: INFO    Set banTime = 86400
2016-02-29 19:00:06,907 fail2ban.filter         [24435]: INFO    Set findtime = 600
2016-02-29 19:00:06,908 fail2ban.filter         [24435]: INFO    Set maxlines = 10
2016-02-29 19:00:07,015 fail2ban.filtersystemd  [24435]: INFO    Added journal match for: '_SYSTEMD_UNIT=sshd.service + _COMM=sshd'
```

#### Relevant lines from monitored log files in question:
If I try that journal match myself, I get several lines, some of which ought to match
```
mimmi$ journalctl --since today _SYSTEMD_UNIT=sshd.service + _COMM=sshd
…
feb 29 03:22:13 mimmi sshd[1180]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
…
```

**Comment by yarikoptic** [comment]
> If I try that journal match myself, I get several lines, some of which ought to match
> ```
> mimmi$ journalctl --since today _SYSTEMD_UNIT=sshd.service + _COMM=sshd
> …
> feb 29 03:22:13 mimmi sshd[1180]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
> …
> ```
if that was the only hit -- your maxRetry is 5, so no action would be
triggered.  provide more context from the log if there were more hits

**Comment by goeranu** [comment]
It's not the only hit  But even if it was, it should be listed on a _found_ line in `fail2ban.log`shouldn't it?

With the risk of spamming, here is today's catch:
```
mimmi$ journalctl --since today _SYSTEMD_UNIT=sshd.service + _COMM=sshd | grep AllowUsers
feb 29 00:35:09 mimmi sshd[18545]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
feb 29 01:29:27 mimmi sshd[19651]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
feb 29 02:23:11 mimmi sshd[20801]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
feb 29 03:22:13 mimmi sshd[1180]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
feb 29 03:48:51 mimmi sshd[1707]: User ftp from 146.0.77.66 not allowed because not listed in AllowUsers
feb 29 03:48:59 mimmi sshd[1717]: User root from 146.0.77.66 not allowed because not listed in AllowUsers
feb 29 04:25:33 mimmi sshd[2641]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
feb 29 05:44:44 mimmi sshd[4223]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
feb 29 05:59:14 mimmi sshd[4500]: User root from 144.0.34.235 not allowed because not listed in AllowUsers
feb 29 06:49:28 mimmi sshd[5669]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
feb 29 07:52:44 mimmi sshd[7034]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
feb 29 08:56:49 mimmi sshd[8394]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
feb 29 10:03:03 mimmi sshd[10763]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
feb 29 11:05:45 mimmi sshd[12247]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
feb 29 11:52:05 mimmi sshd[13331]: User root from 117.244.25.220 not allowed because not listed in AllowUsers
feb 29 12:15:12 mimmi sshd[13944]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
feb 29 13:25:07 mimmi sshd[15854]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
feb 29 14:32:30 mimmi sshd[17323]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
feb 29 15:41:06 mimmi sshd[18869]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
feb 29 17:10:52 mimmi sshd[21082]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
feb 29 17:45:58 mimmi sshd[21922]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
feb 29 18:31:01 mimmi sshd[23634]: User root from 183.3.202.104 not allowed because not listed in AllowUsers
feb 29 18:42:31 mimmi sshd[23883]: User root from 146.0.77.66 not allowed because not listed in AllowUsers
feb 29 18:42:31 mimmi sshd[23885]: User root from 146.0.77.66 not allowed because not listed in AllowUsers
feb 29 18:42:31 mimmi sshd[23889]: User root from 146.0.77.66 not allowed because not listed in AllowUsers
feb 29 18:42:32 mimmi sshd[23891]: User root from 146.0.77.66 not allowed because not listed in AllowUsers
```

**Comment by yarikoptic** [comment]
now point me to at least a single IP which tried to access your server unsuccessfully at least 5 times within 10 minutes?

reopen if you find any ;)

**Comment by yarikoptic** [comment]
actually now I am confused myself -- indeed, "Found" should be spitted out at INFO level which is the default but I don't see it in my log either...

**Comment by yarikoptic** [comment]
please run it for a big with loglevel=DEBUG and see what is reported

**Comment by goeranu** [comment]
I've added loglevel=DEBUG and ran a `fail2ban-client reload`.  That seems like it helped?!?  Just after I did, there was another (single) attempt to log in as root, this time from 183.3.202.104.  And that attempt **was** listed with a “Found” line in `fail2ban.log`.  It wasn't because of the logging itself; I put it in the wrong section at first.  But I guess the reload triggered something.  Maybe this is a problem that only appears when fail2ban has been running for a while?

I'm not sure what "run it for a big" means.  The same as "run it for a while"?

**Comment by goeranu** [comment]
I made an experiment and tried to repeatedly ssh as root from an internal host.  That **did** trigger the jail, and the host got banned.  But since it was after the reload, I'm not sure if it says anything.

**Comment by goeranu** [comment]
Fail2ban did indeed stop detecting new sshd attempts after a while.   Doing `grep sshd..Found` on the log ends at 2016-03-02 08:44:15,980.  Looking for one of the possible patterns, “not listed in AllowUsers”, in the journal lists several attempts after that.  

I'm running with debug logging now, and the log around the last successful detection looks like this:
```
2016-03-02 08:44:15,840 fail2ban.datedetector   [28853]: DEBUG   Sorting the template list
2016-03-02 08:44:15,840 fail2ban.datedetector   [28853]: DEBUG   Winning template: Epoch with 25351 hits
2016-03-02 08:44:15,979 fail2ban.filtersystemd  [28853]: DEBUG   Read systemd journal entry: u'2016-03-02T08:44:15.975487 mimmi sshd[13777]: Invalid user admin from 91.236.74.6'
2016-03-02 08:44:15,980 fail2ban.filter         [28853]: DEBUG   Processing line with time:1456904655.98 and ip:91.236.74.6
2016-03-02 08:44:15,980 fail2ban.filter         [28853]: INFO    [sshd] Found 91.236.74.6
2016-03-02 08:44:15,980 fail2ban.filtersystemd  [28853]: DEBUG   Read systemd journal entry: u'2016-03-02T08:44:15.975487 mimmi sshd[13777]: Invalid user admin from 91.236.74.6'
2016-03-02 08:44:15,981 fail2ban.failmanager    [28853]: DEBUG   Total # of detected failures: 50. Current failures from 2 IPs (IP:count): 91.236.74.6:1, 183.3.202.101:1
2016-03-02 08:44:15,981 fail2ban.filtersystemd  [28853]: DEBUG   Read systemd journal entry: u'2016-03-02T08:44:15.976485 mimmi sshd[13777]: input_userauth_request: invalid user admin [preauth]'
2016-03-02 08:44:15,982 fail2ban.filtersystemd  [28853]: DEBUG   Read systemd journal entry: u'2016-03-02T08:44:15.976485 mimmi sshd[13777]: input_userauth_request: invalid user admin [preauth]'
2016-03-02 08:44:16,016 fail2ban.filterpyinotify[28853]: DEBUG   Default Callback for Event: <Event dir=False mask=0x2 maskname=IN_MODIFY name='' path=/var/log/audit/audit.log pathname=/var/log/audit/audit.log wd=3 >
2016-03-02 08:44:16,017 fail2ban.filtersystemd  [28853]: DEBUG   Read systemd journal entry: u'2016-03-02T08:44:16.016183 mimmi sshd[13777]: Received disconnect from 91.236.74.6: 11: Normal Shutdown, Thank you for playing [preauth]'
```
Then, in the journal I have, for example, this entry
```
mar 04 21:02:16 mimmi sshd[6129]: User root from 183.3.202.101 not allowed because not listed in AllowUsers
```
The fail2ban log around the same time looks like this
```
2016-03-04 21:01:56,773 fail2ban.datedetector   [28853]: DEBUG   Sorting the template list
2016-03-04 21:01:56,773 fail2ban.datedetector   [28853]: DEBUG   Winning template: Epoch with 37368 hits
2016-03-04 21:02:16,094 fail2ban.filtersystemd  [28853]: DEBUG   Read systemd journal entry: u'2016-03-04T21:02:16.087365 mimmi sshd[6129]: User root from 183.3.202.101 not allowed because not listed in AllowUsers'
2016-03-04 21:02:16,096 fail2ban.filtersystemd  [28853]: DEBUG   Read systemd journal entry: u'2016-03-04T21:02:16.088297 mimmi sshd[6129]: input_userauth_request: invalid user root [preauth]'
2016-03-04 21:02:16,096 fail2ban.filtersystemd  [28853]: DEBUG   Read systemd journal entry: u'2016-03-04T21:02:16.088321 mimmi sshd[6129]: Received disconnect from 183.3.202.101: 11:  [preauth]'
2016-03-04 21:02:16,097 fail2ban.filtersystemd  [28853]: DEBUG   Read systemd journal entry: u'2016-03-04T21:02:16.088340 mimmi sshd[6129]: Disconnected from 183.3.202.101 [preauth]'
2016-03-04 21:02:16,389 fail2ban.filterpyinotify[28853]: DEBUG   Default Callback for Event: <Event dir=False mask=0x2 maskname=IN_MODIFY name='' path=/var/log/audit/audit.log pathname=/var/log/audit/audit.log wd=3 >
2016-03-04 21:02:16,389 fail2ban.datedetector   [28853]: DEBUG   Matched time template Epoch
```
That is, it appears to get the entry from the journal, but it doesn't do anything with it.

Any idea what I should try next?

**Comment by goeranu** [comment]
Ah, searching through the logs a bit more, I found something interesting not long after the last match:
```
2016-03-02 08:50:20,519 fail2ban.datedetector   [28853]: DEBUG   Matched time template Epoch
2016-03-02 08:50:20,519 fail2ban.datedetector   [28853]: DEBUG   Got time 1456905020.501000 for "u'1456905020.501'" using template Epoch
2016-03-02 08:50:20,642 fail2ban.filtersystemd  [28853]: DEBUG   Read systemd journal entry: '2016-03-02T08:50:20.580884 mimmi sshd[13893]: pam_unix(sshd:session): session opened for user g\xc3\xb6ran by (uid=0)'
2016-03-02 08:50:20,644 fail2ban.filtersystemd  [28853]: DEBUG   Read systemd journal entry: '2016-03-02T08:50:20.580884 mimmi sshd[13893]: pam_unix(sshd:session): session opened for user g\xc3\xb6ran by (uid=0)'
2016-03-02 08:50:20,644 fail2ban                [28853]: CRITICAL Unhandled exception in Fail2Ban:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fail2ban/server/jailthread.py", line 66, in run_with_except_hook
    run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fail2ban/server/filtersystemd.py", line 246, in run
    *self.formatJournalEntry(logentry))
  File "/usr/lib/python2.7/site-packages/fail2ban/server/filter.py", line 422, in processLineAndAdd
    for element in self.processLine(line, date)[1]:
  File "/usr/lib/python2.7/site-packages/fail2ban/server/filter.py", line 417, in processLine
    tupleLine, date, returnRawHost, checkAllRegex)
  File "/usr/lib/python2.7/site-packages/fail2ban/server/filter.py", line 497, in findFailure
    failRegex.search(self.__lineBuffer)
  File "/usr/lib/python2.7/site-packages/fail2ban/server/failregex.py", line 83, in search
    "\n".join("".join(value[::2]) for value in tupleLines) + "\n")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 69: ordinal not in range(128)
2016-03-02 08:50:20,661 fail2ban.datedetector   [28853]: DEBUG   Sorting the template list
2016-03-02 08:50:20,678 fail2ban.datedetector   [28853]: DEBUG   Winning template: Epoch with 25392 hits
```
Fail2ban can not handle the non-ascii characters in the user name it seems.  The infamous string handling of Python strikes again.

**Comment by yarikoptic** [comment]
Man jail.conf to find logencoding setting for such cases when log files are utf or other encoding

**Comment by goeranu** [comment]
Hm, but that entry says “Default value of "auto" uses current system locale” so it ought to work already.  And indeed, I many entries like these in the log file
```
2016-02-29 19:01:09,264 fail2ban.filter         [24435]: INFO    Set jail log file encoding to UTF-8
```
I'll double check by explicitly setting it for the sshd jail.

**Comment by goeranu** [comment]
I changed the in my `jail.local` to this
```
[sshd]
enabled = true
logencoding=UTF-8
```
Then I repeated the login attempt, and I get the same python traceback.

**Comment by yarikoptic** [comment]
aha... indeed and here you are using systemd backend and it could well be that it doesn't care about "logencoding".  I will check

**Comment by yarikoptic** [comment]
seems to handle log lines in journal with utf8 logins just fine... judging from the backtrace `session opened for user g\xc3\xb6ran by (uid=0` -- what is that user name exactly? (I guess you know since session was opened)

in https://github.com/fail2ban/fail2ban/pull/1344 I did some attempt at explicit decoding of the logged msg (if wasn't a unicode)... but not sure if I should've not just made it more explicit and per each entry in logentry.  You could try that patch for you (commit 8db9576c8a6570410f4cbd28c65f19735f200dc1) but don't know at all if works at all -- apparently that portion of the code is undertested!

**Comment by goeranu** [comment]
\xc3\xb6 is the UTF-8 code for o-diaeresis (ö).  The log I showed was my own login from work to my home system.  When looking at it using `journalctl` it looks like this:
```
mar 02 08:50:20 mimmi sshd[13893]: pam_unix(sshd:session): session opened for user göran by (uid=0)
```
I tried your patch standalone, but I got another traceback.  I'm guessing this patch requires other updates after the 0.9.3 I'm running.
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fail2ban/server/jailthread.py", line 66, in run_with_except_hook
    run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fail2ban/server/filtersystemd.py", line 250, in run
    *self.formatJournalEntry(logentry, self.getEncoding()))
AttributeError: 'FilterSystemd' object has no attribute 'getEncoding'
```

**Comment by NoTeefy** [comment]
Hello I stuck upon the same problem... Fail2Ban stopped recognizing login attempts when I updated it to the 9.5.0 version.
My jails look like this:
`[sshd]

enabled  = true
port    = ssh
filter   = sshd
action   = iptables[name=SSH, port=ssh, protocol=tcp]
           blocklist_de[email="xxx@xxx.xx", apikey="xxxx", service=%(filter)s]
logpath = %(sshd_log)s
backend = systemd
maxretry = 3
findtime = 86400

[sshd-ddos]
# This jail corresponds to the standard configuration in Fail2ban.
# The mail-whois action send a notification e-mail with a whois request
# in the body.
enabled  = true
port    = ssh
filter   = sshd-ddos
action   = iptables[name=SSH, port=ssh, protocol=tcp]
           blocklist_de[email="xxx@xxx.xx", apikey="xxxx", service=%(filter)s]
logpath = %(sshd_log)s
backend = systemd
maxretry = 3
findtime = 86400`

And from the logging side I get logs like this:
`2016-08-30 20:40:07,715 fail2ban.filtersystemd  [4203]: DEBUG   Read systemd journal entry: '2016-08-30T20:34:21.063236 ns3031426.ip-149-202-223.eu sshd[6467]: Disconnected from xx.xxx.xxx.xxx port 46349 [preauth]'
2016-08-30 20:40:07,715 fail2ban.filtersystemd  [4203]: DEBUG   Read systemd journal entry: '2016-08-30T20:34:21.085503 ns3031426.ip-149-202-223.eu sshd[6469]: Connection from xx.xxx.xxx.xxx port 53353 on 149.202.223.108 port 22'
2016-08-30 20:40:07,715 fail2ban.filtersystemd  [4203]: DEBUG   Read systemd journal entry: '2016-08-30T20:34:23.120815 ns3031426.ip-149-202-223.eu sshd[6469]: Invalid user operator from xx.xxx.xxx.xxx port 53353'
2016-08-30 20:40:07,716 fail2ban.filtersystemd  [4203]: DEBUG   Read systemd journal entry: '2016-08-30T20:34:23.120909 ns3031426.ip-149-202-223.eu sshd[6469]: input_userauth_request: invalid user operator [preauth]'
2016-08-30 20:40:07,716 fail2ban.filtersystemd  [4203]: DEBUG   Read systemd journal entry: '2016-08-30T20:34:25.381255 ns3031426.ip-149-202-223.eu sshd[6469]: Received disconnect from xx.xxx.xxx.xxx port 53353:11:  [preauth]'
2016-08-30 20:40:07,716 fail2ban.filtersystemd  [4203]: DEBUG   Read systemd journal entry: '2016-08-30T20:34:25.381268 ns3031426.ip-149-202-223.eu sshd[6469]: Disconnected from xx.xxx.xxx.xxx port 53353 [preauth]'
2016-08-30 20:40:07,716 fail2ban.filtersystemd  [4203]: DEBUG   Read systemd journal entry: '2016-08-30T20:34:25.404018 ns3031426.ip-149-202-223.eu sshd[6474]: Connection from xx.xxx.xxx.xxx port 53734 on 149.202.223.108 port 22'
2016-08-30 20:40:07,716 fail2ban.filtersystemd  [4203]: DEBUG   Read systemd journal entry: '2016-08-30T20:34:26.246909 ns3031426.ip-149-202-223.eu sshd[6474]: Invalid user webadmin from xx.xxx.xxx.xxx port 53734'
2016-08-30 20:40:07,716 fail2ban.filtersystemd  [4203]: DEBUG   Read systemd journal entry: '2016-08-30T20:34:26.247016 ns3031426.ip-149-202-223.eu sshd[6474]: input_userauth_request: invalid user webadmin [preauth]'
2016-08-30 20:40:07,716 fail2ban.filtersystemd  [4203]: DEBUG   Read systemd journal entry: '2016-08-30T20:34:28.423240 ns3031426.ip-149-202-223.eu sshd[6474]: Received disconnect from xx.xxx.xxx.xxx port 53734:11:  [preauth]'
2016-08-30 20:46:54,519 fail2ban.filtersystemd  [4203]: DEBUG   Read systemd journal entry: '2016-08-30T20:46:54.097943 ns3031426.ip-149-202-223.eu sshd[7634]: Connection from xx.xxx.xxx.xxx port 1112 on 149.202.223.108 port 22'
2016-08-30 20:46:54,519 fail2ban.filtersystemd  [4203]: DEBUG   Read systemd journal entry: '2016-08-30T20:46:54.097943 ns3031426.ip-149-202-223.eu sshd[7634]: Connection from xx.xxx.xxx.xxx port 1112 on 149.202.223.108 port 22'
2016-08-30 20:46:55,019 fail2ban.filtersystemd  [4203]: DEBUG   Read systemd journal entry: '2016-08-30T20:46:54.582124 ns3031426.ip-149-202-223.eu sshd[7634]: Received disconnect from xx.xxx.xxx.xxx port 1112:11: Bye Bye [preauth]'
2016-08-30 20:46:55,019 fail2ban.filtersystemd  [4203]: DEBUG   Read systemd journal entry: '2016-08-30T20:46:54.582124 ns3031426.ip-149-202-223.eu sshd[7634]: Received disconnect from xx.xxx.xxx.xxx port 1112:11: Bye Bye [preauth]'
2016-08-30 20:46:55,019 fail2ban.filtersystemd  [4203]: DEBUG   Read systemd journal entry: '2016-08-30T20:46:54.582136 ns3031426.ip-149-202-223.eu sshd[7634]: Disconnected from xx.xxx.xxx.xxx port 1112 [preauth]'
2016-08-30 20:46:55,020 fail2ban.filtersystemd  [4203]: DEBUG   Read systemd journal entry: '2016-08-30T20:46:54.582136 ns3031426.ip-149-202-223.eu sshd[7634]: Disconnected from xx.xxx.xxx.xxx port 1112 [preauth]'
`
If I run the **fail2ban-regex "systemd-journal" /etc/fail2ban/filter.d/sshd.conf** command he gives me back: `Running tests
=============

Use   failregex filter file : sshd, basedir: /etc/fail2ban
Use         maxlines : 10
Use    journal match : _SYSTEMD_UNIT=sshd.service + _COMM=sshd


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Lines: 613 lines, 0 ignored, 0 matched, 613 missed
[processed in 0.34 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 613 lines`
What is the problem right here? Can't find any errors even with fail2ban DEBUG logging on.


Best regards

**Comment by sebres** [comment]
> Fail2Ban stopped recognizing login attempts when I updated it to the 9.5.0 version.

abovementioned issue describes the stopping of jail working (with unhandled exception) after some non-decode-able characters in message of systemd (missed auto-converting + not sufficiently failure protected). This one has nothing with update to 0.9.5...

Your case is a little bit different: fail2ban-regex finds no matches using sshd-filter. That is very weird, because the given log excerpt shows, that it should find some failures...

**Comment by NoTeefy** [comment]
Yes, I'm sorry for posting it here, thought it would go in the same direction. How can I fix those problems? I don't get any errors even with loglevel=debug . It just reads those failed attempts but doesn't do anything about it...

Best regards

**Comment by sebres** [comment]
@NoTeefy

I think in your case it is (new sshd format) - optional port part, that currently not in our failregex. Just try to replace in `sshd.conf`:

```diff
- ^%(__prefix_line)s[iI](?:llegal|nvalid) user .* from <HOST>\s*$
+ ^%(__prefix_line)s[iI](?:llegal|nvalid) user .*? from <HOST>(?:\s+port\s+\d+)?\s*$
```

**Comment by NoTeefy** [comment]
Thanks! That fixed it. Where else do I need to add this part? Are you going to change it globally in a new version?

Best regards

**Comment by sebres** [comment]
To the origin issue - this bug occurred if first and last arguments of tupleLine passed to the processLineAndAdd from systemd have not the same type (e.g. 1st - str, 3th - unicode, or vice versa)...

Additionally it is obvious the way how different python versions does default "converting", resp. encoding/decoding, see this one:
```bash
python3 -c "print([isinstance('', str), isinstance(b'', str), isinstance(u'', str)])"
[True, False, True]
python2 -c "print([isinstance('', str), isinstance(b'', str), isinstance(u'', str)])"
[True, True, False]
```

I'll fix it...

**Comment by sebres** [comment]
@goeranu #1542 should fix this issue (build for two versions - 0.9 and 0.10), can you please test it on your system (in operation or just the test-cases).

**Comment by goeranu** [comment]
It was a bit harder than I first thought to do it in operation.  Since I made this report, Fedora has switched to running fail2ban with Python 3.  After the switch, I don't see the problem any more.  In order to test if the bug is gone for Python 2 as well, I tried simply changing the #!-line and copying the library files between the `/usr/lib/python*` trees.  It wasn't that easy; the files wouldn't run using Python 2.  (It complains about some configuration file, I didn't investigate further.)

To at least run the test cases, I cloned the code and ran the `fail2ban-testcases-all` script.  I had to change `systemd-path system-state-logs` to `systemd-path system-state-logs` in `fail2ban/tests/filtertestcase.py`.  After that, all tests passes.

I tried to run the tests using `fail2ban-testcases-all-python3` too, but hit several incompatibilities.  I hacked around a few, but after just finding more I decided to give this reply before continuing.

I can dig into this more if it would be of any help.  But I thought I'd check before spending much time on it.

**Comment by sebres** [comment]
Thanks a lot.

BTW. The easiest kind of testing for me:
```bash
cd /tmp/
git clone https://github.com/fail2ban/fail2ban.git -b 0.10; # or tar xvfj ...
cd fail2ban
# for python 3:
fail2ban-2to3; # expected if you use python 3.x
# start test:
PYTHONPATH=. bin/fail2ban-testcases
# or using targeted version:
PYTHONPATH=. python3.5 bin/fail2ban-testcases
```

**Comment by goeranu** [comment]
Oh, I didn't realise one was supposed to swap the files between the language versions in that way.  I did another try now.  At first `fail2ban-2to3` failed because it couldn't do some UTF-8 decoding.  :smile:  After cloning to `/tmp` instead of my home directory, that part worked.

The tests themselves worked mostly, except that the SMTPActionTests, all four of them, failed with Connection refused.  Like before, should I try to trace why?  (It won't be tonight.)

B.t.w., the repository I cloned was your _sebres/fail2ban_ using the _\_0.10/fix-systemd-convert-gh-1341_ branch.

**Comment by sebres** [comment]
> The tests themselves worked mostly, except that the SMTPActionTests, all four of them, failed with Connection refused. Like before, should I try to trace why?

That may occurr (network specified thing)... No problem.

> _0.10/fix-systemd-convert-gh-1341 

Yes, this is the right thing.

Needed test cases by this branch would be `PYTHONPATH=. bin/fail2ban-testcases -f WrongChar`
If this works, it's alright!

Thx a lot!
