### ISSUE TITLE
ERROR: testSampleRegexsASTERISK (fail2ban.tests.samplestestcase.FilterSamplesRegex)

### ISSUE THREAD

**Issue by opoplawski** [fail2ban/fail2ban#1352]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): 0.9.4
- OS, including release name/version: Fedora Rawhide (F25)
### The issue:

```
ERROR: testSampleRegexsASTERISK (fail2ban.tests.samplestestcase.FilterSamplesRegex)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/samplestestcase.py", line 91, in testFilter
    for line in logFile:
  File "/usr/lib64/python3.5/fileinput.py", line 265, in __next__
    line = self.readline()
  File "/usr/lib64/python3.5/fileinput.py", line 370, in readline
    self._buffer = self._file.readlines(self._bufsize)
  File "/usr/lib64/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 6963: ordinal not in range(128)
```
#### Steps to reproduce

```
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.LC5buM
+ umask 022
+ cd /builddir/build/BUILD
+ cd fail2ban-0.9.4
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ ./fail2ban-testcases-all-python3 --no-network
Testing using /usr/bin/python3.5
Fail2ban 0.9.4 test suite. Python 3.5.1 (default, Mar  4 2016, 13:43:50) [GCC 6.0.0 20160302 (Red Hat 6.0.0-0.14)]. Please wait...
```

**Comment by opoplawski** [comment]
This is another test that is only failing in my local mock builds - not sure what it going on yet...

**Comment by sebres** [comment]
I say you: your mock does something within your env or python-env (no more conform to f2b)...
The question is what?

**Comment by sebres** [comment]
close for no activity (please reopen if still acute)
