### ISSUE TITLE
iptables -w and iptables multiport errors in fail2ban 0.9.3

### ISSUE THREAD

**Issue by keithchristian** [fail2ban/fail2ban#1364]
Log excerpt:

```
2016-03-15 21:48:43,762 fail2ban.action         [27407]: ERROR   iptables -w -D INPUT -p tcp -m multiport --dports http,https -j f2b-ALL
2016-03-15 21:48:43,763 fail2ban.action         [27407]: ERROR   iptables -w -D INPUT -p tcp -m multiport --dports http,https -j f2b-ALL
2016-03-15 21:48:43,763 fail2ban.action         [27407]: ERROR   iptables -w -D INPUT -p tcp -m multiport --dports http,https -j f2b-ALL
2016-03-15 21:48:43,763 fail2ban.actions        [27407]: ERROR   Failed to stop jail 'apache-403' action 'iptables-multiport': Error stopping action
2016-03-15 21:48:52,526 fail2ban.server         [27856]: ERROR   Unable to import fail2ban database module as sqlite is not available.
2016-03-15 21:48:53,575 fail2ban.action         [27856]: ERROR   iptables <lockingopt> -N f2b-ALL
2016-03-15 21:48:53,576 fail2ban.action         [27856]: ERROR   iptables <lockingopt> -N f2b-ALL
2016-03-15 21:48:53,576 fail2ban.action         [27856]: ERROR   iptables <lockingopt> -N f2b-ALL
2016-03-15 21:48:53,577 fail2ban.actions        [27856]: ERROR   Failed to start jail 'apache-403' action 'iptables-multiport': Error starting action
```
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_
- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)
### The issue:

_Summary here_
#### Any customizations done to /etc/fail2ban/ configuration

```
```
#### Relevant parts of /var/log/fail2ban.log file:

_preferably obtained while running fail2ban with `loglevel = 4`_

```
```
#### Relevant lines from monitored log files in question:

```
```

**Comment by illuusio** [comment]
Same goes with openSUSE 13.2 and 0.9.3
<pre>
2016-03-19 08:52:54,320 fail2ban.action         [20517]: ERROR   iptables -w -N f2b-pure-ftpd-nocleartext
iptables -w -A f2b-pure-ftpd-nocleartext -j RETURN
iptables -w -I INPUT -p tcp -m multiport --dports ftp,ftp-data,ftps,ftps-data -j f2b-pure-ftpd-nocleartext -- returned 1
2016-03-19 08:52:54,321 fail2ban.actions        [20517]: ERROR   Failed to start jail 'pure-ftpd-nocleartext' action 'iptables-multiport': Error starting action
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fail2ban/server/actions.py", line 221, in run
    action.start()
  File "/usr/lib/python2.7/site-packages/fail2ban/server/action.py", line 281, in start
    raise RuntimeError("Error starting action")
RuntimeError: Error starting action
</pre>

**Comment by illuusio** [comment]
If you use non multiport version of action.d/iptables.conf and make all ports work separated confs then it works.. something strange in '-j' stuff.

**Comment by keithchristian** [comment]
I'll check that, thank you, @illuusio.
