### ISSUE TITLE
Fail2ban-regex fail testing

### ISSUE THREAD

**Issue by anthomaxcool** [fail2ban/fail2ban#1401]
Hi, I just installed fail2ban on Debian. I created the file jail.local, followed some tutorials to be sure I configured it properly.

I added this:

```
[tomcat7]
enabled = true
port    = http,https,8080,8443
filter  = tomcat
logpath = /my/log/path/file.log
maxretry = 5
```

After that, I created the file tomcat7.conf in /filter.d/ : 

```
[INCLUDES]

[Definition]

failregex = (FAILED LOGIN) .* ip:<HOST>

ignoreregex =
```

And then I created a log file just to test the regex with two lines (ip being real IP, not xxx..):

```
WARN : April 27, 2016 14:38:41: FAILED LOGIN for user: theUser with ip:xxx.xxx.xxx.xxx
WARN : 04-27-2016 08:58:48: FAILED LOGIN for user: theUser with ip:xxx.xxx.xxx.xxx
```

Then I wrote in my terminal:

```
fail2ban-regex /my/log/path.file.log /etc/fail2ban/filter.d/tomcat7.conf
```

The result is the following:

```
Running tests
=============

Use regex file : /etc/fail2ban/filter.d/tomcat7.conf
Use log file   : /my/log/path/file.log

Found a match for 'WARN : April 27, 2016 09:49:11: FAILED LOGIN for user: myUser with ip:xxx.xxx.xxx.xxx
' but no valid date/time found for 'WARN : April 27, 2016 09:49:11: FAILED LOGIN for user: myUser with ip:xxx.xxx.xxx.xxx
'. Please contact the author in order to get support for this format
Traceback (most recent call last):
  File "/usr/bin/fail2ban-regex", line 372, in <module>
    fail2banRegex.testRegex(line)
  File "/usr/bin/fail2ban-regex", line 225, in testRegex
    ret = self.__filter.processLine(line)
  File "/usr/share/fail2ban/server/filter.py", line 268, in processLine
    return self.findFailure(timeLine, logLine)
  File "/usr/share/fail2ban/server/filter.py", line 318, in findFailure
    date = self.dateDetector.getUnixTime(timeLine)
  File "/usr/share/fail2ban/server/datedetector.py", line 177, in getUnixTime
    date = self.getTime(line)
  File "/usr/share/fail2ban/server/datedetector.py", line 166, in getTime
    date = template.getDate(line)
  File "/usr/share/fail2ban/server/datetemplate.py", line 148, in getDate
    date = list(time.strptime(conv, pattern))
  File "/usr/lib/python2.7/_strptime.py", line 467, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib/python2.7/_strptime.py", line 308, in _strptime
    format_regex = _TimeRE_cache.compile(format)
  File "/usr/lib/python2.7/_strptime.py", line 265, in compile
    return re_compile(self.pattern(format), IGNORECASE)
  File "/usr/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
sre_constants.error: redefinition of group name 'Y' as group 7; was group 3
```

What's going on? Thanks for any help

**Comment by anthomaxcool** [comment]
I tried a lot of datepattern in the config. None seems to work. I ended up changing the date pattern iteself in the log. What I understood is that I need to respect those pattern, which only showed when one suceed:

```
0 hit(s): MONTH Day Hour:Minute:Second
0 hit(s): WEEKDAY MONTH Day Hour:Minute:Second Year
0 hit(s): WEEKDAY MONTH Day Hour:Minute:Second
2 hit(s): Year/Month/Day Hour:Minute:Second
0 hit(s): Day/Month/Year Hour:Minute:Second
0 hit(s): Day/Month/Year Hour:Minute:Second
0 hit(s): Day/MONTH/Year:Hour:Minute:Second
0 hit(s): Month/Day/Year:Hour:Minute:Second
0 hit(s): Year-Month-Day Hour:Minute:Second
0 hit(s): Year.Month.Day Hour:Minute:Second
0 hit(s): Day-MONTH-Year Hour:Minute:Second[.Millisecond]
0 hit(s): Day-Month-Year Hour:Minute:Second
0 hit(s): TAI64N
0 hit(s): Epoch
0 hit(s): ISO 8601
0 hit(s): Hour:Minute:Second
0 hit(s): <Month/Day/Year@Hour:Minute:Second>
```
