### ISSUE TITLE
0.10 - deprecated DNSUtils.IsValidIP in fakegooglebot ignore command

### ISSUE THREAD

**Issue by artyomsol** [fail2ban/fail2ban#1559]
### Environment:
- Fail2Ban version (including any possible distribution suffixes):  0.10.0a2 0a7374dec69bbbe54e0180c80c8d3b653fd1012f
- OS, including release ame/version: Debian 3.2.81-2 x86_64 GNU/Linux
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
Deprecated DNSUtils.isValidIP method used at 
[ignorecommands/apache-fakegooglebot#L18](https://github.com/fail2ban/fail2ban/blob/d71a525a851286392297ffcadb06159e9ac405ba/config/filter.d/ignorecommands/apache-fakegooglebot#L18) 

#### Steps to reproduce
```bash
/etc/fail2ban/filter.d/ignorecommands/apache-fakegooglebot 66.249.65.52; echo $?
```
#### Expected behavior

`0`

#### Observed behavior

```
Traceback (most recent call last):
  File "/etc/fail2ban/filter.d/ignorecommands/apache-fakegooglebot", line 35, in <module>
    is_googlebot(process_args(sys.argv))
  File "/etc/fail2ban/filter.d/ignorecommands/apache-fakegooglebot", line 18, in process_args
    if not DNSUtils.isValidIP(ip):
AttributeError: class DNSUtils has no attribute 'isValidIP'
```

#### Relevant parts of /var/log/fail2ban.log file:
```
2016-09-23 23:34:07,817 fail2ban.utils          [11711]: ERROR   /etc/fail2ban/filter.d/ignorecommands/apache-fakegooglebot 66.249.65.52 -- stderr:
2016-09-23 23:34:07,818 fail2ban.utils          [11711]: ERROR    -- stderr: 'Traceback (most recent call last):'
2016-09-23 23:34:07,818 fail2ban.utils          [11711]: ERROR    -- stderr: '  File "/etc/fail2ban/filter.d/ignorecommands/apache-fakegooglebot", line 35, in <module>'
2016-09-23 23:34:07,818 fail2ban.utils          [11711]: ERROR    -- stderr: '    is_googlebot(process_args(sys.argv))'
2016-09-23 23:34:07,818 fail2ban.utils          [11711]: ERROR    -- stderr: '  File "/etc/fail2ban/filter.d/ignorecommands/apache-fakegooglebot", line 18, in process_a
rgs'
2016-09-23 23:34:07,818 fail2ban.utils          [11711]: ERROR    -- stderr: '    if not DNSUtils.isValidIP(ip):'
2016-09-23 23:34:07,818 fail2ban.utils          [11711]: ERROR    -- stderr: "AttributeError: class DNSUtils has no attribute 'isValidIP'"
2016-09-23 23:34:07,819 fail2ban.utils          [11711]: ERROR   /etc/fail2ban/filter.d/ignorecommands/apache-fakegooglebot 66.249.65.52 -- returned 1
```

**Comment by artyomsol** [comment]
Could be fixed like this:
```diff
@@ -14,8 +14,8 @@

     ip = argv[1]

-    from fail2ban.server.ipdns import DNSUtils
-    if not DNSUtils.isValidIP(ip):
+    from fail2ban.server.ipdns import IPAddr
+    if not IPAddr(ip).isValid:
        sys.stderr.write("Argument must be a single valid IP. Got: %s\n"
                         % ip)
        sys.exit(3)
```

**Comment by KALRONG** [comment]
I was curious about why I was receiving so many emails regarding the google bots being banned even after checking that they were valid ones and found this same error in my logs.

I have applied your patch and will let it run for a couple of days to see how it does.

Thanks a lot!

**Comment by KALRONG** [comment]
Looks like in my case the error is even bigger:

2016-09-24 08:46:47,618 fail2ban.action         [11216]: ERROR   /etc/fail2ban/filter.d/ignorecommands/apache-fakegooglebot 66.249.66.141 -- stderr: b'Traceback (most recent call last):\n  File "/etc/fail2ban/filter.d/ignorecommands/apache-fakegooglebot", line 34, in <module>\n    is_googlebot(process_args(sys.argv))\n  File "/etc/fail2ban/filter.d/ignorecommands/apache-fakegooglebot", line 19, in process_args\n    from fail2ban.server.ipdns import IPAddr\nImportError: No module named fail2ban.server.ipdns\n'

Not sure if the root cause is the same or I should create a new ticket

**Comment by artyomsol** [comment]
@KALRONG this issue is about version 0.10.0a2 0a7374d 
What version of the fail2ban do you have ? Did you ever see the string `from fail2ban.server.ipdns import DNSUtils` in script patched ?

**Comment by KALRONG** [comment]
I have been trying to reproduce this manually and looks like the problem is that python doesn't find the fail2ban module at all therefore failing in the import.

**Comment by KALRONG** [comment]
@artyomsol Im using the latest package in debian repository for stretch:

Fail2Ban v0.9.3

Copyright (c) 2004-2008 Cyril Jaquier, 2008- Fail2Ban Contributors
Copyright of modifications held by their respective authors.
Licensed under the GNU General Public License v2 (GPL).

Written by Cyril Jaquier <cyril.jaquier@fail2ban.org>.
Many contributions by Yaroslav O. Halchenko <debian@onerussian.com>.

**Comment by KALRONG** [comment]
Found the problem, looks like the module is only avaliable for python3 but the script was calling python 2.7.9 

Sorry about this, let me know if you want me to remove my comments.
