### ISSUE TITLE
fail2ban 0.9.5 testVerbose failing in Fedora build

### ISSUE THREAD

**Issue by opoplawski** [fail2ban/fail2ban#1565]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.6.5
- OS, including release name/version: Fedora 26 (rawhide)

### The issue:

```
+ ./fail2ban-testcases-all-python3 --no-network
Testing using /usr/bin/python3.5
Fail2ban 0.9.5 test suite. Python 3.5.2 (default, Sep 14 2016, 11:31:14) [GCC 6.2.1 20160901 (Red Hat 6.2.1-1)]. Please wait...
........................s........................................................................................................................................................................................................................F.....................s..
======================================================================
FAIL: testVerbose (fail2ban.tests.fail2banregextestcase.Fail2banRegexTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/fail2banregextestcase.py", line 162, in testVerbose
    self.assertLogged('141.3.81.106  Fri Aug 14 11:53:59 2015')
  File "./fail2ban/tests/utils.py", line 266, in assertLogged
    raise AssertionError("None among %r was found in the log: %r" % (s, logged))
AssertionError: None among ('141.3.81.106  Fri Aug 14 11:53:59 2015',) was found in the log: 'Setting usedns = warn for Filter(None)\nCreated Filter(None)\nUse   failregex line : (?:(?:Authentication failure|Failed [-/\\w+]+) for(...\nUse         log file : ./fail2ban/tests/files/testcase02.log\nUse         encoding : UTF-8\n\nMatched time template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nGot time 1471175460.000000 for "\'Aug 14 11:51:00\'" using template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nSorting the template list\nWinning template: (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)? with 1 hits\nMatched time template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nGot time 1471175520.000000 for "\'Aug 14 11:52:00\'" using template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nMatched time template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nGot time 1471175580.000000 for "\'Aug 14 11:53:00\'" using template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nMatched time template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nGot time 1471175639.000000 for "\'Aug 14 11:53:59\'" using template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nMatched time template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nGot time 1471175699.000000 for "\'Aug 14 11:54:59\'" using template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nMatched time template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nGot time 1471175759.000000 for "\'Aug 14 11:55:59\'" using template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nMatched time template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nGot time 1471175761.000000 for "\'Aug 14 11:56:01\'" using template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nMatched time template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nGot time 1471175821.000000 for "\'Aug 14 11:57:01\'" using template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nMatched time template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nGot time 1471175879.000000 for "\'Aug 14 11:57:59\'" using template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nMatched time template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nGot time 1471175939.000000 for "\'Aug 14 11:58:59\'" using template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nMatched time template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nGot time 1471175941.000000 for "\'Aug 14 11:59:01\'" using template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nSorting the template list\nWinning template: (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)? with 11 hits\nMatched time template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nGot time 1471175941.000000 for "\'Aug 14 11:59:01\'" using template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nMatched time template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\nGot time 1471175941.000000 for "\'Aug 14 11:59:01\'" using template (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\n\nResults\n=======\n\nFailregex: 5 total\n|-  #) [# of hits] regular expression\n|   1) [5] (?:(?:Authentication failure|Failed [-/\\w+]+) for(?: [iI](?:llegal|nvalid) user)?|[Ii](?:llegal|nvalid) user|ROOT LOGIN REFUSED) .*(?: from|FROM) <HOST>\n|      66.38.192.238  Sun Aug 14 11:52:00 2016\n|      141.3.81.106  Sun Aug 14 11:53:59 2016\n|      141.3.81.106  Sun Aug 14 11:54:59 2016\n|      141.3.81.106  Sun Aug 14 11:57:59 2016\n|      141.3.81.106  Sun Aug 14 11:58:59 2016\n`-\n\nIgnoreregex: 0 total\n\nDate template hits:\n|- [# of hits] date format\n|  [13] (?:DAY )?MON Day 24hour:Minute:Second(?:\\.Microseconds)?(?: Year)?\n|  [0] (?:DAY )?MON Day Year 24hour:Minute:Second(?:\\.Microseconds)?\n|  [0] Year(?P<_sep>[-/.])Month(?P=_sep)Day 24hour:Minute:Second(?:,Microseconds)?\n|  [0] Day(?P<_sep>[-/])Month(?P=_sep)(?:Year|Year2) 24hour:Minute:Second\n|  [0] Day(?P<_sep>[-/])MON(?P=_sep)Year[ :]?24hour:Minute:Second(?:\\.Microseconds)?(?: Zone offset)?\n|  [0] Month/Day/Year:24hour:Minute:Second\n|  [0] Month-Day-Year 24hour:Minute:Second\\.Microseconds\n|  [0] TAI64N\n|  [0] Epoch\n|  [0] Year-Month-Day[T ]24hour:Minute:Second(?:\\.Microseconds)?(?:Zone offset)?\n|  [0] ^24hour:Minute:Second\n|  [0] ^<Month/Day/Year2@24hour:Minute:Second>\n|  [0] ^Year2MonthDay  ?24hour:Minute:Second\n|  [0] MON Day, Year 12hour:Minute:Second AMPM\n|  [0] ^MON-Day-Year2 24hour:Minute:Second\n`-\n\nLines: 13 lines, 0 ignored, 5 matched, 8 missed\n[processed in 0.01 sec]\n\n'
----------------------------------------------------------------------
```

Full log https://kojipkgs.fedoraproject.org//work/tasks/5788/15795788/build.log

Looks like there is a problem with matching the year .  The log only contains the day and month, so the ouput contains the current year:
```
Failregex: 5 total
 2016-10-03 11:58:53,865 139733034018560 |-  #) [# of hits] regular expression
|   1) [5] (?:(?:Authentication failure|Failed [-/\w+]+) for(?: [iI](?:llegal|nvalid) user)?|[Ii](?:llegal|nvalid) user|ROOT LOGIN REFUSED) .*(?: from|FROM) <HOST>
|      66.38.192.238  Sun Aug 14 11:52:00 2016
|      141.3.81.106  Sun Aug 14 11:53:59 2016
```
But the test match is looking for the 2015 date.

**Comment by opoplawski** [comment]
Ah, looks like this should be fixed with c49fe12f701807a8d89bfe57c9f7f492375a0a53
