### ISSUE TITLE
test failure in tag: 0.9.7 current -- test: testCymruInfoNxdomain on CentOS 7 current

### ISSUE THREAD

**Issue by herrold** [fail2ban/fail2ban#1841]
I rolled a tarball from the 0.9.7 tag

git archive --format=tar --prefix=fail2ban-0.9.7-latest/  0.9.7 | \
         gzip > fail2ban-0.9.7-latest.tar.gz

which builds, including tests, and runs fine in a CentOS 6 environment

trying the build fo that same set sources on CentOS 7 fails a test:
```
FAIL: testCymruInfoNxdomain (fail2ban.tests.banmanagertestcase.StatusExtendedCymruInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/banmanagertestcase.py", line 118, in testCymruInfoNxdomain
    "rir": ["nxdomain", "other"]})
  File "./fail2ban/tests/utils.py", line 410, in assert_dict_equal
    assert a==b, "Dictionaries differ:\n%r !=\n%r" % (a, b)
AssertionError: Dictionaries differ:
{'country': ['nxdomain', 'nxdomain'], 'rir': ['nxdomain', 'nxdomain'], 'asn': ['nxdomain', 'nxdomain']} !=
{'country': ['nxdomain', 'unknown'], 'rir': ['nxdomain', 'other'], 'asn': ['nxdomain', '4565']}
----------------------------------------------------------------------
Ran 286 tests in 86.071s
```
so one has to think that the tests are (improperly) looking outside of the sources into the local test environment

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 

tagged github CO of 0.9.7 current vial the method shown above

- [ NA ] Fail2Ban installed via OS/distribution mechanisms -- I am simply building a prior tag
- [ no  ] You have not applied any additional foreign patches to the codebase

three patches, but not related to test coverage:
fail2ban-iptables.patch
fail2ban-log2syslog.patch
fail2ban-paths.patch

they are as follows
```
[herrold@centos-7 fail2ban]$ cat fail2ban-iptables.patch
diff -up fail2ban-0.9.3/config/action.d/iptables-common.conf.iptables fail2ban-0.9.3/config/action.d/iptables-common.conf
--- fail2ban-0.9.3/config/action.d/iptables-common.conf.iptables        2015-07-31 19:32:13.000000000 -0600
+++ fail2ban-0.9.3/config/action.d/iptables-common.conf 2015-10-17 09:23:32.352008971 -0600
@@ -56,7 +56,7 @@ returntype = RETURN
 #          in iptables 1.4.20, so might be absent on older systems
 #          See https://github.com/fail2ban/fail2ban/issues/1122
 # Values:  STRING
-lockingopt = -w
+lockingopt =

 # Option:  iptables
 # Notes.:  Actual command to be executed, including common to all calls options
[herrold@centos-7 fail2ban]$ 
```
=================
```
herrold@centos-7 fail2ban]$ cat fail2ban-log2syslog.patch
diff -up fail2ban-0.9.4/config/fail2ban.conf.log2syslog fail2ban-0.9.4/config/fail2ban.conf
--- fail2ban-0.9.4/config/fail2ban.conf.log2syslog      2016-03-07 19:50:10.000000000 -0700
+++ fail2ban-0.9.4/config/fail2ban.conf 2016-03-09 12:06:22.739574596 -0700
@@ -32,7 +32,7 @@ loglevel = INFO
 #         (e.g. /etc/logrotate.d/fail2ban on Debian systems)
 # Values: [ STDOUT | STDERR | SYSLOG | FILE ]  Default: STDERR
 #
-logtarget = /var/log/fail2ban.log
+logtarget = SYSLOG

 # Option: syslogsocket
 # Notes: Set the syslog socket file. Only used when logtarget is SYSLOG
diff -up fail2ban-0.9.4/config/jail.conf.log2syslog fail2ban-0.9.4/config/jail.conf
--- fail2ban-0.9.4/config/jail.conf.log2syslog  2016-03-09 12:06:22.741574585 -0700
+++ fail2ban-0.9.4/config/jail.conf     2016-03-09 12:07:40.555163704 -0700
@@ -739,7 +739,7 @@ backend  = %(mysql_backend)s
 #    to maintain entries for failed logins for sufficient amount of time
 [recidive]
 
-logpath  = /var/log/fail2ban.log
+logpath  = /var/log/messages
 banaction = %(banaction_allports)s
 bantime  = 604800  ; 1 week
 findtime = 86400   ; 1 day
diff -up fail2ban-0.9.4/fail2ban/tests/clientreadertestcase.py.log2syslog fail2ban-0.9.4/fail2ban/tests/clientreadertestcase.py
--- fail2ban-0.9.4/fail2ban/tests/clientreadertestcase.py.log2syslog    2016-03-09 12:06:22.737574607 -0700
+++ fail2ban-0.9.4/fail2ban/tests/clientreadertestcase.py       2016-03-09 12:06:22.743574574 -0700
@@ -704,7 +704,7 @@ class JailsReaderTest(LogCaptureTestCase
                                                                '/var/lib/fail2ban/fail2ban.sqlite3'],
                                                          ['set', 'dbpurgeage', 86400],
                                                          ['set', 'loglevel', "INFO"],
-                                                         ['set', 'logtarget', '/var/log/fail2ban.log'],
+                                                         ['set', 'logtarget', 'SYSLOG'],
                                                          ['set', 'syslogsocket', 'auto']])
 
                        # and if we force change configurator's fail2ban's baseDir
[herrold@centos-7 fail2ban]$ 
```
===============
```
[herrold@centos-7 fail2ban]$ cat fail2ban-paths.patch
diff -up fail2ban-0.9.6/config/paths-fedora.conf.paths fail2ban-0.9.6/config/paths-fedora.conf
--- fail2ban-0.9.6/config/paths-fedora.conf.paths       2017-02-17 11:11:43.909657115 -0700
+++ fail2ban-0.9.6/config/paths-fedora.conf     2017-02-17 11:12:40.115646223 -0700
@@ -34,18 +34,7 @@ apache_access_log = /var/log/httpd/*acce
 
 exim_main_log = /var/log/exim/main.log
 
-mysql_log = /var/log/mariadb/mariadb.log
+mysql_log = /var/log/mysqld.log
             /var/log/mysqld.log
 
 roundcube_errors_log = /var/log/roundcubemail/errors
-
-# These services will log to the journal via syslog, so use the journal by
-# default.
-syslog_backend = systemd
-sshd_backend = systemd
-dropbear_backend = systemd
-proftpd_backend = systemd
-pureftpd_backend = systemd
-wuftpd_backend = systemd
-postfix_backend = systemd
-dovecot_backend = systemd
[herrold@centos-7 fail2ban]$ 

```
- [  as above ] Some customizations were done to the configuration (provide details below is so)

but none should have impacted test coverage code

### The issue:

_Summary here_

FAIL: testCymruInfoNxdomain (fail2ban.tests.banmanagertestcase.StatusExtendedCymruInfo)

#### Steps to reproduce

simple RPM SRPM rebuild 

#### Expected behavior

no errors

#### Observed behavior

test fails per above

#### Any additional information

there is another issue in that tag (0.9.7) which adds a non-compliant FHS logging path which breaks a 'hands off startup -- it should probably be disabled of commented out

That vendor specific path, sitting in home !! is just wrong ;)  IBM needs to 'clean up its act, register with LANANA, and get a /opt/ibm  or use: /var/log/ibm  which is designed for such
```
# [domino-smtp]
# port    = smtp,ssmtp
# filter  = domino-smtp 
# logpath = /home/domino01/data/IBM_TECHNICAL_SUPPORT/console.log

[root@router fail2ban]# service fail2ban restart
Stopping fail2ban:                                         [  OK  ]
Starting fail2ban: ERROR  No file(s) found for glob /home/domino01/data/IBM_TECHNICAL_SUPPORT/console.log
ERROR  Failed during configuration: Have not found any log file for domino-smtp jail
                                                           [FAILED]
[root@router fail2ban]# j
```
I will file this separately

#### Any customizations done to /etc/fail2ban/ configuration

not relevant -- build time issue

#### Relevant parts of /var/log/fail2ban.log file:

not relevant - -build time test issue

#### Relevant lines from monitored log files in question:

not relevant -- build time issue

**Comment by sebres** [comment]
Cymru info of 10.0.0.0 is changed. Already fixed in 9f55ed86df19d990890c0103f038a147cb7145b9.

Please note that test-cases suite runs only on the clean copy (without config adjustment, .local files, etc.).
