### ISSUE TITLE
fail2ban 0.9.4 stops after couple hours.

### ISSUE THREAD

**Issue by knagpateaculos** [fail2ban/fail2ban#1878]
- Fail2Ban version (including any possible distribution suffixes):

**Fail2Ban v0.9.4**

- OS, including release name/version: 

**cat /etc/debian_version
8.9**

- [ ] Fail2Ban installed via OS/distribution mechanisms

Manual install

- [ ] You have not applied any additional foreign patches to the codebase
none
- [ ] Some customizations were done to the configuration (provide details below is so)
none
### The issue:

After a couple of hours of expected behavior, fail2ban crashes and stops with this message. After that, doing 'service fail2ban restart' revives fail2ban but it's gonna show the same message after 4 - 5 hours

### Configuration, dump and another helpful excerpts
```
fail2ban-client -d
['set', 'syslogsocket', 'auto']
['set', 'loglevel', 'INFO']
['set', 'logtarget', '/var/log/fail2ban.log']
['set', 'dbfile', '/var/lib/fail2ban/fail2ban.sqlite3']
['set', 'dbpurgeage', 86400]
['add', 'sshd', 'auto']
['set', 'sshd', 'usedns', 'warn']
['set', 'sshd', 'addlogpath', '/var/log/auth.log', 'head']
['set', 'sshd', 'maxretry', 3]
['set', 'sshd', 'addignoreip', '127.0.0.1/8']
['set', 'sshd', 'logencoding', 'auto']
['set', 'sshd', 'bantime', 604800]
['set', 'sshd', 'ignorecommand', '']
['set', 'sshd', 'findtime', 600]
['set', 'sshd', 'maxlines', '10']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*(?:error: PAM: )?[aA]uthentication (?:failure|error) for .* from <HOST>( via \\S+)?\\s*$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*(?:error: PAM: )?User not known to the underlying authentication module for .* from <HOST>\\s*$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*Failed \\S+ for .*? from <HOST>(?: port \\d*)?(?: ssh\\d*)?(: (ruser .*|(\\S+ ID \\S+ \\(serial \\d+\\) CA )?\\S+ (?:[\\da-f]{2}:){15}[\\da-f]{2}(, client user ".*", client host ".*")?))?\\s*$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*ROOT LOGIN REFUSED.* FROM <HOST>\\s*$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*[iI](?:llegal|nvalid) user .* from <HOST>\\s*$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*User .+ from <HOST> not allowed because not listed in AllowUsers\\s*$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*User .+ from <HOST> not allowed because listed in DenyUsers\\s*$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*User .+ from <HOST> not allowed because not in any group\\s*$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*refused connect from \\S+ \\(<HOST>\\)\\s*$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*(?:error: )?Received disconnect from <HOST>: 3: .*: Auth fail(?: \\[preauth\\])?$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*User .+ from <HOST> not allowed because a group is listed in DenyGroups\\s*$']
['set', 'sshd', 'addfailregex', "^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*User .+ from <HOST> not allowed because none of user's groups are listed in AllowGroups\\s*$"]
['set', 'sshd', 'addfailregex', '^(?P<__prefix>\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*)User .+ not allowed because account is locked<SKIPLINES>(?P=__prefix)(?:error: )?Received disconnect from <HOST>: 11: .+ \\[preauth\\]$']
['set', 'sshd', 'addfailregex', '^(?P<__prefix>\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*)Disconnecting: Too many authentication failures for .+? \\[preauth\\]<SKIPLINES>(?P=__prefix)(?:error: )?Connection closed by <HOST> \\[preauth\\]$']
['set', 'sshd', 'addfailregex', '^(?P<__prefix>\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*)Connection from <HOST> port \\d+(?: on \\S+ port \\d+)?<SKIPLINES>(?P=__prefix)Disconnecting: Too many authentication failures for .+? \\[preauth\\]$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*(error: )?maximum authentication attempts exceeded for .* from <HOST>(?: port \\d*)?(?: ssh\\d*)? \\[preauth\\]$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*pam_unix\\(sshd:auth\\):\\s+authentication failure;\\s*logname=\\S*\\s*uid=\\d*\\s*euid=\\d*\\s*tty=\\S*\\s*ruser=\\S*\\s*rhost=<HOST>\\s.*$']
['set', 'sshd', 'addjournalmatch', '_SYSTEMD_UNIT=sshd.service', '+', '_COMM=sshd']
['set', 'sshd', 'addaction', 'iptables-multiport']
['set', 'sshd', 'action', 'iptables-multiport', 'actionban', '<iptables> -I f2b-<name> 1 -s <ip> -j <blocktype>']
['set', 'sshd', 'action', 'iptables-multiport', 'actionstop', '<iptables> -D <chain> -p <protocol> -m multiport --dports <port> -j f2b-<name>\n<iptables> -F f2b-<name>\n<iptables> -X f2b-<name>']
['set', 'sshd', 'action', 'iptables-multiport', 'actionstart', '<iptables> -N f2b-<name>\n<iptables> -A f2b-<name> -j <returntype>\n<iptables> -I <chain> -p <protocol> -m multiport --dports <port> -j f2b-<name>']
['set', 'sshd', 'action', 'iptables-multiport', 'actionunban', '<iptables> -D f2b-<name> -s <ip> -j <blocktype>']
['set', 'sshd', 'action', 'iptables-multiport', 'actioncheck', "<iptables> -n -L <chain> | grep -q 'f2b-<name>[ \\t]'"]
['set', 'sshd', 'action', 'iptables-multiport', 'protocol', 'tcp']
['set', 'sshd', 'action', 'iptables-multiport', 'chain', 'INPUT']
['set', 'sshd', 'action', 'iptables-multiport', 'lockingopt', '-w']
['set', 'sshd', 'action', 'iptables-multiport', 'known/known/name', 'default']
['set', 'sshd', 'action', 'iptables-multiport', 'blocktype', 'REJECT --reject-with icmp-port-unreachable']
['set', 'sshd', 'action', 'iptables-multiport', 'known/lockingopt', '-w']
['set', 'sshd', 'action', 'iptables-multiport', 'known/known/port', 'ssh']
['set', 'sshd', 'action', 'iptables-multiport', 'known/protocol', 'tcp']
['set', 'sshd', 'action', 'iptables-multiport', 'known/known/lockingopt', '-w']
['set', 'sshd', 'action', 'iptables-multiport', 'port', 'ssh']
['set', 'sshd', 'action', 'iptables-multiport', 'known/known/chain', 'INPUT']
['set', 'sshd', 'action', 'iptables-multiport', 'known/name', 'default']
['set', 'sshd', 'action', 'iptables-multiport', 'known/known/protocol', 'tcp']
['set', 'sshd', 'action', 'iptables-multiport', 'bantime', '604800']
['set', 'sshd', 'action', 'iptables-multiport', 'iptables', 'iptables <lockingopt>']
['set', 'sshd', 'action', 'iptables-multiport', 'known/__name__', 'Init']
['set', 'sshd', 'action', 'iptables-multiport', 'returntype', 'RETURN']
['set', 'sshd', 'action', 'iptables-multiport', 'known/returntype', 'RETURN']
['set', 'sshd', 'action', 'iptables-multiport', 'known/known/__name__', 'Init']
['set', 'sshd', 'action', 'iptables-multiport', 'known/known/returntype', 'RETURN']
['set', 'sshd', 'action', 'iptables-multiport', 'name', 'sshd']
['set', 'sshd', 'action', 'iptables-multiport', 'known/known/blocktype', 'REJECT --reject-with icmp-port-unreachable']
['set', 'sshd', 'action', 'iptables-multiport', 'known/port', 'ssh']
['set', 'sshd', 'action', 'iptables-multiport', 'known/iptables', 'iptables <lockingopt>']
['set', 'sshd', 'action', 'iptables-multiport', 'known/chain', 'INPUT']
['set', 'sshd', 'action', 'iptables-multiport', 'known/blocktype', 'REJECT --reject-with icmp-port-unreachable']
['set', 'sshd', 'action', 'iptables-multiport', 'known/known/iptables', 'iptables <lockingopt>']
['start', 'sshd']
```
#### Any customizations done to /etc/fail2ban/ configuration
none
#### Relevant parts of /var/log/fail2ban.log file:

```
CRITICAL Unhandled exception in Fail2Ban:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fail2ban-0.9.4-py2.7.egg/fail2ban/server/jailthread.py", line 66, in run_with_except_hook
    run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fail2ban-0.9.4-py2.7.egg/fail2ban/server/filterpoll.py", line 97, in run
    self.getFailures(filename)
  File "/usr/local/lib/python2.7/dist-packages/fail2ban-0.9.4-py2.7.egg/fail2ban/server/filter.py", line 690, in getFailures
    db.updateLog(self.jail, log)
  File "/usr/local/lib/python2.7/dist-packages/fail2ban-0.9.4-py2.7.egg/fail2ban/server/database.py", line 96, in wrapper
    return f(self, self._db.cursor(), *args, **kwargs)
OperationalError: disk I/O error
```
**`#service iptables restart`**
```
2017-08-28 10:14:48,816 fail2ban.server         [1518]: INFO    Stopping all jails
2017-08-28 10:14:53,268 fail2ban.action         [1518]: ERROR   iptables -w -D INPUT -p tcp -m multiport --dports ssh -j f2b-sshd
iptables -w -F f2b-sshd
iptables -w -X f2b-sshd -- stdout: ''
2017-08-28 10:14:53,268 fail2ban.action         [1518]: ERROR   iptables -w -D INPUT -p tcp -m multiport --dports ssh -j f2b-sshd
iptables -w -F f2b-sshd
iptables -w -X f2b-sshd -- stderr: 'iptables: Too many links.\n'
2017-08-28 10:14:53,299 fail2ban.action         [1518]: ERROR   iptables -w -D INPUT -p tcp -m multiport --dports ssh -j f2b-sshd
iptables -w -F f2b-sshd
iptables -w -X f2b-sshd -- returned 1
2017-08-28 10:14:53,300 fail2ban.actions        [1518]: ERROR   Failed to stop jail 'sshd' action 'iptables-multiport': Error stopping action
2017-08-28 10:14:53,300 fail2ban.jail           [1518]: INFO    Jail 'sshd' stopped
2017-08-28 10:14:53,304 fail2ban.server         [1518]: INFO    Exiting Fail2ban
2017-08-28 10:14:54,461 fail2ban.server         [6761]: INFO    Changed logging target to /var/log/fail2ban.log for Fail2ban v0.9.4
2017-08-28 10:14:54,462 fail2ban.database       [6761]: INFO    Connected to fail2ban persistent database '/var/lib/fail2ban/fail2ban.sqlite3'
2017-08-28 10:14:54,474 fail2ban.jail           [6761]: INFO    Creating new jail 'sshd'
2017-08-28 10:14:54,476 fail2ban.jail           [6761]: INFO    Jail 'sshd' uses poller
2017-08-28 10:14:54,492 fail2ban.filter         [6761]: INFO    Set jail log file encoding to ANSI_X3.4-1968
2017-08-28 10:14:54,493 fail2ban.jail           [6761]: INFO    Initiated 'polling' backend
2017-08-28 10:14:54,498 fail2ban.filter         [6761]: INFO    Added logfile = /var/log/auth.log
2017-08-28 10:14:54,498 fail2ban.filter         [6761]: INFO    Set maxRetry = 3
2017-08-28 10:14:54,499 fail2ban.filter         [6761]: INFO    Set jail log file encoding to ANSI_X3.4-1968
2017-08-28 10:14:54,499 fail2ban.actions        [6761]: INFO    Set banTime = 604800
2017-08-28 10:14:54,500 fail2ban.filter         [6761]: INFO    Set findtime = 600
2017-08-28 10:14:54,500 fail2ban.filter         [6761]: INFO    Set maxlines = 10
2017-08-28 10:14:54,568 fail2ban.server         [6761]: INFO    Jail sshd is not a JournalFilter instance
2017-08-28 10:14:54,613 fail2ban.jail           [6761]: INFO    Jail 'sshd' started
```

**Comment by sebres** [comment]
> OperationalError: disk I/O error

There could be a lot of reasons. Real hardware problem (e. g. HDD-issues), some security rules preventing disk access, etc. 

If you believe all this is all right, you can try to delete `/var/lib/fail2ban/fail2ban.sqlite3` (and restart fail2ban hereafter).

> iptables: Too many links.

This going to not proper stopping of fail2ban (where some jails are in unexpected state now).
- stop fail2ban;
- clean up iptables: delete all iptables-entries starting with `f2b-`;
- start fail2ban;

**Comment by knagpateaculos** [comment]
(sorry for the delay on the response, I was waiting to see if it fails again)

After almost 3 days of normal behaviour, today started to gave me this message everytime it tries to ban some IP:

`2017-08-31 10:54:45,472 fail2ban.action         [883]: ERROR   iptables -w -I f2b-sshd 1 -s 180.250.39.54 -j REJECT --reject-with icmp-port-unreachable -- stdout: ''
2017-08-31 10:54:45,473 fail2ban.action         [883]: ERROR   iptables -w -I f2b-sshd 1 -s 180.250.39.54 -j REJECT --reject-with icmp-port-unreachable -- stderr: 'iptables: Memory allocation problem.\n'
2017-08-31 10:54:45,481 fail2ban.action         [883]: ERROR   iptables -w -I f2b-sshd 1 -s 180.250.39.54 -j REJECT --reject-with icmp-port-unreachable -- returned 1
2017-08-31 10:54:45,481 fail2ban.actions        [883]: ERROR   Failed to execute ban jail 'sshd' action 'iptables-multiport' info 'CallingMap({'ipjailmatches': <function <lambda> at 0x7f1fb53ec320>, 'matches': u'Aug 31 10:54:41 euve255689 sshd[10310]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=180.250.39.54  user=root\nAug 31 10:54:42 euve255689 sshd[10310]: Failed password for root from 180.250.39.54 port 59145 ssh2\nAug 31 10:54:44 euve255689 sshd[10310]: Failed password for root from 180.250.39.54 port 59145 ssh2', 'ip': '180.250.39.54', 'ipmatches': <function <lambda> at 0x7f1fb53ec410>, 'ipfailures': <function <lambda> at 0x7f1fb438df50>, 'time': 1504169685.263512, 'failures': 3, 'ipjailfailures': <function <lambda> at 0x7f1fb43a3f50>})': Error banning 180.250.39.54`

Now fail2ban sees the IP but I don't think is blocking anything

2017-08-31 10:54:47,242 fail2ban.filter         [883]: INFO    [sshd] Found 180.250.39.54

**Comment by knagpateaculos** [comment]
The 'Memory allocation problem' is the reason I've upgraded the fail2ban from the version that cames with the debian apt-get package. Now if I try to manually block some ip, the message it's the same:

~# iptables -A INPUT -s 180.250.39.54 -j DROP
iptables: Memory allocation problem.

**Comment by sebres** [comment]
> iptables: Memory allocation problem.

It seems that you've a limit (from provider?)... 
Virtually no new entry can be added after some iptables entries...

If you've a VPS you can try to find out your resources limit for example from user_beancounters...
```bash
egrep "failcnt|numiptent" /proc/user_beancounters
```

**Comment by knagpateaculos** [comment]
`n# egrep "failcnt|numiptent" /proc/user_beancounters
       uid  resource                     held              maxheld              barrier                limit              failcnt
            numiptent                     128                  128                  128                  128                   72`

It is an VPS indeed! Can't recall anythin like this in my short experience with vps, what should be the optimal limit?

**Comment by knagpateaculos** [comment]
n# egrep "failcnt|numiptent" /proc/user_beancounters
       uid  resource                     held              maxheld              barrier                limit              failcnt
            numiptent                     128                  128                  128                  128                   72

**Comment by sebres** [comment]
> what should be the optimal limit?

Hmm?? So large as you need... But you cannot change it... Mostly provider only.

**Comment by knagpateaculos** [comment]
Humm that's odd, package version of fail2ban manages to block up to 293 ips. I had the badip line added for that version when I was using it (I think I upgraded for the persistens bans after restart the server):

https://www.badips.com/stats?key=44ebb4c5d9ac7d2671e7c3d3f59f1498403864e4
