### ISSUE TITLE
skip a testRepairDb if no sqlite3 cmdline helper available

### ISSUE THREAD

**Issue by yarikoptic** [fail2ban/fail2ban#2026]
```
fail2ban/server/database.py:                      Utils.executeCmd((r"""f2b_db=$0; f2b_dbbk=$1; sqlite3 "$f2b_dbbk" ".dump" | sqlite3 "$f2b_db" """,
```

and if no sqlite3 cmdline then
```
======================================================================
ERROR: testRepairDb (fail2ban.tests.databasetestcase.DatabaseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/fail2ban-0.10.2/.pybuild/pythonX.Y_3.6/build/fail2ban/server/database.py", line 205, in _connectDB
    cur.execute("PRAGMA synchronous = OFF")
sqlite3.DatabaseError: database disk image is malformed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/fail2ban-0.10.2/.pybuild/pythonX.Y_3.6/build/fail2ban/server/database.py", line 283, in repairDB
    dbFileSize = os.stat(self._dbFilename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/fail2ban_dqstc0hl.db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/fail2ban-0.10.2/.pybuild/pythonX.Y_3.6/build/fail2ban/tests/databasetestcase.py", line 139, in testRepairDb
    self.db = Fail2BanDb(self.dbFilename)
  File "/build/fail2ban-0.10.2/.pybuild/pythonX.Y_3.6/build/fail2ban/server/database.py", line 174, in __init__
    self._connectDB()
  File "/build/fail2ban-0.10.2/.pybuild/pythonX.Y_3.6/build/fail2ban/server/database.py", line 226, in _connectDB
    self.repairDB()
  File "/build/fail2ban-0.10.2/.pybuild/pythonX.Y_3.6/build/fail2ban/server/database.py", line 296, in repairDB
    os.remove(self._dbFilename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/fail2ban_dqstc0hl.db'

======================================================================
ERROR: testRepairDb (fail2ban.tests.databasetestcase.DatabaseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/fail2ban-0.10.2/.pybuild/pythonX.Y_3.6/build/fail2ban/tests/databasetestcase.py", line 85, in tearDown
    os.remove(self.dbFilename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/fail2ban_dqstc0hl.db'

----------------------------------------------------------------------
```

**Comment by sebres** [comment]
So CI build passed - I merge 8cfd97a.
