### ISSUE TITLE
Fails to ban IP address

### ISSUE THREAD

**Issue by angaunba** [fail2ban/fail2ban#2085]
### Environment:

- 0.10.2
- Debian 9.4
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Fail2ban fails to ban any unsuccessful login attempt via ssh. I can add manually IP to ban list but they are still trying from the same address.

#### Expected behaviour

Ban each unsuccessful login attempt.

#### Observed behaviour

No one is banned, even though the attackers IP are trying to log in many times, they are not banned on unsuccessful attempt.

### Configuration, dump and another helpful excerpts
```
['add', 'sshd', 'auto']
['set', 'sshd', 'maxlines', 1]
['set', 'sshd', 'prefregex', '^<F-MLFID>(?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel: \\[ *\\d+\\.\\d+\\]\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?</F-MLFID>(?:(?:error|fatal): (?:PAM: )?)?<F-CONTENT>.+</F-CONTENT>$']
['set', 'sshd', 'datepattern', '{^LN-BEG}']
['multi-set', 'sshd', 'addfailregex', ['^[aA]uthentication (?:failure|error|failed) for <F-USER>.*</F-USER> from <HOST>( via \\S+)?\\s*(?: \\[preauth\\])?\\s*$', '^User not known to the underlying authentication module for <F-USER>.*</F-USER> from <HOST>\\s*(?: \\[preauth\\])?\\s*$', '^Failed \\S+ for invalid user <F-USER>(?P<cond_user>\\S+)|(?:(?! from ).)*?</F-USER> from <HOST>(?: port \\d+)?(?: on \\S+(?: port \\d+)?)?(?: ssh\\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)', '^Failed \\b(?!publickey)\\S+ for (?P<cond_inv>invalid user )?<F-USER>(?P<cond_user>\\S+)|(?(cond_inv)(?:(?! from ).)*?|[^:]+)</F-USER> from <HOST>(?: port \\d+)?(?: on \\S+(?: port \\d+)?)?(?: ssh\\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)', '^<F-USER>ROOT</F-USER> LOGIN REFUSED.* FROM <HOST>\\s*(?: \\[preauth\\])?\\s*$', '^[iI](?:llegal|nvalid) user <F-USER>.*?</F-USER> from <HOST>(?: port \\d+)?(?: on \\S+(?: port \\d+)?)?\\s*$', '^User <F-USER>.+</F-USER> from <HOST> not allowed because not listed in AllowUsers\\s*(?: \\[preauth\\])?\\s*$', '^User <F-USER>.+</F-USER> from <HOST> not allowed because listed in DenyUsers\\s*(?: \\[preauth\\])?\\s*$', '^User <F-USER>.+</F-USER> from <HOST> not allowed because not in any group\\s*(?: \\[preauth\\])?\\s*$', '^refused connect from \\S+ \\(<HOST>\\)\\s*(?: \\[preauth\\])?\\s*$', '^Received <F-MLFFORGET>disconnect</F-MLFFORGET> from <HOST>(?: port \\d+)?(?: on \\S+(?: port \\d+)?)?:\\s*3: .*: Auth fail(?: \\[preauth\\])?\\s*$', '^User <F-USER>.+</F-USER> from <HOST> not allowed because a group is listed in DenyGroups\\s*(?: \\[preauth\\])?\\s*$', "^User <F-USER>.+</F-USER> from <HOST> not allowed because none of user's groups are listed in AllowGroups\\s*(?: \\[preauth\\])?\\s*$", '^pam_unix\\(sshd:auth\\):\\s+authentication failure;\\s*logname=\\S*\\s*uid=\\d*\\s*euid=\\d*\\s*tty=\\S*\\s*ruser=<F-USER>\\S*</F-USER>\\s*rhost=<HOST>\\s.*(?: \\[preauth\\])?\\s*$', '^(error: )?maximum authentication attempts exceeded for <F-USER>.*</F-USER> from <HOST>(?: port \\d+)?(?: on \\S+(?: port \\d+)?)?(?: ssh\\d*)?(?: \\[preauth\\])?\\s*$', '^User <F-USER>.+</F-USER> not allowed because account is locked(?: \\[preauth\\])?\\s*', '^<F-MLFFORGET>Disconnecting</F-MLFFORGET>: Too many authentication failures(?: for <F-USER>.+?</F-USER>)?(?: \\[preauth\\])?\\s*', '^<F-NOFAIL>Received <F-MLFFORGET>disconnect</F-MLFFORGET></F-NOFAIL> from <HOST>: 11:', '^<F-NOFAIL>Connection <F-MLFFORGET>closed</F-MLFFORGET></F-NOFAIL> by <HOST>(?: \\[preauth\\])?\\s*$', '^<F-MLFFORGET><F-NOFAIL>Accepted publickey</F-NOFAIL></F-MLFFORGET> for \\S+ from <HOST>(?:\\s|$)', '^<F-NOFAIL>Connection from</F-NOFAIL> <HOST>']]
['set', 'sshd', 'addjournalmatch', '_SYSTEMD_UNIT=sshd.service', '+', '_COMM=sshd']
['set', 'sshd', 'usedns', 'warn']
['set', 'sshd', 'addlogpath', '/var/log/auth.log', 'head']
['set', 'sshd', 'maxretry', 1]
['set', 'sshd', 'logencoding', 'auto']
['set', 'sshd', 'bantime', '86400']
['set', 'sshd', 'ignorecommand', '']
['set', 'sshd', 'findtime', '3600']
['set', 'sshd', 'addaction', 'iptables-multiport']
['multi-set', 'sshd', 'action', 'iptables-multiport', [['actionunban', '<iptables> -D f2b-sshd -s <ip> -j <blocktype>'], ['actionflush', '<iptables> -F f2b-sshd'], ['actionstop', '<iptables> -D INPUT -p tcp -m multiport --dports ssh -j f2b-sshd\n<iptables> -F f2b-sshd\n<iptables> -X f2b-sshd'], ['actionstart', '<iptables> -N f2b-sshd\n<iptables> -A f2b-sshd -j RETURN\n<iptables> -I INPUT -p tcp -m multiport --dports ssh -j f2b-sshd'], ['actionban', '<iptables> -I f2b-sshd 1 -s <ip> -j <blocktype>'], ['actioncheck', "<iptables> -n -L INPUT | grep -q 'f2b-sshd[ \\t]'"], ['protocol', 'tcp'], ['chain', '<known/chain>'], ['lockingopt', '-w'], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['port', 'ssh'], ['actname', 'iptables-multiport'], ['bantime', '86400'], ['iptables', 'iptables <lockingopt>'], ['returntype', 'RETURN'], ['iptables?family=inet6', 'ip6tables <lockingopt>'], ['name', 'sshd']]]
['start', 'sshd']
```

#### Any customizations done to /etc/fail2ban/ configuration
```
enabled = true                                                                                                                
backend = polling                                                                                                             
mode   = extra                                                                                                                
port    = ssh                                                                                                                 
filter   = sshd                                                                                                               
logpath = %(sshd_log)s                                                                                                        
backend = %(sshd_backend)s                                                                                                    
maxretry = 1                                                                                                                  
bantime = 86400                                                                                                               
findtime = 3600
```

#### Relevant parts of /var/log/fail2ban.log file:
```
2018-03-17 14:56:24,999 fail2ban.actions        [9741]: NOTICE  [sshd] Unban 185.156.177.11                                 
    8 2018-03-17 14:56:24,999 fail2ban.actions        [9741]: DEBUG   [sshd] action 'iptables-multiport': unban 185.156.177.11    
    7 2018-03-17 14:56:24,999 fail2ban.action         [9741]: DEBUG   iptables -w -n -L INPUT | grep -q 'f2b-sshd[ \t]'           
    6 2018-03-17 14:56:25,003 fail2ban.utils          [9741]: DEBUG   7f650220a608 -- returned successfully 0                     
    5 2018-03-17 14:56:25,003 fail2ban.action         [9741]: DEBUG   iptables -w -D f2b-sshd -s 185.156.177.11 -j REJECT --            reject-with icmp-port-unreachable                                                                                           
    4 2018-03-17 14:56:25,006 fail2ban.utils          [9741]: DEBUG   7f6502757eb0 -- returned successfully 0                     
    3 2018-03-17 14:56:25,006 fail2ban.actions        [9741]: DEBUG   Unbanned 1, 2 ticket(s) in 'sshd'                           
    2 2018-03-17 14:56:43,031 fail2ban.actions        [9741]: NOTICE  [sshd] Unban 80.211.179.170                                 
    1 2018-03-17 14:56:43,031 fail2ban.actions        [9741]: DEBUG   [sshd] action 'iptables-multiport': unban 80.211.179.170    
20514 2018-03-17 14:56:43,031 fail2ban.action         [9741]: DEBUG   iptables -w -n -L INPUT | grep -q 'f2b-sshd[ \t]'           
    1 2018-03-17 14:56:43,037 fail2ban.utils          [9741]: DEBUG   7f650220a608 -- returned successfully 0                     
    2 2018-03-17 14:56:43,038 fail2ban.action         [9741]: DEBUG   iptables -w -D f2b-sshd -s 80.211.179.170 -j REJECT --            reject-with icmp-port-unreachable                                                                                           
    3 2018-03-17 14:56:43,043 fail2ban.utils          [9741]: DEBUG   7f6502757eb0 -- returned successfully 0                     
    4 2018-03-17 14:56:43,043 fail2ban.actions        [9741]: DEBUG   Unbanned 1, 1 ticket(s) in 'sshd' 

2018-03-18 06:25:04,117 fail2ban.filter         [9741]: MSG     Log rotation detected for /var/log/auth.log

2018-03-19 00:30:28,129 fail2ban.transmitter    [9741]: WARNING Command ['status', 'sshd\x01'] has failed. Received UnknownJailException('sshd\x01',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fail2ban/server/transmitter.py", line 57, in proceed
    ret = self.__commandHandler(command)
  File "/usr/local/lib/python2.7/dist-packages/fail2ban/server/transmitter.py", line 131, in __commandHandler
    return self.status(command[1:])
  File "/usr/local/lib/python2.7/dist-packages/fail2ban/server/transmitter.py", line 406, in status
    return self.__server.statusJail(name)
  File "/usr/local/lib/python2.7/dist-packages/fail2ban/server/server.py", line 514, in statusJail
    return self.__jails[name].status(flavor=flavor)
  File "/usr/local/lib/python2.7/dist-packages/fail2ban/server/jails.py", line 80, in __getitem__
    raise UnknownJailException(name)
UnknownJailException: 'sshd\x01'
   
```

#### Relevant lines from monitored log files in question:
```
Mar 17 15:31:57 n01 sshd[10979]: rexec line 34: Deprecated option RSAAuthentication                                           
  1 Mar 17 15:31:57 n01 sshd[10979]: Connection from 80.211.179.170 port 60708 on IP port PORT                       
  2 Mar 17 15:31:57 n01 sshd[10979]: Connection closed by 80.211.179.170 port 60708 [preauth]
```

**Comment by sebres** [comment]
I don't see any error there, except one with UnknownJailException...
This error occured if `fail2ban-client status jail-which-not-exists` will be executed...
So just interesting how you could append a char `\x01` via command line to produce this one - `UnknownJailException: 'sshd\x01'`?

Back to the issue:

The IP 80.211.179.170 was even banned at least once, and unbanned 2018-03-17 14:56:43. 
Here is it:
```
2018-03-17 14:56:43,031 fail2ban.actions        [9741]: NOTICE  [sshd] Unban 80.211.179.170  
```
Regarding "Relevant lines from monitored log files in question": this lines are not directly an authentication error.
For example If you'll try following for exactly this 3 lines:
```
fail2ban-regex /var/log/auth.log sshd
```
you'll get:
```
...
|  29) [1] ^<F-NOFAIL>Connection from</F-NOFAIL> <HOST>
...
Lines: 3 lines, 0 ignored, 1 matched, 2 missed
```
So admittedly you'll see `^<F-NOFAIL>Connection from</F-NOFAIL> <HOST>` catches an entry.
But `F-NOFAIL` means here - it's not a failure (it expects still another match without `F-NOFAIL`), so it is just a helper to match multi-line failures - lines (from the same connect) without the IP in the log-line, like `Disconnecting: Too many authentication failures for user [preauth]`.

Nevertheless, you could try to use mode `aggressive` for the sshd, to ban not directly the intruder IPs even more aggressive (also without direct authentication errors), resp. try it with fail2ban-regex to see the differences:
```
fail2ban-regex -v /var/log/auth.log sshd[mode=aggressive]
```

Also note [[wiki] How fail2ban works](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works)

**Comment by angaunba** [comment]
Hi, 

It was banned because I added it manually using:
```
fail2ban-client set sshd banip 80.211.179.170 
```
But it does not do it automatically. I will read the wiki again. :)

Thanks for help!
Cheers.

**Comment by sebres** [comment]
Which failures did you noticed from this IP?
I mean:
```
grep 80.211.179.170 /var/log/auth.log
```
Are only messages, mentioned in the issue above?

**Comment by angaunba** [comment]
Yes, only those messages with 1 hour between login attempts with this and many other IP addresses also few of them tried different port combinations every 5 seconds for 10 minutes.

**Comment by sebres** [comment]
> with 1 hour between login attempts 

I don't saw any login attempt there (`Connection closed by ... port ... [preauth]` is not really an attempt).

> and many other IP addresses 

with the same? I mean - only `connection closed ... [preauth]`, nothing else?

> few of them tried different port combinations every 5 seconds for 10 minutes.

This looks like port-scanner, searcher for some service (for which the ssh-protocol is probably not suitable), so just closed after timeout.

**Comment by angaunba** [comment]
Ok, my mistake!
Have a nice day! :)
