### ISSUE TITLE
After receiving  error, does not work and does not block IP

### ISSUE THREAD

**Issue by jefomin** [fail2ban/fail2ban#2137]
- Fail2Ban version (including any possible distribution suffixes): v0.11.0.dev2
- OS, including release name/version: CloudLinux Server release 6.9
- [*] Fail2Ban installed via OS/distribution mechanisms
- [* ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

After receiving the error, it does not work and does not block IP, requires kill -9 f2ban and start f2ban.

```
2018-05-21 15:21:29,107 fail2ban.filter [895579]: WARNING Error decoding line from '/var/log/maillog' with 'UTF-8'. Consider setting logencoding=utf-8 (or another appropriate encoding) for this jail. Continuing to process line ignoring invalid characters: 'May 21 15:21:29 HOSTNAME exim[1038999]: 2018-05-21 15:21:29 dovecot_plain authenticator failed for 95-27-160-131.broadband.corbina.ru (\xf2\xf0\xe5\xf2\xe8\xe9) [95.27.160.131]:64885: 535 Incorrect authentication data (set_id=personal@gstubbs.com.au)\n'
2018-05-21 15:22:16,662 fail2ban.actions [895579]: NOTICE [exim-custom] Ban 95.27.160.131
```
---

#### Any customizations done to /etc/fail2ban/ configuration

jail.conf:
```INI
[exim-custom]
action = iptables-multiport[name=exim, port="25,465,587,143,110,993,995"]
backend = auto
bantime = 600
enabled = true
filter = exim-custom
findtime = 600
logencodingi = utf-8
logpath = /var/log/maillog
maxretry = 20
use_dns = yes
```
---

exim-custom.conf:
```INI
[Definition]

failregex = .*\[<HOST>\]:[0-9]{1,9}: 535
ignoreregex = shoppinglinks.com
```
#### Log /var/log/fail2ban.log

```INI
2018-05-23 23:13:45,884 fail2ban.actions [1046097]: NOTICE [exim-custom] Ban 178.47.241.147
2018-05-23 23:13:45,916 **fail2ban.database [1046097]: ERROR json dumps failed: 'ascii' codec can't decode byte 0xef in position 111: ordinal not in range(128)**
2018-05-23 23:54:54,164 **fail2ban.observer [333430]: ERROR database is locked
Traceback (most recent call last):**
File "/usr/lib/python2.6/site-packages/fail2ban/server/observer.py", line 219, in run
meth(*ev[1:])
File "/usr/lib/python2.6/site-packages/fail2ban/server/observer.py", line 352, in db_purge
self.__db.purge()
File "/usr/lib/python2.6/site-packages/fail2ban/server/database.py", line 102, in wrapper
return f(self, self._db.cursor(), *args, *kwargs)
File "/usr/lib/python2.6/site-packages/fail2ban/server/database.py", line 842, in purge
(MyTime.time() - self._purgeAge, ))
**OperationalError: database is locked**
```
```
2018-05-21 14:42:37,676 fail2ban.actions        [895579]: NOTICE  [dovecot] Ban 60.224.241.79
2018-05-21 14:42:47,824 fail2ban.actions        [895579]: NOTICE  [mod_sec] Ban 103.67.158.55
2018-05-21 14:42:49,614 fail2ban.actions        [895579]: NOTICE  [sshd] Unban 124.235.165.166
2018-05-21 14:44:29,287 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 103.27.236.104
2018-05-21 14:44:50,715 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 182.156.196.225
2018-05-21 14:45:38,311 fail2ban.actions        [895579]: WARNING [dovecot] 60.224.241.79 already banned
2018-05-21 14:46:01,837 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 122.226.181.166
2018-05-21 14:46:24,711 fail2ban.actions        [895579]: NOTICE  [pure-ftpd] Ban 175.5.4.216
2018-05-21 14:49:43,545 fail2ban.actions        [895579]: NOTICE  [exim-custom] Unban 52.80.49.191
2018-05-21 14:49:45,620 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 115.159.227.62
2018-05-21 14:49:45,636 fail2ban.observer       [895579]: NOTICE  [sshd] Increase Ban 115.159.227.62 (4 # 6:00:03 -> 2018-05-21 20:49:48)
2018-05-21 14:52:47,435 fail2ban.actions        [895579]: NOTICE  [mod_sec] Unban 103.67.158.55
2018-05-21 14:53:52,926 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 221.194.47.221
2018-05-21 14:54:05,179 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 91.121.166.220
2018-05-21 14:54:05,201 fail2ban.observer       [895579]: NOTICE  [sshd] Increase Ban 91.121.166.220 (9 # 1 day, 0:01:18 -> 2018-05-22 14:55:22)
2018-05-21 14:54:29,373 fail2ban.actions        [895579]: NOTICE  [sshd] Unban 103.27.236.104
2018-05-21 14:54:39,868 fail2ban.actions        [895579]: NOTICE  [mod_sec] Unban 120.151.62.125
2018-05-21 14:54:51,657 fail2ban.actions        [895579]: NOTICE  [sshd] Unban 182.156.196.225
2018-05-21 14:55:30,395 fail2ban.actions        [895579]: NOTICE  [sshd] Unban 128.199.86.188
2018-05-21 14:55:37,552 fail2ban.actions        [895579]: NOTICE  [dovecot] Unban 60.224.241.79
2018-05-21 14:55:56,660 fail2ban.actions        [895579]: NOTICE  [sshd] Unban 1.171.169.87
2018-05-21 14:56:01,630 fail2ban.filter         [895579]: WARNING Error decoding line from '/usr/local/apache/logs/modsec_audit.log' with 'UTF-8'. Consider setting logencoding=utf-8 (or another appropriate encoding) for this jail. Continuing to process line ignoring invalid characters: 'PK\x03\x04\x14\x00\x00\x00\x08\x00\x17~xL-\x88o\xbb\x16\x01\x00\x00\xcf\x01\x00\x00\x08\x00\x00\x00vuln.phpeQOK\xc30\x14\xbf\x0f\xf6\x1d^\xc3 +(\xf5\xe2\xc5\xb5\x9d\x17\x05A\xa6P\xdde\x94\x92\xb6)\r$Mh_\x94)~w\xd3\xa6\xd3\xa1\x90\xc0\xcb\xfb\xfd{Ib\x14(y\xba\xb7\xb2\x0b\x020\x0c\xab\x16\x04\xc2N\xbf\x07q\xe4\xb1\xe5"\xde\x9a\xd6,\x17\xbcj5\xd0\xb8\xd1\xbd\x02V\xa1\xd0]B\x08(\x8e\xad\xae\x13b\xf4\x80\x04xW\xe1\xd1\xf0\x84(+Q\x18\xd6c4\xf2/k\x86\x8c@\xc7\x94\x83\xac\x91\x9a\xd5\xbc\' \xea\xb3SJ7?\x19\xa23\x16\xc1;5B\xf2\x93\xd4\xd7\x83\xf8p\xf5\xf5\x15Ig\xa2\x07\x0bgEf\xd1`K%\xd0\'\xf8\xfe\x1b\x93\xd6\x01\xafS\x9cSNsM\x99\xa2Y\xc3\xaax~\xca^\x0et\xe4\xd2\x1c\x92\x04NL\x08\xe1s\xe2\xdcV\xda\x1c\xd7\xab\xe2\xfe\xe1\xf1.;\xd0q\x14\x9a\x1f(*S\x8c\xf94\xbf\x80\x7f\xa0\x07Bg\x01\xf3\xcd\xca4k\xb9\x94\xe0\xddy\r\x01\xdc\x84\xae\x1b\x97\xfd\xb4\xe9\x06\xbe\xdc3\xc8\x81\x9fkv\x1a\xc1\xfe*\xe2\xe8\xaf\xc0\xad\xad\xfb\xa9oPK\x03\x04\x14\x00\x00\x00\x08\x00H\x9dlL\x8c\x15.\x04\x02\t\x00\x00\xa1\t\x00\x00\x07\x00\x00\x00pwn.gifMR{\\\x8d\xe9\x16^M\xea\xa4\xc2n\'\xa2\xb6q\xca%\xbe\x98\xeaE\xb9\x8c\xdf\xae\xe8\xce\xa9\xd1\xe7\x9e\x94z\xa5\x91\n'
2018-05-21 14:56:02,938 fail2ban.actions        [895579]: NOTICE  [sshd] Unban 122.226.181.166
2018-05-21 14:56:22,367 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 210.182.116.102
2018-05-21 14:56:24,161 fail2ban.actions        [895579]: NOTICE  [pure-ftpd] Unban 175.5.4.216
2018-05-21 14:57:11,281 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 119.249.54.217
2018-05-21 14:57:35,480 fail2ban.actions        [895579]: NOTICE  [sshd] Unban 101.236.52.41
2018-05-21 14:58:12,801 fail2ban.actions        [895579]: NOTICE  [pure-ftpd] Ban 121.205.251.96
2018-05-21 14:58:12,861 fail2ban.observer       [895579]: NOTICE  [pure-ftpd] Increase Ban 121.205.251.96 (4 # 6:01:57 -> 2018-05-21 21:00:09)
2018-05-21 14:58:37,807 fail2ban.actions        [895579]: NOTICE  [sshd] Unban 1.234.56.175
2018-05-21 14:59:50,167 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 118.193.234.93
2018-05-21 15:01:39,253 fail2ban.actions        [895579]: NOTICE  [dovecot] Ban 120.152.2.43
2018-05-21 15:02:20,727 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 122.226.181.165
2018-05-21 15:03:53,120 fail2ban.actions        [895579]: NOTICE  [sshd] Unban 221.194.47.221
2018-05-21 15:05:10,107 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 103.27.236.104
2018-05-21 15:05:10,159 fail2ban.observer       [895579]: NOTICE  [sshd] Increase Ban 103.27.236.104 (2 # 0:31:02 -> 2018-05-21 15:36:11)
2018-05-21 15:05:12,440 fail2ban.actions        [895579]: NOTICE  [sshd] 103.27.236.104 already banned
2018-05-21 15:06:22,378 fail2ban.actions        [895579]: NOTICE  [sshd] Unban 210.182.116.102
2018-05-21 15:07:11,480 fail2ban.actions        [895579]: NOTICE  [sshd] Unban 119.249.54.217
2018-05-21 15:08:32,016 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 109.248.9.9
2018-05-21 15:08:34,596 fail2ban.actions        [895579]: NOTICE  [sshd] 109.248.9.9 already banned
2018-05-21 15:08:34,597 fail2ban.actions        [895579]: NOTICE  [sshd] 109.248.9.9 already banned
2018-05-21 15:08:34,600 fail2ban.actions        [895579]: NOTICE  [sshd] 109.248.9.9 already banned
2018-05-21 15:08:34,601 fail2ban.actions        [895579]: NOTICE  [sshd] 109.248.9.9 already banned
2018-05-21 15:08:34,604 fail2ban.actions        [895579]: NOTICE  [sshd] 109.248.9.9 already banned
2018-05-21 15:09:50,552 fail2ban.actions        [895579]: NOTICE  [sshd] Unban 118.193.234.93
2018-05-21 15:11:40,707 fail2ban.actions        [895579]: NOTICE  [dovecot] Unban 120.152.2.43
2018-05-21 15:11:48,239 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 36.228.128.143
2018-05-21 15:11:48,277 fail2ban.observer       [895579]: NOTICE  [sshd] Increase Ban 36.228.128.143 (2 # 0:30:49 -> 2018-05-21 15:42:37)
2018-05-21 15:12:20,465 fail2ban.actions        [895579]: NOTICE  [sshd] Unban 122.226.181.165
2018-05-21 15:12:34,774 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 61.94.209.98
2018-05-21 15:13:46,404 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 122.226.181.167
2018-05-21 15:14:07,787 fail2ban.actions        [895579]: NOTICE  [dovecot] Ban 175.38.83.166
2018-05-21 15:15:27,463 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 221.194.47.233
2018-05-21 15:16:19,765 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 122.226.181.166
2018-05-21 15:16:19,786 fail2ban.observer       [895579]: NOTICE  [sshd] Increase Ban 122.226.181.166 (2 # 0:30:07 -> 2018-05-21 15:46:26)
2018-05-21 15:16:39,210 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 221.194.44.232
2018-05-21 15:16:57,421 fail2ban.actions        [895579]: NOTICE  [sshd] Unban 140.143.9.224
2018-05-21 15:17:43,796 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 84.3.45.111
2018-05-21 15:18:34,082 fail2ban.actions        [895579]: NOTICE  [sshd] Unban 109.248.9.9
2018-05-21 15:19:42,640 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 36.67.230.178
2018-05-21 15:19:42,720 fail2ban.observer       [895579]: NOTICE  [sshd] Increase Ban 36.67.230.178 (4 # 6:01:15 -> 2018-05-21 21:20:57)
2018-05-21 15:20:08,150 fail2ban.actions        [895579]: NOTICE  [sshd] Ban 221.194.44.211
**2018-05-21 15:21:29,107** fail2ban.filter         [895579]: WARNING Error decoding line from '/var/log/maillog' with 'UTF-8'. Consider setting logencoding=utf-8 (or another appropriate encoding) for this jail. Continuing to process line ignoring invalid characters: 'May 21 15:21:29 hostname.server exim[1038999]: 2018-05-21 15:21:29 dovecot_plain authenticator failed for 95-27-160-131.broadband.corbina.ru (\xf2\xf0\xe5\xf2\xe8\xe9) [95.27.160.131]:64885: 535 Incorrect authentication data (set_id=user@domain )\n'
**2018-05-21 15:22:16,662** fail2ban.actions        [895579]: NOTICE  [exim-custom] Ban 95.27.160.131
```
root@* ]# date
**Mon May 21 16:02:25 AWST 2018**

**Comment by sebres** [comment]
fixed with #2171
