### ISSUE TITLE
Cannot start with AttributeError: 'NoneType' object has no attribute 'startswith' 

### ISSUE THREAD

**Issue by breisig** [fail2ban/fail2ban#2177]
When installing the latest Fail2ban [v0.10 branch] from git, fail2ban doesn't startup but shows the following error message. (from systemd)

-- Unit fail2ban.service has begun starting up.
Jul 10 23:17:48 server fail2ban-client[21134]: Traceback (most recent call last):
Jul 10 23:17:48 server fail2ban-client[21134]:   File "/usr/bin/fail2ban-client", line 34, in <module>
Jul 10 23:17:48 server fail2ban-client[21134]:     from fail2ban.client.fail2banclient import exec_command_line, sys
Jul 10 23:17:48 server fail2ban-client[21134]:   File "/usr/lib/python2.7/site-packages/fail2ban/client/fail2banclient.py", line 35, in <module>
Jul 10 23:17:48 server fail2ban-client[21134]:     from .beautifier import Beautifier
Jul 10 23:17:48 server fail2ban-client[21134]:   File "/usr/lib/python2.7/site-packages/fail2ban/client/beautifier.py", line 25, in <module>
Jul 10 23:17:48 server fail2ban-client[21134]:     from ..helpers import getLogger, logging
Jul 10 23:17:48 server. fail2ban-client[21134]:   File "/usr/lib/python2.7/site-packages/fail2ban/helpers.py", line 39, in <module>
Jul 10 23:17:48 server fail2ban-client[21134]:     if sys.stdout and not sys.stdout.encoding.startswith('ANSI_'):
Jul 10 23:17:48 server fail2ban-client[21134]: AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by sebres** [comment]
Thx... going to fix.

**Comment by sebres** [comment]
Fixed, would be nice if you could test and let us know.

**Comment by breisig** [comment]
@sebres It's now working again, thanks!

**Comment by sebres** [comment]
Thank you too!
