### ISSUE TITLE
Failed to process line - caught exception: KeyError

### ISSUE THREAD

**Issue by johnramsden** [fail2ban/fail2ban#2277]
### Environment:

- Fail2Ban version 0.10.1:
- OS, Ubuntu 14.04
- Fail2Ban installed via PPA for 0.10.1
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration

### The issue:

On a recurring basis I've been noticing the following error in my logs:

```
2018-11-18 00:02:22,097 fail2ban.filter         [13983]: ERROR   Failed to process line: u'104.199.114.234 spbatpa.org - [17/Nov/2018:18:09:43 -0600] "GET / HTTP/1.1" 200 44828 "http://example.com" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0" "-" "-"\n', caught exception: KeyError((u'118.93.131.93', -4),)

2018-11-18 00:06:27,736 fail2ban.filter         [13983]: ERROR   Failed to process line: u'176.145.93.237 www.example.org - [18/Nov/2018:00:02:50 -0600] "GET /services/rest/user/110746 HTTP/1.1" 403 67 "-" "WSAndroid 2.0.3 HUAWEI ALE-L21 Android v6.0" "0.64" "FR"\n', caught exception: KeyError((u'54.36.150.156', -4),)
```

I was wondering what might be causing the error and what I should do to fix the problem if it's fixable.

#### Expected behavior

No error.

#### Any customizations done to /etc/fail2ban/ configuration

Filters:

```nginx-request.local```

```
[Definition]

failregex = ^<HOST> .*
ignoreregex =
```

```nginx-badbots.local```

```
[Definition]

badbotscustom = Seekport Crawler|EmailCollector|WebEMailExtrac|TrackBack/1\.02|sogou music spider
badbots = Atomic_Email_Hunter/4\.0|atSpider/1\.0|autoemailspider|bwh3_user_agent|China Local Browse 2\.6|ContactBot/0\.2|ContentSmartz|DataCha0s/2\.0|DBrowse 1\.4b|DBrowse 1\.4d|Demo Bot DOT 16b|Demo Bot Z 16b|DSurf15a 01|DSurf15a 71|DSurf15a 81|DSurf15a VA|EBrowse 1\.4b|Educate Search VxB|EmailSiphon|EmailSpider|EmailWolf 1\.00|ESurf15a 15|ExtractorPro|Franklin Locator 1\.8|FSurf15a 01|Full Web Bot 0416B|Full Web Bot 0516B|Full Web Bot 2816B|Guestbook Auto Submitter|Industry Program 1\.0\.x|ISC Systems iRc Search 2\.1|IUPUI Research Bot v 1\.9a|LARBIN-EXPERIMENTAL \(efp@gmx\.net\)|LetsCrawl\.com/1\.0 +http\://letscrawl\.com/|Lincoln State Web Browser|LMQueueBot/0\.2|LWP\:\:Simple/5\.803|Mac Finder 1\.0\.xx|MFC Foundation Class Library 4\.0|Microsoft URL Control - 6\.00\.8xxx|Missauga Locate 1\.0\.0|Missigua Locator 1\.9|Missouri College Browse|Mizzu Labs 2\.2|Mo College 1\.9|MVAClient|Mozilla/2\.0 \(compatible; NEWT ActiveX; Win32\)|Mozilla/3\.0 \(compatible; Indy Library\)|Mozilla/3\.0 \(compatible; scan4mail \(advanced version\) http\://www\.peterspages\.net/?scan4mail\)|Mozilla/4\.0 \(compatible; Advanced Email Extractor v2\.xx\)|Mozilla/4\.0 \(compatible; Iplexx Spider/1\.0 http\://www\.iplexx\.at\)|Mozilla/4\.0 \(compatible; MSIE 5\.0; Windows NT; DigExt; DTS Agent|Mozilla/4\.0 efp@gmx\.net|Mozilla/5\.0 \(Version\: xxxx Type\:xx\)|NameOfAgent \(CMS Spider\)|NASA Search 1\.0|Nsauditor/1\.x|PBrowse 1\.4b|PEval 1\.4b|Poirot|Port Huron Labs|Production Bot 0116B|Production Bot 2016B|Production Bot DOT 3016B|Program Shareware 1\.0\.2|PSurf15a 11|PSurf15a 51|PSurf15a VA|psycheclone|RSurf15a 41|RSurf15a 51|RSurf15a 81|searchbot admin@google\.com|ShablastBot 1\.0|snap\.com beta crawler v0|Snapbot/1\.0|Snapbot/1\.0 \(Snap Shots&#44; +http\://www\.snap\.com\)|sogou develop spider|Sogou Orion spider/3\.0\(+http\://www\.sogou\.com/docs/help/webmasters\.htm#07\)|sogou spider|Sogou web spider/3\.0\(+http\://www\.sogou\.com/docs/help/webmasters\.htm#07\)|sohu agent|SSurf15a 11 |TSurf15a 11|Under the Rainbow 2\.2|User-Agent\: Mozilla/4\.0 \(compatible; MSIE 6\.0; Windows NT 5\.1\)|VadixBot|WebVulnCrawl\.unknown/1\.0 libwww-perl/5\.803|Wells Search II|WEP Search 00

failregex = ^<HOST>.*(?:%(badbots)s|%(badbotscustom)s).*$

ignoreregex =
```

```jail.local```:

```
[DEFAULT]

ignoreip = 127.0.0.1/8 

bantime  = 10m

findtime = 6m
maxretry = 3

backend = auto

#
# ACTIONS
#

# Default banning action
banaction = iptables-ipset-proto6-allports

# Default protocol
protocol = tcp

# Specify chain where jumps would need to be added in iptables-* actions
chain = ban

#
# Action shortcuts. To be used to define action parameter
protocol_ipset6_ = all
action_ipset6_ = %(banaction)s[name=%(__name__)s, protocol="%(protocol_ipset6_)s", bantime="%(bantime)s", chain="%(chain)s"]
action = %(action_ipset6_)s

www_error_logs_ = /var/www/log/error/*error.log
www_access_logs_ = /var/www/log/access/*access.log

#
# JAILS
#

#
# SSH servers
#

[sshd]

# To use more aggressive sshd modes set filter parameter "mode" in jail.local:
# normal (default), ddos, extra or aggressive (combines all).
# See "tests/files/logs/sshd" or "filter.d/sshd.conf" for usage example and details.
enabled  = true
mode    = normal
filter  = sshd[mode=%(mode)s]
port    = 27271
backend = %(sshd_backend)s
banaction = iptables-ipset-proto6
logpath  = /var/log/auth.log
action = %(action_)s

#
# nginx
#

[nginx-http-auth]

enabled = true
filter  = nginx-http-auth
logpath = %(www_error_logs_)s

#
# nginx-badbots
#

[nginx-badbots-10]

enabled  = true
filter   = nginx-badbots
logpath  = %(www_access_logs_)s
maxretry = 2
bantime = 2h
findtime = 10m

[nginx-badbots-1440]

enabled  = true
filter   = nginx-badbots
logpath  = %(www_access_logs_)s
maxretry = 6
bantime = 24h
findtime = 7h

#
# nginx-aggr
#

[nginx-aggr-00-30]

enabled  = true
filter   = nginx-request
logpath  = %(www_access_logs_)s
maxretry = 10
findtime = 30s
bantime = 2m

[nginx-aggr-5]

enabled  = true
filter   = nginx-request
logpath  = %(www_access_logs_)s
maxretry = 50
findtime = 5m
bantime = 1m

[nginx-aggr-30]

enabled  = true
filter   = nginx-request
logpath  = %(www_access_logs_)s
maxretry = 250
findtime = 30m
bantime = 5m

[nginx-aggr-60]

enabled  = true
filter   = nginx-request
logpath  = %(www_access_logs_)s
maxretry = 400
findtime = 1h
bantime = 1h

[nginx-aggr-120]

enabled  = true
filter   = nginx-request
logpath  = %(www_access_logs_)s
maxretry = 600
findtime = 2h
bantime = 24h

[nginx-aggr-1440]

enabled  = true
filter   = nginx-request
logpath  = %(www_access_logs_)s
maxretry = 750
findtime = 24h
bantime = 6h
```

**Comment by sebres** [comment]
Hmm... it looks like an after effect (some other previous failures can cause this)... 
Can you provide please the log-excerpt with the IPs that are mentioned in KeyError (e. g. grep using 54.36.150.156)?
Another possibility would be try to set DEBUG log-level (if your server does not has too large load), because fail2ban will provide more info in DEBUG level if this error occurs (e. g. the call stack).
Or to avoid large debug-output, you can try to change this line manually:
https://github.com/fail2ban/fail2ban/blob/0.10/fail2ban/server/filter.py#L611-L612
```diff
			logSys.error("Failed to process line: %r, caught exception: %r", line, e,
-				exc_info=logSys.getEffectiveLevel()<=logging.DEBUG)
+				exc_info=True)
```
After restart of fail2ban you'll get a call stack if this error occurs again.

**Comment by johnramsden** [comment]
logs:

<details><summary>176.145.93.237</summary><p>

```
2018-11-17 15:40:23,683 fail2ban.filter         [13983]: INFO    [nginx-aggr-5] Found 176.145.93.237 - 2018-11-17 15:39:11
2018-11-17 15:40:23,710 fail2ban.filter         [13983]: INFO    [nginx-aggr-120] Found 176.145.93.237 - 2018-11-17 15:39:11
2018-11-17 15:40:23,713 fail2ban.filter         [13983]: INFO    [nginx-aggr-30] Found 176.145.93.237 - 2018-11-17 15:39:11
2018-11-17 15:40:23,758 fail2ban.filter         [13983]: INFO    [nginx-aggr-1440] Found 176.145.93.237 - 2018-11-17 15:39:11
2018-11-17 15:40:23,777 fail2ban.filter         [13983]: INFO    [nginx-aggr-60] Found 176.145.93.237 - 2018-11-17 15:39:11
2018-11-17 15:41:12,571 fail2ban.filter         [13983]: INFO    [nginx-aggr-1440] Found 176.145.93.237 - 2018-11-17 15:39:10
2018-11-17 15:41:13,548 fail2ban.filter         [13983]: INFO    [nginx-aggr-5] Found 176.145.93.237 - 2018-11-17 15:39:10
2018-11-17 15:41:13,633 fail2ban.filter         [13983]: INFO    [nginx-aggr-30] Found 176.145.93.237 - 2018-11-17 15:39:10
2018-11-17 15:41:13,704 fail2ban.filter         [13983]: INFO    [nginx-aggr-120] Found 176.145.93.237 - 2018-11-17 15:39:10
2018-11-17 15:41:13,752 fail2ban.filter         [13983]: INFO    [nginx-aggr-60] Found 176.145.93.237 - 2018-11-17 15:39:10
2018-11-18 00:06:27,731 fail2ban.filter         [13983]: INFO    [nginx-aggr-1440] Found 176.145.93.237 - 2018-11-18 00:02:50
2018-11-18 00:06:27,736 fail2ban.filter         [13983]: ERROR   Failed to process line: u'176.145.93.237 www.example.org - [18/Nov/2018:00:02:50 -0600] "
GET /services/rest/user/110746 HTTP/1.1" 403 67 "-" "WSAndroid 2.0.3 HUAWEI ALE-L21 Android v6.0" "0.64" "FR"\n', caught exception: KeyError((u'54.36.150.156'
, -4),)
2018-11-18 00:06:27,790 fail2ban.filter         [13983]: INFO    [nginx-aggr-60
] Found 176.145.93.237 - 2018-11-18 00:02:50
2018-11-18 00:06:27,791 fail2ban.filter         [13983]: INFO    [nginx-aggr-5]
 Found 176.145.93.237 - 2018-11-18 00:02:50
2018-11-18 00:06:27,993 fail2ban.filter         [13983]: INFO    [nginx-aggr-12
0] Found 176.145.93.237 - 2018-11-18 00:02:50
2018-11-18 00:19:27,673 fail2ban.filter         [13983]: INFO    [nginx-aggr-14
40] Found 176.145.93.237 - 2018-11-18 00:02:51
```
</p></details>

<details><summary>104.199.114.234</summary><p>
```
2018-11-16 12:03:52,072 fail2ban.filter         [13983]: INFO    [nginx-aggr-120] Found 104.199.114.234 - 2018-11-16 11:18:40
2018-11-16 12:03:52,082 fail2ban.filter         [13983]: INFO    [nginx-aggr-120] Found 104.199.114.234 - 2018-11-16 11:18:40
2018-11-16 12:03:52,253 fail2ban.filter         [13983]: INFO    [nginx-aggr-60] Found 104.199.114.234 - 2018-11-16 11:18:40
2018-11-16 12:03:52,254 fail2ban.filter         [13983]: INFO    [nginx-aggr-60] Found 104.199.114.234 - 2018-11-16 11:18:40
2018-11-16 12:03:52,369 fail2ban.filter         [13983]: INFO    [nginx-aggr-1440] Found 104.199.114.234 - 2018-11-16 11:18:40
2018-11-16 12:03:52,369 fail2ban.filter         [13983]: INFO    [nginx-aggr-1440] Found 104.199.114.234 - 2018-11-16 11:18:40
2018-11-16 14:22:44,296 fail2ban.filter         [13983]: INFO    [nginx-aggr-120] Found 104.199.114.234 - 2018-11-16 14:12:25
2018-11-16 14:22:44,308 fail2ban.filter         [13983]: INFO    [nginx-aggr-120] Found 104.199.114.234 - 2018-11-16 14:12:25
2018-11-16 14:22:44,311 fail2ban.filter         [13983]: INFO    [nginx-aggr-30] Found 104.199.114.234 - 2018-11-16 14:12:25
2018-11-16 14:22:44,316 fail2ban.filter         [13983]: INFO    [nginx-aggr-30] Found 104.199.114.234 - 2018-11-16 14:12:25
2018-11-16 14:22:44,317 fail2ban.filter         [13983]: INFO    [nginx-aggr-60] Found 104.199.114.234 - 2018-11-16 14:12:25
2018-11-16 14:22:44,322 fail2ban.filter         [13983]: INFO    [nginx-aggr-60] Found 104.199.114.234 - 2018-11-16 14:12:25
2018-11-16 14:22:44,572 fail2ban.filter         [13983]: INFO    [nginx-aggr-1440] Found 104.199.114.234 - 2018-11-16 14:12:25
2018-11-16 14:22:44,579 fail2ban.filter         [13983]: INFO    [nginx-aggr-1440] Found 104.199.114.234 - 2018-11-16 14:12:25
2018-11-17 04:20:06,105 fail2ban.filter         [13983]: INFO    [nginx-aggr-30] Found 104.199.114.234 - 2018-11-17 04:01:36
2018-11-17 04:20:06,486 fail2ban.filter         [13983]: INFO    [nginx-aggr-120] Found 104.199.114.234 - 2018-11-17 04:01:36
2018-11-17 04:20:06,487 fail2ban.filter         [13983]: INFO    [nginx-aggr-60] Found 104.199.114.234 - 2018-11-17 04:01:36
2018-11-17 04:20:06,490 fail2ban.filter         [13983]: INFO    [nginx-aggr-1440] Found 104.199.114.234 - 2018-11-17 04:01:36
2018-11-17 08:20:06,501 fail2ban.filter         [13983]: INFO    [nginx-aggr-1440] Found 104.199.114.234 - 2018-11-17 04:01:36
2018-11-18 00:02:22,097 fail2ban.filter         [13983]: ERROR   Failed to process line: u'104.199.114.234 spbatpa.org - [17/Nov/2018:18:09:43 -0600] "GET / HTTP/1.1" 200 44828 "http://example.com" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0" "-" "-"\n', caught exception: KeyError((u'118.93.131.93', -4),)
2018-11-18 00:02:24,347 fail2ban.filter         [13983]: INFO    [nginx-aggr-1440] Found 104.199.114.234 - 2018-11-17 18:09:43
```
</p></details>

---

I don't think I can enable debug since our load is fairly high. Adding the line you mentioned would just dump a calltrace to our logs if the error occurs?

**Comment by sebres** [comment]
> logs

No I meant the nginx-logs (not fail2ban) and grep by the IP from KeyError (e. g. 54.36.150.156).

> Adding the line you mentioned would just dump a calltrace to our logs if the error occurs?

Yes and exactly by this error only.

By the way, the usage of several jails `nginx-aggr...` observing the same log is a bit weird (at least not optimal). I know what you're trying to do, but... possibly you can try ban-time-incr feature of 0.11th version of fail2ban (doing almost the same but inside the single jail).

**Comment by sebres** [comment]
> If i'm running from a package, am I safe to edit

Yes, just create a backup of this file before you patch it.

**Comment by johnramsden** [comment]
Yes I'm aware it's not optimal and I am looking forward to ban-time-incr.

The grep for the IP returns a huge number of entries, will it be of any usage to you? I don't think I even have the relevant entries that caused the errors anymore since my logs have been rotated.

**Comment by sebres** [comment]
is there any news about that? do you still have a patched version running?

**Comment by johnramsden** [comment]
Yes, I actually didn't get around to patching it until yesterday though. I'll let you know when it occurs.

**Comment by johnramsden** [comment]
I got another error in my `fail2ban.log`, but I just ended up with the same information:

```
2018-12-16 00:10:10,420 fail2ban.filter         [13983]: ERROR   Failed to process line: u'111.111.120.232 www.example.org - [16/Dec/2018:00:08:49 -0600] "POST /services/rest/hosts/by_location HTTP/1.1" 200 3792 "-" "WSAndroid 2.0.3 HUAWEI HUAWEI VNS-L31 Android v6.0" "4.84" "TH"\n', caught exception: KeyError((u'111.111.164.52', -4),)
```

Does the debugging information go somewhere other than the log? I should have expected to see a trace back right?

Here's my patched file:

```
except Exception as e:
    logSys.error("Failed to process line: %r, caught exception: %r", line, e,
        exc_info=True)
```

**Comment by sebres** [comment]
Nope, it would be normally logged into the same target.
Either fail2ban is not restarted after patch, or the patch is applied to other file (or some old pre-compiled version is still used / doesn't updated for some reasons).

**Comment by sebres** [comment]
Note if you has used grep ERROR, it may not catch the except-info, because it may be simply added to log as pure multi-line string output without typical log structure.

**Comment by johnramsden** [comment]
Yeah I checked after it and there was no message. Maybe I forgot to restart it. I will do that and get back to you.

**Comment by johnramsden** [comment]
Okay, finally got the exception:

```
2018-12-23 16:17:20,072 fail2ban.filter         [28608]: ERROR   Failed to process line: u'111.111.111.111 example.com - [23/Dec/2018:10:03:26 -0600] "GET /blog/x HTTP/1.1" 200 16683 "https://www.google.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36" "4.47" "US"\n', caught exception: KeyError((u'111.111.111.111', -4),)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/fail2ban/server/filter.py", line 545, in processLineAndAdd
    for element in self.processLine(line, date):
  File "/usr/lib/python2.7/dist-packages/fail2ban/server/filter.py", line 539, in processLine
    return self.findFailure(tupleLine, date)
  File "/usr/lib/python2.7/dist-packages/fail2ban/server/filter.py", line 774, in findFailure
    ip = IPAddr(host, cidr)
  File "/usr/lib/python2.7/dist-packages/fail2ban/server/ipdns.py", line 224, in __new__
    IPAddr.CACHE_OBJ.set(args, ip)
  File "/usr/lib/python2.7/dist-packages/fail2ban/server/utils.py", line 96, in set
    del cache[ck]
```

**Comment by sebres** [comment]
Thanks. I'll fix it soon.

**Comment by johnramsden** [comment]
Thanks!

**Comment by leonardocuei** [comment]
Hello guys ... i'm running fail2ban with correctly patched "fail2ban/server/utils.py" file, and still caught exception keyerror thing ... it's running on a VERY busy server

example:

2019-02-18 08:22:33,052 fail2ban.filter         [3422]: ERROR   Failed to process line: u'Feb 18 08:12:42 correio dovecot: auth-worker(3038): sql(USER@MYDOMAIN.com.br,177.79.XX.XX,<xxxxxxxxxxxxxxx>): Password mismatch (given password: XXXXXXXX)\n', caught
exception: KeyError((u'54.39.xx.xx', -4),)

(IPs are different on the logline and keyerror message ... is this correct/expected? The second IP, 54.39.x.x, is an actually banned IP)

The same logfile, processed with fail2ban-regex, shows no problem at all and gives the expected match:

[root@correio shm]# fail2ban-regex /dev/shm/teste /etc/fail2ban/filter.d/dovecot.conf
[ ... ]
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.01 sec]

Once the ERROR ... caught exception KeyError messages started, logfile is flooded with them. Stoppping and restarting fail2ban daemon seems to stop the error from appearing for a long time.

**Comment by sebres** [comment]
> i'm running fail2ban with correctly patched "fail2ban/server/utils.py" file

How sure you are? I mean, it is really fail2ban version that running (you should check python-version, so it should be patched in the module that used).
Stupid question: you have restarted fail2ban after you patched that?

Reviewed the fix again, and don't see where it could throw `KeyError((IP, ...))` anymore...
It was always to hard to reproduce, but I'll take a closer look (resp. try to cover this with more multi-threaded test-cases)...

**Comment by sebres** [comment]
Got it (reproduced). Fix coming soon.
Thanks.

**Comment by leonardocuei** [comment]
You're welcome :) And yes i'm pretty sure, i'm running a 'git clone' version which already came fully patched, i never patched the file anyway.

I'll be glad to help testing any new patches :) It's not occuring 'always' and after stop/start seems to take a while to happens again. But it eventually always happens.

**Comment by sebres** [comment]
I'm pretty sure it is fixed now in e30ebb1f3b408043d164a411b57661141e4fe1af, and it is also well reproducible with 14f997231d70314059d287691de153689125889b, 
so `fail2ban-testcases testOverflowedIPCache` would fail there (without fix).

But of course you could test it too if you want.

**Comment by conandrum** [comment]
I know this is closed, but wanted to ask.
I have Fail2Ban v0.10.2 and I am getting this same error.
2019-03-14 11:32:42,218 fail2ban.filter         [967]: ERROR   Failed to process line: 'Mar 14 11:32:42 ns1 sshd[20043]: Invalid user fer from 121.133.183.121 port 28119\n', caught exception: KeyError(('self', 'ips'),)

I cannot update fail2ban because it came with Virtualmin.
I want to ask whether my VPS is in danger because of this error?

**Comment by sebres** [comment]
> I want to ask whether my VPS is in danger because of this error?

Well what one would understand as danger... 
However, it is clear that "Failed to process line" means the fail2ban can not recognize the line as possible failure, so does not hit it, so the IP possibly does not reach maxretry value (during a findtime) and therefore does not banned (but it can happen later if no such error occurring for this IP).

It's not good, sure.... But it is not critical (unless the log is full by errors like this).

**Comment by conandrum** [comment]
only one error so far in a week. I will keep an eye out. 
I am glad that this does not affect fail2ban further than the single line where it happens.
Thanks for your help.

**Comment by sebres** [comment]
yw
> this does not affect fail2ban further than the single line where it happens.

otherwise I had labeled the issue as "grave" and we had should provide a hot-fix release for that. :)

**Comment by Sin4th** [comment]
Hey i have fail2ban 0.11.2 and the same error on a json traefik log line.
Regex tester shows no match (correctly) but i still get error messages in the log.

regex: `^.*ClientHost":"<HOST>".*POST.*xmlrpc\.php.*`

logline (replaced ips): `{"ClientAddr":"12.12.12.12:41046","ClientHost":"12.12.12.12","ClientPort":"41046","ClientUsername":"-","DownstreamContentSize":19,"DownstreamStatus":404,"Duration":240708,"OriginContentSize":19,"OriginDuration":20342,"OriginStatus":404,"Overhead":220366,"RequestAddr":"12.12.12.12:443","RequestContentSize":0,"RequestCount":23,"RequestHost":"5.255.77.9","RequestMethod":"GET","RequestPath":"/","RequestPort":"443","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"StartLocal":"2022-09-27T18:44:25.457733309Z","StartUTC":"2022-09-27T18:44:25.457733309Z","entryPointName":"websecure","level":"info","msg":"","time":"2022-09-27T18:44:25Z"}`

regex test output: `Lines: 1 lines, 0 ignored, 0 matched, 1 missed
[processed in 0.02 sec]
`

**Comment by sebres** [comment]
No, the issues are different.

**Comment by Sin4th** [comment]
Realized that and just opened a new ticket:
https://github.com/fail2ban/fail2ban/issues/3366
