### ISSUE TITLE
from fail2ban log: CRITICAL Unhandled exception in Fail2Ban

### ISSUE THREAD

**Issue by bar2019** [fail2ban/fail2ban#2395]
### Environment:
- Fail2Ban version (including any possible distribution suffixes):
fail2ban.noarch               0.9.7-1.el7           installed
fail2ban-firewalld.noarch     0.9.7-1.el7           installed
fail2ban-sendmail.noarch      0.9.7-1.el7           installed
fail2ban-server.noarch        0.9.7-1.el7           installed
fail2ban-systemd.noarch       0.9.7-1.el7           installed

- OS, including release name/version: Oracle Linux Server 7.5

- [x] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Dear Fail2ban team,

I would like to ask you for your help or advice since I'm not python expert and I struggle with this issue for some days.

Explanation of the issue:
I've installed Fail2ban v0.9.7-1 with needed dependencies on our server - distribution Oracle Linux Server 7.5, Python version is 2.7.5.
I created a new jail.local file with following parameters:

**jail.local**
```ini
[DEFAULT]
ignoreip = 127.0.0.1/8
bantime = 600
findtime = 600
maxretry = 3
backend = systemd
logencoding = auto

[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/seclog.log
```
I didn't change anything in fail2ban.conf and even didn't create a new fail2ban.local.

And due to errors in /var/log/fail2ban.log during starting f2b service, I renamed 00-firewalld.conf to 00-firewalld.disabled in /etc/fail2ban/jail.d since I don't use firewalld.

With that configuration it was working for a while but then it stopped working (it doesn't register any login attempts) even though nothing was changed.
Probably after unban action following errors appeared in /var/log/fail2ban.log:
```
2019-03-28 16:13:09,243 fail2ban.jail           [351]: INFO    Jail 'sshd' started
2019-03-28 16:13:47,542 fail2ban.server         [351]: INFO    Stopping all jails
2019-03-28 16:13:48,501 fail2ban.jail           [351]: INFO    Jail 'sshd' stopped
2019-03-28 16:13:48,508 fail2ban.server         [351]: INFO    Stopping all jails
2019-03-28 16:13:48,508 fail2ban.server         [351]: INFO    Exiting Fail2ban
2019-03-28 16:13:48,683 fail2ban.server         [422]: INFO    Changed logging target to /var/log/fail2ban.log for Fail2ban v0.9.7
2019-03-28 16:13:48,684 fail2ban.database       [422]: INFO    Connected to fail2ban persistent database '/var/lib/fail2ban/fail2ban.sqlite3'
2019-03-28 16:13:48,685 fail2ban.jail           [422]: INFO    Creating new jail 'sshd'
2019-03-28 16:13:48,700 fail2ban.jail           [422]: INFO    Jail 'sshd' uses systemd {}
2019-03-28 16:13:48,713 fail2ban.jail           [422]: INFO    Initiated 'systemd' backend
2019-03-28 16:13:48,714 fail2ban.filter         [422]: INFO    Set maxRetry = 3
2019-03-28 16:13:48,715 fail2ban.filter         [422]: INFO    Set jail log file encoding to UTF-8
2019-03-28 16:13:48,715 fail2ban.actions        [422]: INFO    Set banTime = 600
2019-03-28 16:13:48,716 fail2ban.filter         [422]: INFO    Set findtime = 600
2019-03-28 16:13:48,716 fail2ban.filter         [422]: INFO    Set maxlines = 10
2019-03-28 16:13:48,773 fail2ban.filtersystemd  [422]: INFO    Added journal match for: '_SYSTEMD_UNIT=sshd.service + _COMM=sshd'
2019-03-28 16:13:48,782 fail2ban                [422]: CRITICAL Unhandled exception in Fail2Ban:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fail2ban/server/jailthread.py", line 66, in run_with_except_hook
    run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fail2ban/server/filtersystemd.py", line 280, in run
    *self.formatJournalEntry(logentry))
  File "/usr/lib/python2.7/site-packages/fail2ban/server/filtersystemd.py", line 207, in formatJournalEntry
    logelements[-1] += ("[%i]" % v)
TypeError: %d format: a number is required, not str
2019-03-28 16:13:48,784 fail2ban.jail           [422]: INFO    Jail 'sshd' started
```
I also removed and re-installed Fail2ban but it didn't help.

Could you please take a look at the issue and help me?

Many thanks in advance.

### Configuration, dump and another helpful excerpts

 **fail2ban-client status**
```
Status
|- Number of jail:      1
`- Jail list:   sshd
```
**fail2ban-client status sshd**
```
Status for the jail: sshd
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     0
|  `- Journal matches:  _SYSTEMD_UNIT=sshd.service + _COMM=sshd
`- Actions
   |- Currently banned: 0
   |- Total banned:     0
   `- Banned IP list:
```
**systemctl status fail2ban.service**
```
● fail2ban.service - Fail2Ban Service
   Loaded: loaded (/usr/lib/systemd/system/fail2ban.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-04-03 10:38:40 CEST; 3h 17min ago
     Docs: man:fail2ban(1)
  Process: 11299 ExecStop=/usr/bin/fail2ban-client stop (code=exited, status=0/SUCCESS)
  Process: 11304 ExecStart=/usr/bin/fail2ban-client -x start (code=exited, status=0/SUCCESS)
 Main PID: 11308 (fail2ban-server)
   CGroup: /system.slice/fail2ban.service
           └─11308 /usr/bin/python2.7 -s /usr/bin/fail2ban-server -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid -x -b

Apr 03 10:38:39 dcplnx23199083 systemd[1]: Stopped Fail2Ban Service.
Apr 03 10:38:39 dcplnx23199083 systemd[1]: Starting Fail2Ban Service...
Apr 03 10:38:40 dcplnx23199083 fail2ban-client[11304]: 2019-04-03 10:38:40,132 fail2ban.server         [11306]: INFO    Starting Fail2ban v0.9.7
Apr 03 10:38:40 dcplnx23199083 fail2ban-client[11304]: 2019-04-03 10:38:40,132 fail2ban.server         [11306]: INFO    Starting in daemon mode
Apr 03 10:38:40 dcplnx23199083 systemd[1]: Started Fail2Ban Service.
```

**Comment by sebres** [comment]
> `logelements[-1] += ("[%i]" % v)` ... `%d format: a number is required, not str`

Hmm... Related to current implementation (at least in 0.9th branch) https://github.com/fail2ban/fail2ban/blob/c7ddf1f940aa30f7d31dc1bf6e4d895713a6e38b/fail2ban/server/filtersystemd.py#L203-L207
it looks like either `SYSLOG_PID` or `_PID` of some entry in journal return string (not numeric) value using python-systemd module.
It is a bit unexpected...

I will provide a fix soon.
Thanks!

**Comment by bar2019** [comment]
Great, the issue is solved 👍 

Thank you very much for your help and time!
