### ISSUE TITLE
on fail2ban stop, 'pfctl: Table does not exist' errors seen in logs

### ISSUE THREAD

**Issue by dlangille** [fail2ban/fail2ban#2521]
### Environment:

- py27-fail2ban-0.10.4_2 on FreeBSD 12.0-RELEASE-p10 
- OS, including release name/version: 
- [ x] Fail2Ban installed via OS/distribution mechanisms
- [x ] You have not applied any additional foreign patches to the codebase
- [x ] Some customizations were done to the configuration (provide details below if so)

### The issue:

When I restart fail2ban, I see these messages in the logs:

2019-09-03 14:36:16,813 fail2ban.utils          [289]: ERROR   801fb4e00 -- stderr: 'pfctl: Table does not exist.'

#### Steps to reproduce

service fail2ban stop

#### Expected behavior

no ERRORs

#### Observed behavior

```
2019-09-03 14:36:16,813 fail2ban.utils          [289]: #39-Lev. 801fb4e00 -- exec: pfctl -a f2b/wordpress-xmlrpc -t f2b-wordpress-xmlrpc -T flush
2019-09-03 14:36:16,813 fail2ban.utils          [289]: ERROR   801fb4e00 -- stderr: 'pfctl: Table does not exist.'
2019-09-03 14:36:16,813 fail2ban.utils          [289]: ERROR   801fb4e00 -- killed with signal 127 (return code: 255)
2019-09-03 14:36:16,814 fail2ban                [289]: CRITICAL Unhandled exception in Fail2Ban:
```

#### Any additional information

These errors repeat for other tables:

```
2019-09-03 14:36:16,813 fail2ban.utils          [289]: #39-Lev. 801fb4e00 -- exec: pfctl -a f2b/wordpress-xmlrpc -t f2b-wordpress-xmlrpc -T flush
2019-09-03 14:36:16,829 fail2ban.utils          [289]: #39-Lev. 802429270 -- exec: pfctl -a f2b/wordpress -t fail2ban_ssh-wordpress -T flush
2019-09-03 14:36:17,025 fail2ban.utils          [289]: #39-Lev. 801f76558 -- exec: pfctl -a f2b/wordpress-pingback -t fail2ban_http-wordpress-pingback -T flush
2019-09-03 14:36:17,091 fail2ban.utils          [289]: #39-Lev. 802423710 -- exec: pfctl -a f2b/ssh-pf -t fail2ban_ssh-ssh-pf -T flush
```

#### Any customizations done to /etc/fail2ban/ configuration
```
$ cat jail.d/wordpress-xmlrpc.local
[INCLUDES]

before = common.conf

[Definition]

_daemon = wordpress

failregex = ^<HOST> .*"POST /xmlrpc\.php .*

ignoreregex =

datepattern = ^[^\[]*\[(%%d/%%b/%%Y:%%H:%%M:%%S %%z)\]
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
2019-09-03 14:46:04,145 fail2ban.filterpyinotif [7110]: DEBUG   [ssh-pf] filter exited (pyinotifier)
2019-09-03 14:46:04,212 fail2ban.actions        [7110]: DEBUG     Flush ban list
2019-09-03 14:46:04,212 fail2ban.actions        [7110]: NOTICE  [wordpress-xmlrpc] Flush ticket(s) with pf
2019-09-03 14:46:04,212 fail2ban.actions        [7110]: DEBUG     Flush ban list
2019-09-03 14:46:04,212 fail2ban.filterpyinotif [7110]: DEBUG   [wordpress-pingback] filter exited (pyinotifier)
2019-09-03 14:46:04,213 fail2ban.filterpyinotif [7110]: DEBUG   [wordpress] filter exited (pyinotifier)
2019-09-03 14:46:04,213 fail2ban.action         [7110]: DEBUG   pfctl -a f2b/wordpress-xmlrpc -t f2b-wordpress-xmlrpc -T flush
2019-09-03 14:46:04,213 fail2ban.actions        [7110]: NOTICE  [ssh-pf] Flush ticket(s) with pf
2019-09-03 14:46:04,213 fail2ban.action         [7110]: DEBUG   pfctl -a f2b/ssh-pf -t fail2ban_ssh-ssh-pf -T flush
2019-09-03 14:46:04,218 fail2ban.utils          [7110]: #39-Lev. 80241ae00 -- exec: pfctl -a f2b/wordpress-xmlrpc -t f2b-wordpress-xmlrpc -T flush
2019-09-03 14:46:04,219 fail2ban.utils          [7110]: ERROR   80241ae00 -- stderr: 'pfctl: Table does not exist.'
2019-09-03 14:46:04,219 fail2ban.utils          [7110]: ERROR   80241ae00 -- killed with signal 127 (return code: 255)
2019-09-03 14:46:04,219 fail2ban                [7110]: CRITICAL Unhandled exception in Fail2Ban:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/fail2ban/server/jailthread.py", line 69, in run_with_except_hook
    run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fail2ban/server/actions.py", line 287, in run
    self.__flushBan()
  File "/usr/local/lib/python2.7/site-packages/fail2ban/server/actions.py", line 468, in __flushBan
    action.flush()
  File "/usr/local/lib/python2.7/site-packages/fail2ban/server/action.py", line 493, in flush
    return self._executeOperation('<actionflush>', 'flushing', family=family)
  File "/usr/local/lib/python2.7/site-packages/fail2ban/server/action.py", line 399, in _executeOperation
    raise RuntimeError("Error %s action %s/%s" % (operation, self._jail, self._name,))
RuntimeError: Error flushing action Jail('wordpress-xmlrpc')/pf
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by dlangille** [comment]
Could this be related to missing `actionstop` entries in my .`/action.d/pf.local` file?

**Comment by sebres** [comment]
> pfctl: Table does not exist.

This said what it really is - the table seems not to exist (anymore). 
Possibly something (script, service or you) has deleted (killed) this table.
Or you have some name conflicts (so fail2ban used same names for chains, so by stop the second jail would miss the table.

> Could this be related to missing actionstop entries in my ./action.d/pf.local file?

No, in this case it shares the value from `action.d/pf.conf`.

**Comment by sebres** [comment]
Do you see any errors if fail2ban starting?

**Comment by dlangille** [comment]
Looking for duplicate table names:

```
[dan@zuul:/usr/local/etc/fail2ban] $ grep -r wordpress-xmlrpc *
jail.d/wordpress-xmlrpc.local:[wordpress-xmlrpc]
jail.d/wordpress-xmlrpc.local:filter  = wordpress-xmlrpc
```

**Comment by dlangille** [comment]
> Do you see any errors if fail2ban starting?

No, only INFO and NOTICE entries appear in `/var/log/fail2ban.log`

**Comment by sebres** [comment]
And you can surely exclude this?
> Possibly something (script, service or you) has deleted (killed) this table.

Anyway short excerpt of your log showing the command:
```
pfctl -a f2b/wordpress-xmlrpc -t f2b-wordpress-xmlrpc -T flush
```
and it looks good (at least if anchor "f2b/*" is specified and table has been not deleted.
May be wordpress-pingback or wordpress (which were stopping too) have removed something?
Or (weird but...) anchors or table names are restricted by size (truncated in pf)...

Please take a look into or provide a dump of actions for this jail:
```
fail2ban-client -d | grep -E 'wordpress-xmlrpc.*action'
```
For example is there only one action? `['set', 'wordpress-xmlrpc', 'addaction', ...]`

Can you try also this in shell (stop fail2ban firstly or rename the value of testjail `tjl` in script to something not conflicting with fail2ban's generated tables):
```bash
# test jail name (resulting to pf table names):
tjl="wordpress-xmlrpc"

# ==================================================
# == multi-port - pf                              ==
# ==================================================
# === start === =====
echo "table <f2b-$tjl> persist counters" | pfctl -a f2b/$tjl -f-
port="http,https"; if [ "$port" != "" ] && case "$port" in \{*) false;; esac; then port="{$port}"; fi
echo "block quick proto tcp from <f2b-$tjl> to any port $port" | pfctl -a f2b/$tjl -f-
# === ban-ipv4 === =====
pfctl -a f2b/$tjl -sr | grep -q f2b-$tjl
pfctl -a f2b/$tjl -t f2b-$tjl -T add 192.0.2.1
# === flush === =====
pfctl -a f2b/$tjl -t f2b-$tjl -T flush
# === stop === =====
pfctl -a f2b/$tjl -sr 2>/dev/null | grep -v f2b-$tjl | pfctl -a f2b/$tjl -f-
pfctl -a f2b/$tjl -t f2b-$tjl -T flush
pfctl -a f2b/$tjl -t f2b-$tjl -T kill

# ==================================================
# == all-ports - pf                               ==
# ==================================================
# === start === =====
echo "table <f2b-$tjl> persist counters" | pfctl -a f2b/$tjl -f-
port="<port>"; if [ "$port" != "" ] && case "$port" in \{*) false;; esac; then port="{$port}"; fi
echo "block quick proto tcp from <f2b-$tjl> to any" | pfctl -a f2b/$tjl -f-
# === ban-ipv4 === =====
pfctl -a f2b/$tjl -sr | grep -q f2b-$tjl
pfctl -a f2b/$tjl -t f2b-$tjl -T add 192.0.2.1
# === flush === =====
pfctl -a f2b/$tjl -t f2b-$tjl -T flush
# === stop === =====
pfctl -a f2b/$tjl -sr 2>/dev/null | grep -v f2b-$tjl | pfctl -a f2b/$tjl -f-
pfctl -a f2b/$tjl -t f2b-$tjl -T flush
pfctl -a f2b/$tjl -t f2b-$tjl -T kill
```

**Comment by dlangille** [comment]
```
$ fail2ban-client -d | grep -E 'wordpress-xmlrpc.*action'
['set', 'wordpress-xmlrpc', 'addaction', 'pf']
['multi-set', 'wordpress-xmlrpc', 'action', 'pf', [['actionunban', '/sbin/pfctl -t f2b -T delete <ip>/24'], ['actionflush', 'pfctl -a f2b/wordpress-xmlrpc -t f2b-wordpress-xmlrpc -T flush'], ['actionstart_on_demand', False], ['actionstop', ''], ['actionstart', ''], ['actionban', '/sbin/pfctl -t f2b -T add    <ip>/24'], ['actioncheck', ''], ['protocol', 'tcp'], ['name', 'wordpress-xmlrpc'], ['multiport', 'any port $port'], ['tablename', 'f2b'], ['actiontype', '<multiport>'], ['allports', 'any'], ['actname', 'pf'], ['block', 'block quick']]]
$ 

```

**Comment by dlangille** [comment]
Yes, I am quite sure I am not manipulating the tables.  Here is the other test:

```
# # test jail name (resulting to pf table names):
# tjl="wordpress-xmlrpc"
# 
# # ==================================================
# # == multi-port - pf                              ==
# # ==================================================
# # === start === =====
# echo "table <f2b-$tjl> persist counters" | pfctl -a f2b/$tjl -f-
# port="http,https"; if [ "$port" != "" ] && case "$port" in \{*) false;; esac; then port="{$port}"; fi
# echo "block quick proto tcp from <f2b-$tjl> to any port $port" | pfctl -a f2b/$tjl -f-
# # === ban-ipv4 === =====
# pfctl -a f2b/$tjl -sr | grep -q f2b-$tjl
# pfctl -a f2b/$tjl -t f2b-$tjl -T add 192.0.2.1
1/1 addresses added.
# # === flush === =====
# pfctl -a f2b/$tjl -t f2b-$tjl -T flush
1 addresses deleted.
# # === stop === =====
# pfctl -a f2b/$tjl -sr 2>/dev/null | grep -v f2b-$tjl | pfctl -a f2b/$tjl -f-
# pfctl -a f2b/$tjl -t f2b-$tjl -T flush
0 addresses deleted.
# pfctl -a f2b/$tjl -t f2b-$tjl -T kill
1 table deleted.
# # ==================================================
# # == all-ports - pf                               ==
# # ==================================================
# # === start === =====
# echo "table <f2b-$tjl> persist counters" | pfctl -a f2b/$tjl -f-
# port="<port>"; if [ "$port" != "" ] && case "$port" in \{*) false;; esac; then port="{$port}"; fi
# echo "block quick proto tcp from <f2b-$tjl> to any" | pfctl -a f2b/$tjl -f-
# # === ban-ipv4 === =====
# pfctl -a f2b/$tjl -sr | grep -q f2b-$tjl
# pfctl -a f2b/$tjl -t f2b-$tjl -T add 192.0.2.1
1/1 addresses added.
# # === flush === =====
# pfctl -a f2b/$tjl -t f2b-$tjl -T flush
1 addresses deleted.
# # === stop === =====
# pfctl -a f2b/$tjl -sr 2>/dev/null | grep -v f2b-$tjl | pfctl -a f2b/$tjl -f-
# pfctl -a f2b/$tjl -t f2b-$tjl -T flush
0 addresses deleted.
# pfctl -a f2b/$tjl -t f2b-$tjl -T kill
1 table deleted.
# 

```

**Comment by sebres** [comment]
Well your dump (config) looks totally weird:
```python
['multi-set', 'wordpress-xmlrpc', 'action', 'pf', [
  ['actionstart', ''], 
  ['actioncheck', ''], 
  ['actionban', '/sbin/pfctl -t f2b -T add    <ip>/24'], 
  ['actionunban', '/sbin/pfctl -t f2b -T delete <ip>/24'],
  ['actionflush', 'pfctl -a f2b/wordpress-xmlrpc -t f2b-wordpress-xmlrpc -T flush'],
  ['actionstop', ''], 
  ...
]
```
Although actionban, actionunban are specified, but looks as some custom entries (don't correspond original pf-action of fail2ban), only actionflush looks correct.
And actionstop and actionstart are empty at all. 

Normally you'd see all that entries provided as test above.
Your action configuration can not work properly. If you write your own action, why you still include original pf? Either reset/rewrite all expected `action*` parameters (e. g. set `actionflush` empty too), or just waive original action and write own (with own name like `mypf`).

Thus closed as 3rd party issue.
Please check your configuration (action/pf.conf, action/pf.local etc)...

**Comment by sebres** [comment]
By the way, I refine my answer to this question:

> Could this be related to missing actionstop entries in my ./action.d/pf.local file?

It looks like it is not missing but overwritten as empty:
```ini
actionstop =
```
