### ISSUE TITLE
maxretry-setting ignored

### ISSUE THREAD

**Issue by Tutmanichtun** [fail2ban/fail2ban#2536]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): v0.10.2
- OS, including release name/version: ubuntu 18.04.3
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [] Some customizations were done to the configuration (provide details below is so)

### The issue:

Fail2Ban ignores the maxretry-variable set in jail and uses a value of 3 (default in jail.conf is 5 instead).

I want to ban users which create filetypes on a samba-share which are not on a whitelist (e.g. place audio-files on a picture-share). Therefore i created a samba.conf in jail.d which bans on first attempt (maxretry=1).

#### Steps to reproduce

Rename a file on a share for four times. (Three times valid, fourth attempt fails.)

#### Expected behavior

I whould expect to get banned after the first try.

### Configuration, dump and another helpful excerpts

/etc/fail2ban/jail.d/samba.conf:
```
[samba]
filter = samba
enabled = true
action = iptables-multiport[name=samba, port="135,139,445,137,138", protocol=tcp]
         mail[name=samba, dest=admin@MYDOMAIN.DE]
logpath = /var/log/syslog
maxretry = 1    #Schon der erste Versuch ist strafbar
findtime = 600  #Schaut sich immer die letzen 10 Minuten an
bantime = 7200 #Ban für 2h
```

#### Relevant parts of /var/log/fail2ban.log file:
```
2019-10-03 15:45:07,170 fail2ban.filterpyinotify[28140]: DEBUG   Added file watcher for /var/log/syslog
2019-10-03 15:45:07,171 fail2ban.filter         [28140]: DEBUG   Seek to find time 1570109707.1654758 (2019-10-03 15:35:07), file size 207337835
2019-10-03 15:45:07,174 fail2ban.filter         [28140]: DEBUG   Position 207323128 from 207337835, found time 1570110303.0 (2019-10-03 15:45:03) within 1 seeks
2019-10-03 15:45:07,177 fail2ban.filter         [28140]: INFO      encoding: UTF-8
2019-10-03 15:45:07,180 fail2ban.transmitter    [28140]: WARNING Command ['set', 'samba', 'maxretry', 'None'] has failed. Received ValueError("invalid literal for int() with base 10: 'None'",)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/fail2ban/server/transmitter.py", line 57, in proceed
    ret = self.__commandHandler(command)
  File "/usr/lib/python3/dist-packages/fail2ban/server/transmitter.py", line 127, in __commandHandler
    return self.__commandSet(command[1:])
  File "/usr/lib/python3/dist-packages/fail2ban/server/transmitter.py", line 270, in __commandSet
    self.__server.setMaxRetry(name, int(value))
ValueError: invalid literal for int() with base 10: 'None'
2019-10-03 15:45:07,186 fail2ban                [28140]: ERROR   NOK: ("invalid literal for int() with base 10: 'None'",)
2019-10-03 15:45:07,190 fail2ban.filter         [28140]: INFO      findtime: 600
2019-10-03 15:45:07,193 fail2ban.actions        [28140]: INFO      banTime: 7200
2019-10-03 15:45:07,196 fail2ban.filter         [28140]: DEBUG   Setting usedns = warn for FilterPyinotify(Jail('samba'))
2019-10-03 15:45:07,200 fail2ban.CommandAction  [28140]: DEBUG   Created <class 'fail2ban.server.action.CommandAction'>
2019-10-03 15:45:07,202 fail2ban.CommandAction  [28140]: DEBUG     Set actionstart = '<iptables> -N f2b-samba\n<iptables> -A f2b-samba -j RETURN\n<iptables> -I INPUT -p tcp -m multiport --dports 135,139,445,137,138 -j f2b-samba'
2019-10-03 15:45:07,203 fail2ban.CommandAction  [28140]: DEBUG     Set actionstop = '<iptables> -D INPUT -p tcp -m multiport --dports 135,139,445,137,138 -j f2b-samba\n<iptables> -F f2b-samba\n<iptables> -X f2b-samba'
2019-10-03 15:45:07,203 fail2ban.CommandAction  [28140]: DEBUG     Set actionflush = '<iptables> -F f2b-samba'
2019-10-03 15:45:07,204 fail2ban.CommandAction  [28140]: DEBUG     Set actioncheck = "<iptables> -n -L INPUT | grep -q 'f2b-samba[ \\t]'"
2019-10-03 15:45:07,205 fail2ban.CommandAction  [28140]: DEBUG     Set actionban = '<iptables> -I f2b-samba 1 -s <ip> -j <blocktype>'
2019-10-03 15:45:07,205 fail2ban.CommandAction  [28140]: DEBUG     Set actionunban = '<iptables> -D f2b-samba -s <ip> -j <blocktype>'
2019-10-03 15:45:07,206 fail2ban.CommandAction  [28140]: DEBUG     Set name = 'samba'
2019-10-03 15:45:07,206 fail2ban.CommandAction  [28140]: DEBUG     Set port = '135,139,445,137,138'
2019-10-03 15:45:07,207 fail2ban.CommandAction  [28140]: DEBUG     Set protocol = 'tcp'
2019-10-03 15:45:07,207 fail2ban.CommandAction  [28140]: DEBUG     Set actname = 'iptables-multiport'
2019-10-03 15:45:07,208 fail2ban.CommandAction  [28140]: DEBUG     Set chain = 'INPUT'
2019-10-03 15:45:07,209 fail2ban.CommandAction  [28140]: DEBUG     Set blocktype = 'REJECT --reject-with icmp-port-unreachable'
2019-10-03 15:45:07,209 fail2ban.CommandAction  [28140]: DEBUG     Set returntype = 'RETURN'
2019-10-03 15:45:07,210 fail2ban.CommandAction  [28140]: DEBUG     Set lockingopt = '-w'
2019-10-03 15:45:07,210 fail2ban.CommandAction  [28140]: DEBUG     Set iptables = 'iptables <lockingopt>'
2019-10-03 15:45:07,211 fail2ban.CommandAction  [28140]: DEBUG     Set blocktype?family=inet6 = 'REJECT --reject-with icmp6-port-unreachable'
2019-10-03 15:45:07,211 fail2ban.CommandAction  [28140]: DEBUG     Set iptables?family=inet6 = 'ip6tables <lockingopt>'
2019-10-03 15:45:07,213 fail2ban.CommandAction  [28140]: DEBUG   Created <class 'fail2ban.server.action.CommandAction'>
2019-10-03 15:45:07,215 fail2ban.CommandAction  [28140]: DEBUG     Set actionstart = 'printf %b "Hi,\\n\nThe jail samba has been started successfully.\\n\nRegards,\\n\nFail2Ban"|mail -s "[Fail2Ban] samba: started  on <fq-hostname>" admin@MYDOMAIN.DE'
2019-10-03 15:45:07,216 fail2ban.CommandAction  [28140]: DEBUG     Set actionstop = 'printf %b "Hi,\\n\nThe jail samba has been stopped.\\n\nRegards,\\n\nFail2Ban"|mail -s "[Fail2Ban] samba: stopped on <fq-hostname>" admin@MYDOMAIN.DE'
2019-10-03 15:45:07,216 fail2ban.CommandAction  [28140]: DEBUG     Set actioncheck = ''
2019-10-03 15:45:07,217 fail2ban.CommandAction  [28140]: DEBUG     Set actionban = 'printf %b "Hi,\\n\nThe IP <ip> has just been banned by Fail2Ban after\n<failures> attempts against samba.\\n\nRegards,\\n\nFail2Ban"|mail -s "[Fail2Ban] samba: banned <ip> from <fq-hostname>" admin@MYDOMAIN.DE'
2019-10-03 15:45:07,217 fail2ban.CommandAction  [28140]: DEBUG     Set actionunban = ''
2019-10-03 15:45:07,218 fail2ban.CommandAction  [28140]: DEBUG     Set norestored = True
2019-10-03 15:45:07,218 fail2ban.CommandAction  [28140]: DEBUG     Set name = 'samba'
2019-10-03 15:45:07,219 fail2ban.CommandAction  [28140]: DEBUG     Set dest = 'admin@MYDOMAIN.DE'
2019-10-03 15:45:07,219 fail2ban.CommandAction  [28140]: DEBUG     Set actname = 'mail'
2019-10-03 15:45:07,221 fail2ban.jail           [28140]: DEBUG   Starting jail 'sshd'
2019-10-03 15:45:07,223 fail2ban.filterpyinotify[28140]: DEBUG   [sshd] filter started (pyinotifier)
2019-10-03 15:45:07,227 fail2ban.jail           [28140]: INFO    Jail 'sshd' started
2019-10-03 15:45:07,229 fail2ban.jail           [28140]: DEBUG   Starting jail 'samba'
2019-10-03 15:45:07,230 fail2ban.filterpyinotify[28140]: DEBUG   [samba] filter started (pyinotifier)
2019-10-03 15:45:07,235 fail2ban.jail           [28140]: INFO    Jail 'samba' started
2019-10-03 15:45:07,319 fail2ban.action         [28140]: DEBUG   printf %b "Hi,\n
The jail samba has been started successfully.\n
Regards,\n
Fail2Ban"|mail -s "[Fail2Ban] samba: started  on Server" admin@MYDOMAIN.DE
2019-10-03 15:45:08,858 fail2ban.utils          [28140]: DEBUG   7f4dd7bda440 -- returned successfully 0
2019-10-03 15:49:55,307 fail2ban.filter         [28140]: DEBUG   Processing line with time:1570110595.0 and ip:192.168.230.29
2019-10-03 15:49:55,322 fail2ban.filter         [28140]: INFO    [samba] Found 192.168.230.29 - 2019-10-03 15:49:55
2019-10-03 15:49:55,324 fail2ban.failmanager    [28140]: DEBUG   Total # of detected failures: 1. Current failures from 1 IPs (IP:count): 192.168.230.29:1
2019-10-03 15:49:58,607 fail2ban.filter         [28140]: DEBUG   Processing line with time:1570110598.0 and ip:192.168.230.29
2019-10-03 15:49:58,608 fail2ban.filter         [28140]: INFO    [samba] Found 192.168.230.29 - 2019-10-03 15:49:58
2019-10-03 15:49:58,609 fail2ban.failmanager    [28140]: DEBUG   Total # of detected failures: 2. Current failures from 1 IPs (IP:count): 192.168.230.29:2
2019-10-03 15:50:06,989 fail2ban.filter         [28140]: DEBUG   Processing line with time:1570110606.0 and ip:192.168.230.29
2019-10-03 15:50:06,990 fail2ban.filter         [28140]: INFO    [samba] Found 192.168.230.29 - 2019-10-03 15:50:06
2019-10-03 15:50:06,992 fail2ban.failmanager    [28140]: DEBUG   Total # of detected failures: 3. Current failures from 1 IPs (IP:count): 192.168.230.29:3
2019-10-03 15:50:07,725 fail2ban.actions        [28140]: NOTICE  [samba] Ban 192.168.230.29
2019-10-03 15:50:07,728 fail2ban.action         [28140]: DEBUG   iptables -w -N f2b-samba
iptables -w -A f2b-samba -j RETURN
iptables -w -I INPUT -p tcp -m multiport --dports 135,139,445,137,138 -j f2b-samba
2019-10-03 15:50:07,771 fail2ban.utils          [28140]: DEBUG   7f4dd76511b0 -- returned successfully 0
2019-10-03 15:50:07,774 fail2ban.action         [28140]: DEBUG   iptables -w -n -L INPUT | grep -q 'f2b-samba[ \t]'
2019-10-03 15:50:07,817 fail2ban.utils          [28140]: DEBUG   7f4dd764f718 -- returned successfully 0
2019-10-03 15:50:07,820 fail2ban.action         [28140]: DEBUG   iptables -w -I f2b-samba 1 -s 192.168.230.29 -j REJECT --reject-with icmp-port-unreachable
2019-10-03 15:50:07,866 fail2ban.utils          [28140]: DEBUG   7f4dd7bdb6f0 -- returned successfully 0
2019-10-03 15:50:07,870 fail2ban.action         [28140]: DEBUG   printf %b "Hi,\n
The IP 192.168.230.29 has just been banned by Fail2Ban after
3 attempts against samba.\n
Regards,\n
Fail2Ban"|mail -s "[Fail2Ban] samba: banned 192.168.230.29 from Server" admin@MYDOMAIN.DE
2019-10-03 15:50:09,428 fail2ban.utils          [28140]: DEBUG   7f4dd9854138 -- returned successfully 0
2019-10-03 15:50:09,429 fail2ban.actions        [28140]: DEBUG   Banned 1 / 1, 1 ticket(s) in 'samba'
```

Note: since i set loglevel = DEBUG, my log is flooded with this lines:
```
2019-10-03 15:45:07,237 fail2ban.filterpyinotify[28140]: DEBUG   Event queue size: 16
2019-10-03 15:45:07,238 fail2ban.filterpyinotify[28140]: DEBUG   <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
```

#### Relevant lines from monitored log files in question:
```
Oct  3 02:08:41 Server smbd_audit: IP=192.168.230.29|USER=gregor|MACHINE=vostro|VOLUME=Bilder|rename|ok|dsedidn.mp3|dsedsidn.mp3
Oct  3 02:08:45 Server smbd_audit: IP=192.168.230.29|USER=gregor|MACHINE=vostro|VOLUME=Bilder|rename|ok|dsedsidn.mp3|dsesdsidn.mp3
Oct  3 02:08:48 Server smbd_audit: IP=192.168.230.29|USER=gregor|MACHINE=vostro|VOLUME=Bilder|rename|ok|dsesdsidn.mp3|dsesdssidn.mp3
Oct  3 15:49:55 Server smbd_audit: IP=192.168.230.29|USER=gregor|MACHINE=vostro|VOLUME=Bilder|rename|ok|dsesdssidn.mp3|dsesddssidn.mp3
Oct  3 15:49:58 Server smbd_audit: IP=192.168.230.29|USER=gregor|MACHINE=vostro|VOLUME=Bilder|rename|ok|dsesddssidn.mp3|dsesdddssidn.mp3
Oct  3 15:50:06 Server smbd_audit: IP=192.168.230.29|USER=gregor|MACHINE=vostro|VOLUME=Bilder|rename|ok|dsesdddssidn.mp3|dsesddddssidn.mp3
```

**Comment by sebres** [comment]
> `maxretry = 1    #Schon der erste Versuch ist strafbar`
> maxretry-setting ignored

This is not ignored, but failed to set, see error message `invalid literal for int() with base 10` in log.
Fail2ban (as per default also python's) ini-configs accepting `#` and `;` as comment-prefixes only, this means comment string should start with this chars (white-spaces allowed), so just rewrite your inline comments to something like here:
```diff
-maxretry = 1    #Schon der erste Versuch ist strafbar
+#Schon der erste Versuch ist strafbar
+maxretry = 1
```
