### ISSUE TITLE
testStartForeground test failures with 0.11.1

### ISSUE THREAD

**Issue by opoplawski** [fail2ban/fail2ban#2597]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.11.1
- OS, including release name/version: Fedora Rawhide

### The issue:

Investigating updating the Fedora package to 0.11.1.  In addition to the test failures seen with 0.10.5 I see:
```
FAIL: testStartForeground (fail2ban.tests.fail2banclienttestcase.Fail2banClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/utils.py", line 243, in wrapper
    return f(self, tmp, *args, **kwargs)
  File "./fail2ban/tests/fail2banclienttestcase.py", line 367, in wrapper
    return f(self, tmp, startparams, *args, **kwargs)
  File "./fail2ban/tests/fail2banclienttestcase.py", line 479, in testStartForeground
    self.assertLogged("{'stacksize': 32}")
  File "./fail2ban/tests/utils.py", line 810, in assertLogged
    self.fail("None among %r was found in the log%s: ===\n%s===" % (s,
AssertionError: None among ("{'stacksize': 32}",) was found in the log: ===
������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������Using start params ('-c', '/tmp/f2b-tempzf5cucw4/config', '-s', '/tmp/f2b-tempzf5cucw4/f2b.sock', '-p', '/tmp/f2b-tempzf5cucw4/f2b.pid', '--logtarget', 'INHERITED', '--loglevel', 'INFO', '--syslogsocket', 'auto', '--timeout', '59', 'get', 'thread')
  conf: {'async': False, 'conf': '/tmp/f2b-tempzf5cucw4/config', 'force': False, 'background': True, 'verbose': 1, 'socket': '/tmp/f2b-tempzf5cucw4/f2b.sock', 'pidfile': '/tmp/f2b-tempzf5cucw4/f2b.pid', 'timeout': 59, 'logtarget': 'INHERITED', 'loglevel': 'INFO', 'syslogsocket': 'auto'}, args: ('get', 'thread')
Using socket file /tmp/f2b-tempzf5cucw4/f2b.sock
Using pid file /tmp/f2b-tempzf5cucw4/f2b.pid, [INFO] logging to INHERITED
{'stacksize': 0}
Exit with code 0
===
======================================================================
FAIL: testStartForeground (fail2ban.tests.fail2banclienttestcase.Fail2banServerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/utils.py", line 243, in wrapper
    return f(self, tmp, *args, **kwargs)
  File "./fail2ban/tests/fail2banclienttestcase.py", line 367, in wrapper
    return f(self, tmp, startparams, *args, **kwargs)
  File "./fail2ban/tests/fail2banclienttestcase.py", line 479, in testStartForeground
    self.assertLogged("{'stacksize': 32}")
  File "./fail2ban/tests/utils.py", line 810, in assertLogged
    self.fail("None among %r was found in the log%s: ===\n%s===" % (s,
AssertionError: None among ("{'stacksize': 32}",) was found in the log: ===
�����������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������Using start params ('-c', '/tmp/f2b-tempcwg3npfl/config', '-s', '/tmp/f2b-tempcwg3npfl/f2b.sock', '-p', '/tmp/f2b-tempcwg3npfl/f2b.pid', '--logtarget', 'INHERITED', '--loglevel', 'INFO', '--syslogsocket', 'auto', '--timeout', '59', 'get', 'thread')
  conf: {'async': False, 'conf': '/tmp/f2b-tempcwg3npfl/config', 'force': False, 'background': True, 'verbose': 1, 'socket': '/tmp/f2b-tempcwg3npfl/f2b.sock', 'pidfile': '/tmp/f2b-tempcwg3npfl/f2b.pid', 'timeout': 59, 'logtarget': 'INHERITED', 'loglevel': 'INFO', 'syslogsocket': 'auto'}, args: ('get', 'thread')
Using socket file /tmp/f2b-tempcwg3npfl/f2b.sock
Using pid file /tmp/f2b-tempcwg3npfl/f2b.pid, [INFO] logging to INHERITED
{'stacksize': 0}
Exit with code 0
```
[build.log](https://github.com/fail2ban/fail2ban/files/4050062/build.log)

**Comment by opoplawski** [comment]
I should note that these also only appear in the koji build, no a local one.  So something is different about the two environments.

**Comment by sebres** [comment]
Well the issue is obvious - it is searching for `{'stacksize': 32}`. but logged was `{'stacksize': 0}`.
The tests set thread stacksize to 32 and get it again to cover set/get for this new parameters.
I don't know what is different in koji build, but what would you see running that:
```
python -c 'import threading; threading.stack_size(32*1024); print(threading.stack_size() // 1024)'
```
Is it 32 or 0?
Or could you tell me some constraint (how can we recognize koji build) to skip this test?

**Comment by opoplawski** [comment]
```
python3 -c 'import threading; threading.stack_size(32*1024); print(threading.stack_size() // 1024)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: size not valid: 32768 bytes
```

**Comment by opoplawski** [comment]
This particular build was on a aarch64 builder.

**Comment by opoplawski** [comment]
I think aarch64 may have a minimum stack size of 64K.

**Comment by sebres** [comment]
Thx, Orion!
I hope test is fixed now.
