### ISSUE TITLE
Error when fail2ban attempts to ban an ip

### ISSUE THREAD

**Issue by marianoo-andres** [fail2ban/fail2ban#2720]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): v0.10.5
- OS, including release name/version: CentOS Linux release 7.6.1810 (Core)
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

I've seen in fail2ban logs that an ERROR occurs when fail2ban attempts to ban an IP. Fortunately, the IP gets banned anyway, but I'm not sure if it'd bring any future problem to let this error continue to happen.

#### Any additional information
Using firewalld as firewall.

#### Any customizations done to /etc/fail2ban/ configuration
Overrided params on /etc/fail2ban/jail.local:
```
backend = systemd
banaction = firewallcmd-ipset
banaction_allports = firewallcmd-ipset
```

Also have a sshd.local file /etc/fail2ban/jail.d/sshd.local:
```
enabled = true
port = ssh
logpath = %(sshd_log)s
maxretry = 5
bantime = 100years
findtime = 600
```

#### Relevant parts of /var/log/fail2ban.log file:
```
2020-05-13 16:39:55,983 fail2ban.filter         [23658]: DEBUG   Processing line with time:1589384395.98 and ip:222.186.15.10
2020-05-13 16:39:55,984 fail2ban.filter         [23658]: INFO    [sshd] Found 222.186.15.10 - 2020-05-13 16:39:55
2020-05-13 16:39:55,984 fail2ban.failmanager    [23658]: DEBUG   Total # of detected failures: 313. Current failures from 23 IPs (IP:count): 180.167.240.222:1, 187.86.200.18:4, 200.45.147.129:2, 62.234.182.174:1, 122.51.86.234:3, 106.54.141.65:2, 173.249.43.21:2, 51.104.40.179:4, 43.224.130.146:4, 159.65.59.41:3, 188.254.0.197:2, 58.65.191.124:2, 23.101.23.82:4, 107.175.33.240:1, 49.88.112.75:1, 122.51.98.36:2, 51.255.168.254:2, 192.241.135.34:1, 222.186.30.218:4, 120.72.106.106:2, 40.73.77.191:4, 221.140.86.142:2, 222.186.15.10:1
2020-05-13 16:39:57,980 fail2ban.filter         [23658]: DEBUG   Processing line with time:1589384397.98 and ip:222.186.15.10
2020-05-13 16:39:57,981 fail2ban.filter         [23658]: INFO    [sshd] Found 222.186.15.10 - 2020-05-13 16:39:57
2020-05-13 16:39:57,981 fail2ban.failmanager    [23658]: DEBUG   Total # of detected failures: 314. Current failures from 23 IPs (IP:count): 180.167.240.222:1, 187.86.200.18:4, 200.45.147.129:2, 62.234.182.174:1, 122.51.86.234:3, 106.54.141.65:2, 173.249.43.21:2, 51.104.40.179:4, 43.224.130.146:4, 159.65.59.41:3, 188.254.0.197:2, 58.65.191.124:2, 23.101.23.82:4, 107.175.33.240:1, 49.88.112.75:1, 122.51.98.36:2, 51.255.168.254:2, 192.241.135.34:1, 222.186.30.218:4, 120.72.106.106:2, 40.73.77.191:4, 221.140.86.142:2, 222.186.15.10:2
2020-05-13 16:40:00,726 fail2ban.filter         [23658]: DEBUG   Processing line with time:1589384400.72 and ip:222.186.15.10
2020-05-13 16:40:00,726 fail2ban.filter         [23658]: INFO    [sshd] Found 222.186.15.10 - 2020-05-13 16:40:00
2020-05-13 16:40:00,727 fail2ban.failmanager    [23658]: DEBUG   Total # of detected failures: 315. Current failures from 23 IPs (IP:count): 180.167.240.222:1, 187.86.200.18:4, 200.45.147.129:2, 62.234.182.174:1, 122.51.86.234:3, 106.54.141.65:2, 173.249.43.21:2, 51.104.40.179:4, 43.224.130.146:4, 159.65.59.41:3, 188.254.0.197:2, 58.65.191.124:2, 23.101.23.82:4, 107.175.33.240:1, 49.88.112.75:1, 122.51.98.36:2, 51.255.168.254:2, 192.241.135.34:1, 222.186.30.218:4, 120.72.106.106:2, 40.73.77.191:4, 221.140.86.142:2, 222.186.15.10:3
2020-05-13 16:40:11,317 fail2ban.filter         [23658]: DEBUG   Processing line with time:1589384411.32 and ip:222.186.15.10
2020-05-13 16:40:11,318 fail2ban.filter         [23658]: INFO    [sshd] Found 222.186.15.10 - 2020-05-13 16:40:11
2020-05-13 16:40:11,318 fail2ban.failmanager    [23658]: DEBUG   Total # of detected failures: 318. Current failures from 23 IPs (IP:count): 180.167.240.222:1, 187.86.200.18:2, 200.45.147.129:2, 62.234.182.174:1, 122.51.86.234:3, 106.54.141.65:2, 173.249.43.21:2, 51.104.40.179:4, 43.224.130.146:4, 159.65.59.41:3, 188.254.0.197:2, 58.65.191.124:2, 23.101.23.82:4, 107.175.33.240:1, 49.88.112.75:1, 122.51.98.36:2, 51.255.168.254:2, 192.241.135.34:1, 222.186.30.218:4, 120.72.106.106:2, 40.73.77.191:4, 221.140.86.142:2, 222.186.15.10:4
2020-05-13 16:40:14,433 fail2ban.filter         [23658]: DEBUG   Processing line with time:1589384414.43 and ip:222.186.15.10
2020-05-13 16:40:14,434 fail2ban.filter         [23658]: INFO    [sshd] Found 222.186.15.10 - 2020-05-13 16:40:14
2020-05-13 16:40:14,434 fail2ban.failmanager    [23658]: DEBUG   Total # of detected failures: 319. Current failures from 23 IPs (IP:count): 180.167.240.222:1, 187.86.200.18:2, 200.45.147.129:2, 62.234.182.174:1, 122.51.86.234:3, 106.54.141.65:2, 173.249.43.21:2, 51.104.40.179:4, 43.224.130.146:4, 159.65.59.41:3, 188.254.0.197:2, 58.65.191.124:2, 23.101.23.82:4, 107.175.33.240:1, 49.88.112.75:1, 122.51.98.36:2, 51.255.168.254:2, 192.241.135.34:1, 222.186.30.218:4, 120.72.106.106:2, 40.73.77.191:4, 221.140.86.142:2, 222.186.15.10:5
2020-05-13 16:40:14,517 fail2ban.actions        [23658]: NOTICE  [sshd] Ban 222.186.15.10
2020-05-13 16:40:14,518 fail2ban.action         [23658]: DEBUG   ipset create f2b-sshd hash:ip timeout 3155760000
firewall-cmd --direct --add-rule ipv4 filter INPUT_direct 0 -p tcp -m multiport --dports ssh -m set --match-set f2b-sshd src -j REJECT --reject-with icmp-port-unreachable
2020-05-13 16:40:14,734 fail2ban.utils          [23658]: ERROR   7f8d87ea7e30 -- exec: ipset create f2b-sshd hash:ip timeout 3155760000
firewall-cmd --direct --add-rule ipv4 filter INPUT_direct 0 -p tcp -m multiport --dports ssh -m set --match-set f2b-sshd src -j REJECT --reject-with icmp-port-unreachable
2020-05-13 16:40:14,734 fail2ban.utils          [23658]: ERROR   7f8d87ea7e30 -- stderr: "ipset v6.38: Syntax error: '3155760000' is out of range 0-4294967"
2020-05-13 16:40:14,735 fail2ban.utils          [23658]: ERROR   7f8d87ea7e30 -- stderr: "Error: COMMAND_FAILED: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore v1.4.21: Set f2b-sshd doesn't exist."
2020-05-13 16:40:14,735 fail2ban.utils          [23658]: ERROR   7f8d87ea7e30 -- stderr: ''
2020-05-13 16:40:14,735 fail2ban.utils          [23658]: ERROR   7f8d87ea7e30 -- stderr: 'Error occurred at line: 2'
2020-05-13 16:40:14,735 fail2ban.utils          [23658]: ERROR   7f8d87ea7e30 -- stderr: "Try `iptables-restore -h' or 'iptables-restore --help' for more information."
2020-05-13 16:40:14,735 fail2ban.utils          [23658]: ERROR   7f8d87ea7e30 -- stderr: ''
2020-05-13 16:40:14,735 fail2ban.utils          [23658]: ERROR   7f8d87ea7e30 -- returned 13
2020-05-13 16:40:14,735 fail2ban.actions        [23658]: ERROR   Failed to execute ban jail 'sshd' action 'firewallcmd-ipset' info 'ActionInfo({'ip': '222.186.15.10', 'fid': <function <lambda> at 0x7f8d87defa28>, 'family': 'inet4', 'raw-ticket': <function <lambda> at 0x7f8d87defed8>})': Error starting action Jail('sshd')/firewallcmd-ipset: 'Script error'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fail2ban/server/actions.py", line 458, in __checkBan
    action.ban(aInfo)
  File "/usr/lib/python2.7/site-packages/fail2ban/server/action.py", line 537, in ban
    self._start(family, forceStart=True)
  File "/usr/lib/python2.7/site-packages/fail2ban/server/action.py", line 518, in _start
    ret = self._executeOperation('<actionstart>', 'starting', family=family, afterExec=_started)
  File "/usr/lib/python2.7/site-packages/fail2ban/server/action.py", line 451, in _executeOperation
    raise RuntimeError("Error %s action %s/%s: %r" % (operation, self._jail, self._name, err))
RuntimeError: Error starting action Jail('sshd')/firewallcmd-ipset: 'Script error'
2020-05-13 16:40:14,735 fail2ban.actions        [23658]: DEBUG   Banned 1 / 38, 36 ticket(s) in 'sshd'
```

Any thoughts?
Thanks!

**Comment by sebres** [comment]
> bantime = 100years
> ipset v6.38: Syntax error: '3155760000' is out of range 0-4294967

I guess this is the main reason why it does not work for you. Max timout of ipset is 4294967 (seconds) that corresponds to 49 days.
Either you set the `bantime` to something smaller value (believe me 1 month is enough, and additionally would not bother your net-filter subsystem with too old IPs).
Or you should update your config (action `firewallcmd-ipset`) like in this patch - #2703.
So I'll close it now as fixed in newer version (don't hesitate to notice us if it does not help, so I'd reopen then).

**Comment by marianoo-andres** [comment]
I've changed bantime to 1month and I can confirm the issue stopped.

Thank you!
