### ISSUE TITLE
HINT on 127: "Command not found". - despite, the file actually exists and is executable

### ISSUE THREAD

**Issue by Roberto6969** [fail2ban/fail2ban#2781]
**### Environment:**

- Fail2Ban version: latest 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x ] You have not applied any additional foreign patches to the codebase
- [x ] Some customizations were done to the configuration (provide details below is so)

**### The issue:**

There is a file named fail2ban-telegram.sh in /data/scripts. I can execute script manually from command prompt. But when /data/action.d/telegram.conf call it, fail2ban.log says:
ERROR   b654c7b0 -- stderr: '/bin/sh: /home/pi/fail2ban/data/scripts/fail2ban-telegram.sh: not found' 

Due to this error jail also could not be started. I have tried different path but unsuccessfully.

**_Summary here_**

**#### Steps to reproduce**
from jail.local, jail sshd, call an action from /action.d/ (in my case is telegram.conf);  

File telegram.conf:
[Definition]
# Option:  actionstart
# Notes.:  command executed once at the start of Fail2Ban.
# Values:  CMD
#
actionstart = /home/pi/fail2ban/data/scripts/fail2ban-telegram.sh start

**#### Expected behavior**
scripts/fail2ban-telegram.sh (or any other script) should be executable if it is called by file from action.d

**#### Observed behavior**
'/bin/sh: /home/pi/fail2ban/data/scripts/fail2ban-telegram.sh: not found'

**#### Any additional information**
Otherwise, default action for sending mail works fine. If I add action = iptables-allports telegram, there is no telegram action neither mail any more.

**### Configuration, dump and another helpful excerpts**
[docker-compose.yml]
version: "3.2"

services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "./data:/data"
      - "/var/log:/var/log:rw"
    env_file:
      - "./fail2ban.env"
    restart: always

[fail2ban.env]
F2B_LOG_TARGET=/var/log/fail2ban.log
F2B_LOG_LEVEL=DEBUG
F2B_DB_PURGE_AGE=1d
F2B_IPTABLES_CHAIN=DOCKER-USER

**#### Any customizations done to /etc/fail2ban/ configuration**
fail2ban runs from docker image: https://github.com/crazy-max/docker-fail2ban  

**#### Relevant parts of /var/log/fail2ban.log file:**
2020-07-16 11:49:30,341 fail2ban.jail           [1]: DEBUG   Starting jail 'sshd'
2020-07-16 11:49:30,341 fail2ban.filterpyinotif [1]: DEBUG   [sshd] filter started (pyinotifier)
2020-07-16 11:49:30,348 fail2ban.jail           [1]: INFO    Jail 'sshd' started
2020-07-16 11:49:30,350 fail2ban.jail           [1]: DEBUG   Starting jail 'vsftpd'
2020-07-16 11:49:30,351 fail2ban.filterpyinotif [1]: DEBUG   [vsftpd] filter started (pyinotifier)
2020-07-16 11:49:30,353 fail2ban.utils          [1]: ERROR   b654c7b0 -- exec: /home/pi/fail2ban/data/scripts/fail2ban-telegram.sh start
2020-07-16 11:49:30,353 fail2ban.jail           [1]: INFO    Jail 'vsftpd' started
2020-07-16 11:49:30,353 fail2ban.jail           [1]: DEBUG   Starting jail 'sshd-ddos'
2020-07-16 11:49:30,354 fail2ban.utils          [1]: ERROR   b654c7b0 -- stderr: '/bin/sh: /home/pi/fail2ban/data/scripts/fail2ban-telegram.sh: not found'
2020-07-16 11:49:30,354 fail2ban.utils          [1]: ERROR   b654c7b0 -- returned 127
2020-07-16 11:49:30,354 fail2ban.utils          [1]: INFO    HINT on 127: "Command not found".  Make sure that all commands in '/home/pi/fail2ban/data/scripts/fail2ban-telegram.sh start' are in the PATH of fail2ban-serv$
2020-07-16 11:49:30,355 fail2ban.actions        [1]: ERROR   Failed to start jail 'sshd' action 'telegram': Error starting action Jail('sshd')/telegram: 'Script error'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/fail2ban/server/actions.py", line 319, in run
    action.start()
  File "/usr/lib/python3.8/site-packages/fail2ban/server/action.py", line 510, in start
    return self._start()
  File "/usr/lib/python3.8/site-packages/fail2ban/server/action.py", line 529, in _start
    ret = self._executeOperation('<actionstart>', 'starting', family=family, afterExec=_started)
  File "/usr/lib/python3.8/site-packages/fail2ban/server/action.py", line 462, in _executeOperation
    raise RuntimeError("Error %s action %s/%s: %r" % (operation, self._jail, self._name, err))
RuntimeError: Error starting action Jail('sshd')/telegram: 'Script error'

**#### Relevant lines from monitored log files in question:**

2020-07-16 11:49:30,354 fail2ban.utils          [1]: ERROR   b654c7b0 -- stderr: '/bin/sh: /home/pi/fail2ban/data/scripts/fail2ban-telegram.sh: not found'
2020-07-16 11:49:30,354 fail2ban.utils          [1]: ERROR   b654c7b0 -- returned 127
2020-07-16 11:49:30,354 fail2ban.utils          [1]: INFO    HINT on 127: "Command not found".  Make sure that all commands in '/home/pi/fail2ban/data/scripts/fail2ban-telegram.sh start' are in the PATH of fail2ban-serv$

**Comment by sebres** [comment]
Well the file `/home/pi/fail2ban/data/scripts/fail2ban-telegram.sh` is executed, otherwise I guess you've got something like:
```
Can't open /home/pi/fail2ban/data/scripts/fail2ban-telegram.sh
```
but it looks like some command in the script is not there, check that all commands can be found in PATH specified in your unit/service for fail2ban.
Note that service may have different PATH than your PATH in tty-shell where you may try this script.
So compare both outputs:
```bash
# path of f2b process:
pid_of_fail2ban=$(ps -ef | grep -m1 fail2ban | tr -s ' ' | cut -d ' ' -f2)
cat /proc/$pid_of_fail2ban/environ | tr '\0' '\n' | grep PATH
# path of shell process:
echo $PATH
```
