### ISSUE TITLE
Square Brackets in --datepattern crashes fail2ban-server

### ISSUE THREAD

**Issue by moon8orange** [fail2ban/fail2ban#2785]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): Fail2Ban v0.11.1
- OS, including release name/version: Fedora 32
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
If you add square brackets to the "--datepattern" option when testing with "fail2ban-regex"  you can crash the fail2ban-server

#### Steps to reproduce
add a date pattern like this:  
`--datepattern="^[%b %d %H:%M:%S]"`  

#### Expected behavior  
Honestly I was debugging log lines in order to see why it wasn't matching them. I wanted it to match the following line (spit out from a docker log):  
`[Jul 21 10:06:58] Connection closed by invalid user root 192.168.1.135 port 33384 [preauth]`

that line was a simplification of the actual docker log line:  
`Jul 21 10:06:58 nairn sftp-user[29049]: Connection from 192.168.0.82 port 33384 on 172.15.0.2 port 1023 rdomain ""`

So really I want it to match the longer version of the line. I've spent hours trying to figure this out.  

#### Observed behavior
fail2ban-server crashes and produces a typical python crash report (printed below).  

### Configuration, dump and another helpful excerpts
```
fail2ban-regex -v --datepattern="^[%b %d %H:%M:%S]" '[Jul 21 10:06:58] Connection closed by invalid user root 192.168.0.82 port 33384 [preauth]' 'Connection closed by invalid user root <HOST> port 33384 [preauth]'

Running tests
=============

Use      datepattern : ^[MON Day 24hour:Minute:Second]
Use   failregex line : Connection closed by invalid user root <HOST> port...
Use      single line : [Jul 21 10:06:58] Connection closed by invalid use...

Traceback (most recent call last):
  File "/usr/bin/fail2ban-regex", line 34, in <module>
    exec_command_line()
  File "/usr/lib/python3.8/site-packages/fail2ban/client/fail2banregex.py", line 762, in exec_command_line
    if not fail2banRegex.start(args):
  File "/usr/lib/python3.8/site-packages/fail2ban/client/fail2banregex.py", line 703, in start
    self.process(test_lines)
  File "/usr/lib/python3.8/site-packages/fail2ban/client/fail2banregex.py", line 507, in process
    line_datetimestripped, ret, is_ignored = self.testRegex(line)
  File "/usr/lib/python3.8/site-packages/fail2ban/client/fail2banregex.py", line 453, in testRegex
    found = self._filter.processLine(line, date)
  File "/usr/lib/python3.8/site-packages/fail2ban/server/filter.py", line 581, in processLine
    (timeMatch, template) = self.dateDetector.matchTime(l)
  File "/usr/lib/python3.8/site-packages/fail2ban/server/datedetector.py", line 392, in matchTime
    match = template.matchDate(line)
  File "/usr/lib/python3.8/site-packages/fail2ban/server/datetemplate.py", line 158, in matchDate
    self._compileRegex()
  File "/usr/lib/python3.8/site-packages/fail2ban/server/datetemplate.py", line 152, in _compileRegex
    raise e
  File "/usr/lib/python3.8/site-packages/fail2ban/server/datetemplate.py", line 149, in _compileRegex
    self._cRegex = re.compile(self.regex)
  File "/usr/lib64/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib64/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib64/python3.8/sre_parse.py", line 962, in parse
    raise source.error("unbalanced parenthesis")
re.error: unbalanced parenthesis at position 173
```

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
`datepattern` is a kind of regex (with % tokens substitution), you have to escape brackets, so rewrite it like:
```diff
-^[%b %d %H:%M:%S]
+^\[%b %d %H:%M:%S\]
