### ISSUE TITLE
Python 3.8.6 removed itemitrs() from dictionary.

### ISSUE THREAD

**Issue by egberts** [fail2ban/fail2ban#2844]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): master (commit 960e30cfcdae7e2c81f74046efdbff1606f9774e)
- OS, including release name/version: Linux arca 5.8.0-2-amd64 #1 SMP Debian 5.8.10-1 (2020-09-19) x86_64 GNU/Linux

- [ ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Python 3.8.1 removed itemiters() from dictionary.  As a result, `fail2ban-client` failed.
#### Steps to reproduce

```
# fresh install Debian Bullseye  11
git clone https://github.com/fail2ban/fail2ban.git
cd fail2ban
python3.8.6 ./setup.py install 
cp build/fail2ban.service /etc/systemd/system
systemctl daemon-reload
systemctl start fail2ban.service
fail2ban-client status
```

#### Expected behavior

No error during `fail2ban-client` due to Python obsoleted function uages.

#### Observed behavior

As a result, `fail2ban-client` failed with:
```console
$ fail2ban-client status
Traceback (most recent call last):
  File "/usr/local/bin/fail2ban-client", line 34, in <module>
    from fail2ban.client.fail2banclient import exec_command_line, sys
  File "/home/steve/work/github/fail2ban/fail2ban/client/fail2banclient.py", line 39, in <module>
    from ..server.utils import Utils
  File "/home/steve/work/github/fail2ban/fail2ban/server/utils.py", line 60, in <module>
    for name, num in signal.__dict__.iteritems() if name.startswith("SIG"))
AttributeError: 'dict' object has no attribute 'iteritems'
steve@arca:~/work/github/fail2ban$ python3.8
Python 3.8.6 (default, Sep 25 2020, 09:36:53) 
```

#### Any additional information

* https://stackoverflow.com/questions/30418481/error-dict-object-has-no-attribute-iteritems
*

**Comment by egberts** [comment]
Mmmmm, I  just  closed this, but  comment got lost.

My git repo  was  behind  0.2revs  worth of commit.

Invalid.

**Comment by egberts** [comment]
Also  a duplicate of #2845 due to my  local  power outage and  loss of  edit session.
