### ISSUE TITLE
failregex for exim message: 535 Incorrect authentication data

### ISSUE THREAD

**Issue by supp0rt2019** [fail2ban/fail2ban#2848]
Help create a rule for events:

```
`2020-10-05` 18:27:01 auth_login authenticator failed for (User) [212.70.149.5] I=[35.70.211.228]:25: 535 Incorrect authentication data (set_id=dostavka@giri.ru)

2020-10-05 18:27:12 auth_login authenticator failed for (User) [212.70.149.5] I=[95.119.1.3]:25: 535 Incorrect authentication data `(set_id=copia@giri.ru)`
```

there is already a rule:

```
failregex = \[<HOST>\] .*(?:rejected by local_scan|Unrouteable address)

\[<HOST>\] I=[[0-9.]+]:25: 535 Incorrect authentication data
```

but when checked it gives an error:

```
[root@gateway exim]# fail2ban-regex /var/log/exim/main.log /etc/fail2ban/filter.d/exim.conf

Running tests
=============

Use regex file : /etc/fail2ban/filter.d/exim.conf
Use log file   : /var/log/exim/main.log

Traceback (most recent call last):
  File "/usr/bin/fail2ban-regex", line 372, in ?
    fail2banRegex.testRegex(line)
  File "/usr/bin/fail2ban-regex", line 225, in testRegex
    ret = self.__filter.processLine(line)
  File "/usr/share/fail2ban/server/filter.py", line 243, in processLine
    timeMatch = self.dateDetector.matchTime(l)
  File "/usr/share/fail2ban/server/datedetector.py", line 114, in matchTime
    match = template.matchDate(line)
  File "/usr/share/fail2ban/server/datetemplate.py", line 58, in matchDate
    dateMatch = self.__cRegex.search(line)
KeyboardInterrupt
```

**Comment by sebres** [comment]
> \`2020-10-05\` ...
> ... \`(set_id=...)\`

What do mean with this apostrophes in your first and second example? are they just like an emphasis for you?
Well, if it is so, this messages (with removed \` chars) will be correct parsed with our default [exim filter](https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/exim.conf):
```
$ msg='2020-10-05 18:27:12 auth_login authenticator failed for (User) [192.0.2.1] I=[192.0.2.2]:25: 535 Incorrect authentication data (set_id=test@example.com)'
$ fail2ban-regex "$msg" exim

Running tests
=============

Use   failregex filter file : exim, basedir: /etc/fail2ban/
Use      single line : 2020-10-05 18:27:12 auth_login authenticator faile...


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   2) [1] ^(?: \[\d+\])? \w+ authenticator failed for (?:[^\[\( ]* )?(?:\(\S*\) )?\[<HOST>\](?::\d+)?(?: I=\[\S+\](:\d+)?)?: 535 Incorrect authentication data( \(set_id=.*\)|: \d+ Time\(s\))?\s*$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] {^LN-BEG}ExYear(?P<_sep>[-/.])Month(?P=_sep)Day(?:T|  ?)24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
```

> but when checked it gives an error:
> KeyboardInterrupt

As for the error with your RE - I don't really see that, KeyboardInterrupt indicating that you stopped execution (Ctrl+C, Ctrl+Break, etc).
Note that your regex is not anchored, moreover contain catch-all, so the search for the match can be very slow, because will try to find every part of RE is applicable on every message.
How long is your log-file (may be it's time to use logrotate)?
If it's very large, you can cut a part of log out and test your regex with this partial excerpt.

**Comment by supp0rt2019** [comment]
thanks for the hint, the problem was in a huge log
