### ISSUE TITLE
invalid literal for int() with base 10

### ISSUE THREAD

**Issue by Loki3000** [fail2ban/fail2ban#2849]
### Environment:

- Fail2Ban version  0.10.2
- OS, including release name/version: Ubuntu 18.04.5 LTS
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
Error in log file:
```
2020-10-06 13:21:21,462 fail2ban.jail           [1052]: INFO    Creating new jail 'nginx-botsearch'
2020-10-06 13:21:21,462 fail2ban.jail           [1052]: INFO    Jail 'nginx-botsearch' uses pyinotify {}
2020-10-06 13:21:21,462 fail2ban.filter         [1052]: DEBUG   Setting usedns = warn for FilterPyinotify(Jail('nginx-botsearch'))
2020-10-06 13:21:21,462 fail2ban.filter         [1052]: DEBUG   Created FilterPyinotify(Jail('nginx-botsearch'))
2020-10-06 13:21:21,465 fail2ban.filterpyinotify[1052]: DEBUG   Created FilterPyinotify
2020-10-06 13:21:21,465 fail2ban.jail           [1052]: INFO    Initiated 'pyinotify' backend
2020-10-06 13:21:21,466 fail2ban.transmitter    [1052]: WARNING Command ['set', 'nginx-botsearch', 'maxlines', 'None'] has failed. Received ValueError("invalid literal for int() with base 10: 'None'",)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/fail2ban/server/transmitter.py", line 57, in proceed
    ret = self.__commandHandler(command)
  File "/usr/lib/python3/dist-packages/fail2ban/server/transmitter.py", line 127, in __commandHandler
    return self.__commandSet(command[1:])
  File "/usr/lib/python3/dist-packages/fail2ban/server/transmitter.py", line 274, in __commandSet
    self.__server.setMaxLines(name, int(value))
ValueError: invalid literal for int() with base 10: 'None'
2020-10-06 13:21:21,466 fail2ban                [1052]: ERROR   NOK: ("invalid literal for int() with base 10: 'None'",)
2020-10-06 13:21:21,467 fail2ban.server         [1052]: DEBUG     prefregex: 'None'
2020-10-06 13:21:21,467 fail2ban.datetemplate   [1052]: DEBUG     constructed regex (?:^|\b|\W)(None)(?=\b|\W|$)
2020-10-06 13:21:21,468 fail2ban.datedetector   [1052]: INFO      date pattern `'None'`: `None`
```

Config of nginx-botsearch has no option 'maxlines' at all (jail.conf):
```
[nginx-botsearch]

port     = http,https
logpath  = %(nginx_error_log)s
maxretry = 2
```
fail2ban-client -d | grep 'nginx-botsearch' output:

```
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 'failregex' not defined in 'Definition'. Using default one: ''
 'failregex' not defined in 'Definition'. Using default one: ''
['add', 'nginx-botsearch', 'auto']
['set', 'nginx-botsearch', 'maxlines', None]
['set', 'nginx-botsearch', 'prefregex', None]
['set', 'nginx-botsearch', 'datepattern', None]
['set', 'nginx-botsearch', 'addlogpath', '/var/log/nginx/access.log', 'head']
['set', 'nginx-botsearch', 'logencoding', 'auto']
['set', 'nginx-botsearch', 'maxretry', 1]
['set', 'nginx-botsearch', 'findtime', '340']
['set', 'nginx-botsearch', 'bantime', '1440']
['set', 'nginx-botsearch', 'usedns', 'warn']
['set', 'nginx-botsearch', 'ignorecommand', '']
['set', 'nginx-botsearch', 'addignoreip', '127.0.0.0/8']
['set', 'nginx-botsearch', 'addignoreip', 'xxx.xxx.xxx.xxx']
['set', 'nginx-botsearch', 'addaction', 'iptables-allports']
['multi-set', 'nginx-botsearch', 'action', 'iptables-allports', [['actionstart', '<iptables> -N f2b-nginx-botsearch\n<iptables> -A f2b-nginx-botsearch -j RETURN\n<iptables> -I INPUT -p all -j f2b-nginx-botsearch'], ['actionstop', '<iptables> -D INPUT -p all -j f2b-nginx-botsearch\n<iptables> -F f2b-nginx-botsearch\n<iptables> -X f2b-nginx-botsearch'], ['actionflush', '<iptables> -F f2b-nginx-botsearch'], ['actioncheck', "<iptables> -n -L INPUT | grep -q 'f2b-nginx-botsearch[ \\t]'"], ['actionban', '<iptables> -I f2b-nginx-botsearch 1 -s <ip> -j <blocktype>'], ['actionunban', '<iptables> -D f2b-nginx-botsearch -s <ip> -j <blocktype>'], ['name', 'nginx-botsearch'], ['protocol', 'all'], ['actname', 'iptables-allports'], ['chain', 'INPUT'], ['port', 'ssh'], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['returntype', 'RETURN'], ['lockingopt', '-w'], ['iptables', 'iptables <lockingopt>'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['iptables?family=inet6', 'ip6tables <lockingopt>']]]
['start', 'nginx-botsearch']
```

If I add a parameter 'maxlines = 1' to nginx-botsearch config error still present and '['set', 'nginx-botsearch', 'maxlines', None]' in fail2ban-client  still the same.

**Comment by sebres** [comment]
This is a part of filter probably (per default filter is equal jail name in fail2ban), so check your `filter.d/nginx-botsearch.conf` (or .local)...
Neither in original [nginx-botsearch.conf](https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/nginx-botsearch.conf), nor in its include [botsearch-common.conf](https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/botsearch-common.conf) the value of `maxlines` is set, so normally they should be ignored and not supplied to the configuration stream.

I guess it could be indeed an error in your version (so try to add it into the filter as `maxlines = 1`).
I'll check whether it is affecting current versions too and will then fix that.

**Comment by Loki3000** [comment]
No, there is no "maxlines" in nginx-botsearch.conf or it's includes:
```
grep -R maxlines ./*
./filter.d/sshd.conf:maxlines = 1
./filter.d/guacamole.conf:# "maxlines" is number of log lines to buffer for multi-line regex searches
./filter.d/guacamole.conf:maxlines = 2
./filter.d/ejabberd-auth.conf:# "maxlines" is number of log lines to buffer for multi-line regex searches
./filter.d/ejabberd-auth.conf:maxlines = 2
./filter.d/mongodb-auth.conf:maxlines = 10
./filter.d/mongodb-auth.conf:# of this regex maxlines of 10 is quite generious.
./filter.d/slapd.conf:# "maxlines" is number of log lines to buffer for multi-line regex searches
./filter.d/slapd.conf:maxlines = 20
```

As I wrote in my first message I'm already tried to add ```maxlines = 1``` in config (in nginx-botsearch.conf and in jail.conf also) but with no luck.

**Comment by sebres** [comment]
What confusing me additionally are the `No section: 'Definition'` warnings in your output, can you generate the dump with increased verbosity and provide the output here? Interesting to see which files gets loaded thereby.
```
fail2ban-client -vvvd
```

**Comment by sebres** [comment]
> I'm already tried to add maxlines = 1 in config (in nginx-botsearch.conf and in jail.conf also) but with no luck

This is definitely not the case, since if you would add it to `Definition` section of `/etc/fail2ban/filter.d/nginx-botsearch.conf`, it would be 1 and not None.

I was also trying 0.10.2 version (without any modifications in filters, just enabled jail `nginx-botsearch`) and there is no `maxlines` at all in configuration dump, neither with `None` (nor with 1, which is default basically).

I guess some include file could cause that in your case.

**Comment by Loki3000** [comment]
>  can you generate the dump with increased verbosity

```
 +   86 7FBDE8CA0740 fail2ban.configreader     TRACE Non essential option 'norestored' not defined in 'Definition'.
 +   86 7FBDE8CA0740 fail2ban.configreader     INFO  Loading configs for filter.d/botsearch-common under /etc/fail2ban
 +   86 7FBDE8CA0740 fail2ban.configreader     DEBUG Reading configs for filter.d/botsearch-common under /etc/fail2ban
 +   87 7FBDE8CA0740 fail2ban.configreader     DEBUG Reading config files: /etc/fail2ban/filter.d/botsearch-common.conf
 +   87 7FBDE8CA0740 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/filter.d/botsearch-common.conf']
 +   87 7FBDE8CA0740 fail2ban.configparserinc  TRACE     Reading file: /etc/fail2ban/filter.d/botsearch-common.conf
 +   87 7FBDE8CA0740 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/filter.d/botsearch-common.conf']
 +   87 7FBDE8CA0740 fail2ban.configparserinc  TRACE     Shared file: /etc/fail2ban/filter.d/botsearch-common.conf
 +   87 7FBDE8CA0740 fail2ban.configreader     ERROR No section: 'Definition'
 +   87 7FBDE8CA0740 fail2ban.configreader     ERROR No section: 'Definition'
 +   87 7FBDE8CA0740 fail2ban.configreader     ERROR No section: 'Definition'
 +   88 7FBDE8CA0740 fail2ban.configreader     ERROR No section: 'Definition'
 +   88 7FBDE8CA0740 fail2ban.configreader     ERROR No section: 'Definition'
 +   88 7FBDE8CA0740 fail2ban.configreader     ERROR No section: 'Definition'
 +   88 7FBDE8CA0740 fail2ban.configreader     TRACE Non essential option 'logtimezone' not defined in 'nginx-botsearch'.
 +   88 7FBDE8CA0740 fail2ban.configreader     TRACE Non essential option 'failregex' not defined in 'nginx-botsearch'.
 +   88 7FBDE8CA0740 fail2ban.configreader     TRACE Non essential option 'ignoreregex' not defined in 'nginx-botsearch'.
 +   88 7FBDE8CA0740 fail2ban.configreader     TRACE Non essential option 'ignoreself' not defined in 'nginx-botsearch'.
 +   88 7FBDE8CA0740 fail2ban.configreader     TRACE Non essential option 'datepattern' not defined in 'nginx-botsearch'.
 +   88 7FBDE8CA0740 fail2ban.configreader     ERROR No section: 'Definition'
 +   89 7FBDE8CA0740 fail2ban.configreader     ERROR No section: 'Definition'
 +   89 7FBDE8CA0740 fail2ban.configreader     ERROR No section: 'Definition'
 +   89 7FBDE8CA0740 fail2ban.configreader     ERROR No section: 'Definition'
 +   89 7FBDE8CA0740 fail2ban.configreader     ERROR No section: 'Definition'
 +   89 7FBDE8CA0740 fail2ban.configreader     ERROR No section: 'Definition'
 +   89 7FBDE8CA0740 fail2ban.configreader     INFO  Loading configs for action.d/iptables-allports under /etc/fail2ban
 +   89 7FBDE8CA0740 fail2ban.configreader     DEBUG Reading configs for action.d/iptables-allports under /etc/fail2ban
 +   89 7FBDE8CA0740 fail2ban.configreader     DEBUG Reading config files: /etc/fail2ban/action.d/iptables-allports.conf
```



> This is definitely not the case, since if you would add it to `Definition` section of `/etc/fail2ban/filter.d/nginx-botsearch.conf`, it would be 1 and not None.

```
cat /etc/fail2ban/filter.d/nginx-botsearch.conf
# Fail2Ban filter to match web requests for selected URLs that don't exist
#

[INCLUDES]

# Load regexes for filtering
before = botsearch-common.conf

[Definition]

failregex = ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) \/<block> \S+\" 404 .+$
            ^ \[error\] \d+#\d+: \*\d+ (\S+ )?\"\S+\" (failed|is not found) \(2\: No such file or directory\), client\: <HOST>\, server\: \S*\, request: \"(GET|POST|HEAD) \/<block> \S+\"\, .*?$

ignoreregex =

datepattern = {^LN-BEG}%%ExY(?P<_sep>[-/.])%%m(?P=_sep)%%d[T ]%%H:%%M:%%S(?:[.,]%%f)?(?:\s*%%z)?
              ^[^\[]*\[({DATE})
              {^LN-BEG}

#added for test
maxlines = 1

# DEV Notes:
# Based on apache-botsearch filter
#
# Author: Frantisek Sumsal
```
then ```service fail2ban restart``` and
```
fail2ban-client -d | grep 'nginx-botsearch'
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 No section: 'Definition'
 'failregex' not defined in 'Definition'. Using default one: ''
 'failregex' not defined in 'Definition'. Using default one: ''
['add', 'nginx-botsearch', 'auto']
['set', 'nginx-botsearch', 'maxlines', None]
['set', 'nginx-botsearch', 'prefregex', None]
['set', 'nginx-botsearch', 'datepattern', None]
['set', 'nginx-botsearch', 'addlogpath', '/var/log/nginx/access.log', 'head']
['set', 'nginx-botsearch', 'logencoding', 'auto']
['set', 'nginx-botsearch', 'maxretry', 1]
['set', 'nginx-botsearch', 'findtime', '340']
['set', 'nginx-botsearch', 'bantime', '1440']
['set', 'nginx-botsearch', 'usedns', 'warn']
['set', 'nginx-botsearch', 'ignorecommand', '']
['set', 'nginx-botsearch', 'addignoreip', '127.0.0.0/8']
['set', 'nginx-botsearch', 'addignoreip', 'xxx.xxx.xxx.xxx']
['set', 'nginx-botsearch', 'addaction', 'iptables-allports']
['multi-set', 'nginx-botsearch', 'action', 'iptables-allports', [['actionstart', '<iptables> -N f2b-nginx-botsearch\n<iptables> -A f2b-nginx-botsearch -j RETURN\n<iptables> -I INPUT -p all -j f2b-nginx-botsearch'], ['actionstop', '<iptables> -D INPUT -p all -j f2b-nginx-botsearch\n<iptables> -F f2b-nginx-botsearch\n<iptables> -X f2b-nginx-botsearch'], ['actionflush', '<iptables> -F f2b-nginx-botsearch'], ['actioncheck', "<iptables> -n -L INPUT | grep -q 'f2b-nginx-botsearch[ \\t]'"], ['actionban', '<iptables> -I f2b-nginx-botsearch 1 -s <ip> -j <blocktype>'], ['actionunban', '<iptables> -D f2b-nginx-botsearch -s <ip> -j <blocktype>'], ['name', 'nginx-botsearch'], ['protocol', 'all'], ['actname', 'iptables-allports'], ['chain', 'INPUT'], ['port', 'ssh'], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['returntype', 'RETURN'], ['lockingopt', '-w'], ['iptables', 'iptables <lockingopt>'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['iptables?family=inet6', 'ip6tables <lockingopt>']]]
['start', 'nginx-botsearch']
```

> I guess some include file could cause that in your case.

I suppose that you are right, but how to detect this inclusion?

**Comment by sebres** [comment]
Hmm... this is really weird, and I'm unable to reproduce that...
<details><summary>Attempt to check that for 0.10.2 with nginx-botsearch jail enabled (click for details)...</summary>

```
/tmp/fail2ban-0.10.2$ printf "[nginx-botsearch]\nenabled = true\n" > ./config/jail.local
/tmp/fail2ban-0.10.2$ PYTHONPATH=. bin/fail2ban-client -c "$(pwd)/config/" -vvvd
 +   35 7FD226B435C0 fail2ban.configreader     INFO  Loading configs for fail2ban under /tmp/fail2ban-0.10.2/config
...
 +   36 7FD226B435C0 fail2ban.configreader     INFO  Loading configs for jail under /tmp/fail2ban-0.10.2/config
 +   36 7FD226B435C0 fail2ban.configreader     DEBUG Reading configs for jail under /tmp/fail2ban-0.10.2/config
 +   37 7FD226B435C0 fail2ban.configreader     DEBUG Reading config files: /tmp/fail2ban-0.10.2/config/jail.conf, /tmp/fail2ban-0.10.2/config/jail.local
 +   37 7FD226B435C0 fail2ban.configparserinc  INFO    Loading files: ['/tmp/fail2ban-0.10.2/config/jail.conf']
 +   37 7FD226B435C0 fail2ban.configparserinc  TRACE     Reading file: /tmp/fail2ban-0.10.2/config/jail.conf
 +   39 7FD226B435C0 fail2ban.configparserinc  INFO    Loading files: ['/tmp/fail2ban-0.10.2/config/paths-debian.conf']
 +   39 7FD226B435C0 fail2ban.configparserinc  TRACE     Reading file: /tmp/fail2ban-0.10.2/config/paths-debian.conf
 +   39 7FD226B435C0 fail2ban.configparserinc  INFO    Loading files: ['/tmp/fail2ban-0.10.2/config/paths-common.conf']
 +   39 7FD226B435C0 fail2ban.configparserinc  TRACE     Reading file: /tmp/fail2ban-0.10.2/config/paths-common.conf
 +   39 7FD226B435C0 fail2ban.configparserinc  INFO    Loading files: ['/tmp/fail2ban-0.10.2/config/paths-overrides.local']
 +   39 7FD226B435C0 fail2ban.configparserinc  TRACE     Reading file: /tmp/fail2ban-0.10.2/config/paths-overrides.local
 +   39 7FD226B435C0 fail2ban.configparserinc  INFO    Loading files: ['/tmp/fail2ban-0.10.2/config/jail.local']
 +   39 7FD226B435C0 fail2ban.configparserinc  TRACE     Reading file: /tmp/fail2ban-0.10.2/config/jail.local
 +   40 7FD226B435C0 fail2ban.configparserinc  INFO    Loading files: ['/tmp/fail2ban-0.10.2/config/paths-common.conf', '/tmp/fail2ban-0.10.2/config/paths-debian.conf', '/tmp/fail2ban-0.10.2/config/jail.conf', '/tmp/fail2ban-0.10.2/config/jail.local']
 +   40 7FD226B435C0 fail2ban.configparserinc  TRACE     Shared file: /tmp/fail2ban-0.10.2/config/paths-common.conf
 +   40 7FD226B435C0 fail2ban.configparserinc  TRACE     Shared file: /tmp/fail2ban-0.10.2/config/paths-debian.conf
 +   40 7FD226B435C0 fail2ban.configparserinc  TRACE     Shared file: /tmp/fail2ban-0.10.2/config/jail.conf
 +   41 7FD226B435C0 fail2ban.configparserinc  TRACE     Shared file: /tmp/fail2ban-0.10.2/config/jail.local
 +   42 7FD226B435C0 fail2ban.configreader     INFO  Loading configs for filter.d/nginx-botsearch under /tmp/fail2ban-0.10.2/config
 +   42 7FD226B435C0 fail2ban.configreader     DEBUG Reading configs for filter.d/nginx-botsearch under /tmp/fail2ban-0.10.2/config
 +   42 7FD226B435C0 fail2ban.configreader     DEBUG Reading config files: /tmp/fail2ban-0.10.2/config/filter.d/nginx-botsearch.conf
 +   42 7FD226B435C0 fail2ban.configparserinc  INFO    Loading files: ['/tmp/fail2ban-0.10.2/config/filter.d/nginx-botsearch.conf']
 +   42 7FD226B435C0 fail2ban.configparserinc  TRACE     Reading file: /tmp/fail2ban-0.10.2/config/filter.d/nginx-botsearch.conf
 +   42 7FD226B435C0 fail2ban.configparserinc  INFO    Loading files: ['/tmp/fail2ban-0.10.2/config/filter.d/botsearch-common.conf']
 +   42 7FD226B435C0 fail2ban.configparserinc  TRACE     Reading file: /tmp/fail2ban-0.10.2/config/filter.d/botsearch-common.conf
 +   42 7FD226B435C0 fail2ban.configparserinc  INFO    Loading files: ['/tmp/fail2ban-0.10.2/config/filter.d/botsearch-common.conf', '/tmp/fail2ban-0.10.2/config/filter.d/nginx-botsearch.conf']
 +   42 7FD226B435C0 fail2ban.configparserinc  TRACE     Shared file: /tmp/fail2ban-0.10.2/config/filter.d/botsearch-common.conf
 +   42 7FD226B435C0 fail2ban.configparserinc  TRACE     Shared file: /tmp/fail2ban-0.10.2/config/filter.d/nginx-botsearch.conf
 +   42 7FD226B435C0 fail2ban.configreader     TRACE Non essential option 'prefregex' not defined in 'Definition'.
 +   42 7FD226B435C0 fail2ban.configreader     TRACE Non essential option 'journalmatch' not defined in 'Definition'.
 +   42 7FD226B435C0 fail2ban.configreader     TRACE Non essential option 'maxlines' not defined in 'Definition'.
 +   43 7FD226B435C0 fail2ban.configreader     TRACE Non essential option 'logtimezone' not defined in 'nginx-botsearch'.
 +   43 7FD226B435C0 fail2ban.configreader     TRACE Non essential option 'failregex' not defined in 'nginx-botsearch'.
 +   43 7FD226B435C0 fail2ban.configreader     TRACE Non essential option 'ignoreregex' not defined in 'nginx-botsearch'.
 +   43 7FD226B435C0 fail2ban.configreader     TRACE Non essential option 'ignoreip' not defined in 'nginx-botsearch'.
 +   43 7FD226B435C0 fail2ban.configreader     TRACE Non essential option 'datepattern' not defined in 'nginx-botsearch'.
 +   44 7FD226B435C0 fail2ban.configreader     TRACE Non essential option 'prefregex' not defined in 'Definition'.
 +   44 7FD226B435C0 fail2ban.configreader     TRACE Non essential option 'journalmatch' not defined in 'Definition'.
 +   44 7FD226B435C0 fail2ban.configreader     TRACE Non essential option 'maxlines' not defined in 'Definition'.
 +   44 7FD226B435C0 fail2ban.configreader     INFO  Loading configs for action.d/iptables-multiport under /tmp/fail2ban-0.10.2/config
 +   44 7FD226B435C0 fail2ban.configreader     DEBUG Reading configs for action.d/iptables-multiport under /tmp/fail2ban-0.10.2/config
 +   44 7FD226B435C0 fail2ban.configreader     DEBUG Reading config files: /tmp/fail2ban-0.10.2/config/action.d/iptables-multiport.conf
 +   44 7FD226B435C0 fail2ban.configparserinc  INFO    Loading files: ['/tmp/fail2ban-0.10.2/config/action.d/iptables-multiport.conf']
 +   44 7FD226B435C0 fail2ban.configparserinc  TRACE     Reading file: /tmp/fail2ban-0.10.2/config/action.d/iptables-multiport.conf
 +   44 7FD226B435C0 fail2ban.configparserinc  INFO    Loading files: ['/tmp/fail2ban-0.10.2/config/action.d/iptables-common.conf']
 +   44 7FD226B435C0 fail2ban.configparserinc  TRACE     Reading file: /tmp/fail2ban-0.10.2/config/action.d/iptables-common.conf
 +   45 7FD226B435C0 fail2ban.configparserinc  INFO    Loading files: ['/tmp/fail2ban-0.10.2/config/action.d/iptables-blocktype.local']
 +   45 7FD226B435C0 fail2ban.configparserinc  TRACE     Reading file: /tmp/fail2ban-0.10.2/config/action.d/iptables-blocktype.local
 +   45 7FD226B435C0 fail2ban.configparserinc  INFO    Loading files: ['/tmp/fail2ban-0.10.2/config/action.d/iptables-common.local']
 +   45 7FD226B435C0 fail2ban.configparserinc  TRACE     Reading file: /tmp/fail2ban-0.10.2/config/action.d/iptables-common.local
 +   45 7FD226B435C0 fail2ban.configparserinc  INFO    Loading files: ['/tmp/fail2ban-0.10.2/config/action.d/iptables-common.conf', '/tmp/fail2ban-0.10.2/config/action.d/iptables-multiport.conf']
 +   45 7FD226B435C0 fail2ban.configparserinc  TRACE     Shared file: /tmp/fail2ban-0.10.2/config/action.d/iptables-common.conf
 +   45 7FD226B435C0 fail2ban.configparserinc  TRACE     Shared file: /tmp/fail2ban-0.10.2/config/action.d/iptables-multiport.conf
 +   45 7FD226B435C0 fail2ban.configreader     TRACE Non essential option 'actionstart_on_demand' not defined in 'Definition'.
 +   45 7FD226B435C0 fail2ban.configreader     TRACE Non essential option 'norestored' not defined in 'Definition'.
 +   45 7FD226B435C0 fail2ban.configreader     TRACE Non essential option 'actionrepair' not defined in 'Definition'.
 +   45 7FD226B435C0 fail2ban.configreader     TRACE Non essential option 'actionreload' not defined in 'Definition'.
['set', 'syslogsocket', 'auto']
['set', 'loglevel', 'DEBUG']
['set', 'logtarget', '/var/log/fail2ban.log']
['set', 'dbfile', '/var/lib/fail2ban/fail2ban.sqlite3']
['set', 'dbpurgeage', '50d']
['add', 'nginx-botsearch', 'pyinotify']
['multi-set', 'nginx-botsearch', 'addfailregex', ['^<HOST> \\- \\S+ \\[\\] \\"(GET|POST|HEAD) \\/\\/?(roundcube|(ext)?mail|horde|(v-?)?webmail|(typo3/|xampp/|admin/|)(pma|(php)?[Mm]y[Aa]dmin)|wp-(login|signup|admin)\\.php|cgi-bin|mysqladmin)[^,]* \\S+\\" 404 .+$', '^ \\[error\\] \\d+#\\d+: \\*\\d+ (\\S+ )?\\"\\S+\\" (failed|is not found) \\(2\\: No such file or directory\\), client\\: <HOST>\\, server\\: \\S*\\, request: \\"(GET|POST|HEAD) \\/\\/?(roundcube|(ext)?mail|horde|(v-?)?webmail|(typo3/|xampp/|admin/|)(pma|(php)?[Mm]y[Aa]dmin)|wp-(login|signup|admin)\\.php|cgi-bin|mysqladmin)[^,]* \\S+\\"\\, .*?$']]
['set', 'nginx-botsearch', 'datepattern', '{^LN-BEG}%ExY(?P<_sep>[-/.])%m(?P=_sep)%d[T ]%H:%M:%S(?:[.,]%f)?(?:\\s*%z)?\n^[^\\[]*\\[({DATE})\n{^LN-BEG}']
['set', 'nginx-botsearch', 'usedns', 'warn']
['set', 'nginx-botsearch', 'ignoreself', False]
['set', 'nginx-botsearch', 'addlogpath', '/var/log/nginx/error.log', 'head']
['set', 'nginx-botsearch', 'maxretry', 2]
['set', 'nginx-botsearch', 'logencoding', 'auto']
['set', 'nginx-botsearch', 'bantime', '10m']
['set', 'nginx-botsearch', 'ignorecommand', '']
['set', 'nginx-botsearch', 'findtime', '10m']
['set', 'nginx-botsearch', 'addaction', 'iptables-multiport']
['multi-set', 'nginx-botsearch', 'action', 'iptables-multiport', [['actionunban', '<iptables> -D f2b-nginx-botsearch -s <ip> -j <blocktype>'], ['actionflush', '<iptables> -F f2b-nginx-botsearch'], ['actionstop', '<iptables> -D INPUT -p tcp -m multiport --dports http,https -j f2b-nginx-botsearch\n<iptables> -F f2b-nginx-botsearch\n<iptables> -X f2b-nginx-botsearch'], ['actionstart', '<iptables> -N f2b-nginx-botsearch\n<iptables> -A f2b-nginx-botsearch -j RETURN\n<iptables> -I INPUT -p tcp -m multiport --dports http,https -j f2b-nginx-botsearch'], ['actionban', '<iptables> -I f2b-nginx-botsearch 1 -s <ip> -j <blocktype>'], ['actioncheck', "<iptables> -n -L INPUT | grep -q 'f2b-nginx-botsearch[ \\t]'"], ['protocol', 'tcp'], ['chain', '<known/chain>'], ['lockingopt', '-w'], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['port', 'http,https'], ['actname', 'iptables-multiport'], ['bantime', '10m'], ['iptables', 'iptables <lockingopt>'], ['returntype', 'RETURN'], ['iptables?family=inet6', 'ip6tables <lockingopt>'], ['name', 'nginx-botsearch']]]
['start', 'nginx-botsearch']
 +   48 7FD226B435C0 fail2ban                  DEBUG Exit with code 0
```
</details>

You can try it by yourself - download (or clone from git) 0.10.2 version and repeat my test from above.

Also comparing your excerpt I don't see loading of `filter.d/nginx-botsearch.conf` at all (only an include is loaded), but I guess your excerpt is too short (truncated from begin).

Maybe this is caused because it cannot be loaded properly (lot of errors by loading of `botsearch-common.conf`).
Although `botsearch-common.conf` indeed don't have `Definition` section, but it is optional in v.0.10 (only v.0.9 would miss that).
Or some other files causing that.

1. Which files do you see in `Loading files: [... nginx-botsearch.conf ...]`? Here is a normal case from above:
`Loading files: ['.../filter.d/botsearch-common.conf', '.../filter.d/nginx-botsearch.conf']`
2. which version do you see if you execute `fail2ban-client -V`?
3. Is there some version conflict possibly? Do you see some other `fail2ban-client` in your PATH? What would return `whereis fail2ban-client`? Multiple or single file?

**Comment by Loki3000** [comment]
I found!
```/etc/fail2ban/jail.d/custom.local```
```
...
[nginx-botsearch]
enabled =true
filter = botsearch-common #it's problem source
action = iptables-allports[name="nginx-botsearch", protocol="all"]
maxretry = 1
bantime  = 1440
logpath = /var/log/nginx/access.log
...
```
When I removed filter string - error is gone.
Thanks for you help!
