### ISSUE TITLE
[BR]: Compilation from git errors using Python3

### ISSUE THREAD

**Issue by iamdoubz** [fail2ban/fail2ban#2959]
### Environment:

- Fail2Ban version  : `fail2ban-client -V` Fail2Ban v1.0.1.dev1 [git rev 08393f9](https://github.com/fail2ban/fail2ban/commit/08393f9d82d4929ce3ee09bd9f3c685d38b2428d)
- OS, including release name/version : Ubuntu 20.04
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue(s):

- `AttributeError: 'dict' object has no attribute 'iteritems'`
- `ERROR: No module named 'ConfigParser'. Cannot start fail2ban.`

#### Steps to reproduce

Install from git:

```
git clone https://github.com/fail2ban/fail2ban.git
cd fail2ban
sudo python3 setup.py install
```

Then test install:

```
fail2ban-client -h
```

#### Expected behavior

Get help documentation.

#### Observed behavior

Two errors to first issue above in following files:

```
sudo nano +434 /usr/local/lib/python3.8/dist-packages/fail2ban/client/fail2banclient.py
sudo nano +60 /usr/local/lib/python3.8/dist-packages/fail2ban/server/utils.py
```

Changed these lines from _iteritems_ to _items_.

Once changed, remove existing files, "reinstall":

```
sudo rm -rf /etc/fail2ban /etc/init.d/fail2ban /var/run/fail2ban /usr/share/doc/fail2ban /usr/local/bin/fail2ban* /usr/lib*/python*/site-packages/fail2ban /usr/local/lib*/python*/site-packages/fail2ban
sudo python3 setup.py install
```

Once running `fail2ban-client -h` issue number 1 disappears.

#### Any additional information

When adding a basic addition to jail.local using command `fail2ban-client set JAIL addignoreip 192.168.1.1`, I get a new issue:

```
ERROR: No module named 'ConfigParser'
2021-03-05 13:46:44,191 fail2ban    [82654]: ERROR   Init of command line failed
```

Goggle search turns up that module is for Python2, and Python3 uses `configparser`.

When compiling a second time, I also received this error:

```
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/server/ipdns.py to ipdns.cpython-38.pyc
  File "/usr/local/lib/python3.8/dist-packages/fail2ban/server/ipdns.py", line 333
    mask = ~(0xFFFFFFFFL >> cidr)
                       ^
SyntaxError: invalid syntax
```

AND:

```
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/misctestcase.py to misctestcase.cpython-38.pyc
  File "/usr/local/lib/python3.8/dist-packages/fail2ban/tests/misctestcase.py", line 265
    print deep_function(3)
          ^
SyntaxError: invalid syntax

byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/filtertestcase.py to filtertestcase.cpython-38.pyc
  File "/usr/local/lib/python3.8/dist-packages/fail2ban/tests/filtertestcase.py", line 1647
    % m for m in 53, 54, 57, 58])
                   ^
SyntaxError: invalid syntax
```

However, fail2ban-client _does_ install properly.

#### Any customizations done to /etc/fail2ban/ configuration

```
NONE
```

#### Relevant parts of /var/log/fail2ban.log file:

```
Hasn't started yet.
```

#### Relevant lines from monitored log files:

```
Not relevant yet.
```

## Other

Thanks for the help in advance. I know it will be something really dumb I've overlooked.

**Comment by iamdoubz** [comment]
Running: `./fail2ban-2to3` results in:

```
./fail2ban-2to3: line 8: 2to3: command not found
Fail!
```

**Comment by iamdoubz** [comment]
Installed 2to3 using:

```
apt install 2to3 python3-lib2to3 python3-toolz
```

When running `./fail2ban-2to3` this error appears:

```
iamdoubz@computer:~/theGits/fail2ban$ ./fail2ban-2to3
RefactoringTool: Skipping optional fixer: buffer
RefactoringTool: Skipping optional fixer: idioms
RefactoringTool: Skipping optional fixer: set_literal
RefactoringTool: Skipping optional fixer: ws_comma
RefactoringTool: No changes to bin/fail2ban-client
Traceback (most recent call last):
  File "/usr/bin/2to3", line 5, in <module>
    sys.exit(main("lib2to3.fixes"))
  File "/usr/lib/python3.8/lib2to3/main.py", line 258, in main
    rt.refactor(args, options.write, options.doctests_only,
  File "/usr/lib/python3.8/lib2to3/refactor.py", line 686, in refactor
    return super(MultiprocessRefactoringTool, self).refactor(
  File "/usr/lib/python3.8/lib2to3/refactor.py", line 282, in refactor
    self.refactor_file(dir_or_file, write, doctests_only)
  File "/usr/lib/python3.8/lib2to3/refactor.py", line 727, in refactor_file
    return super(MultiprocessRefactoringTool, self).refactor_file(
  File "/usr/lib/python3.8/lib2to3/refactor.py", line 322, in refactor_file
    input, encoding = self._read_python_source(filename)
  File "/usr/lib/python3.8/lib2to3/refactor.py", line 318, in _read_python_source
    return f.read(), encoding
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 25: invalid start byte
Fail!
```

**Comment by iamdoubz** [comment]
Deleted everything.

Started over.

Ran `./fail2ban-2to3`.

Success.

**Comment by iamdoubz** [comment]
## Steps for future people like me:

1. Are you going to user python3?
    [x] Yes
    [ ] No
2. If yes, continue, else follow the README.
3. Install needed libraries for python2 to python3 conversion: i.e. `sudo apt install 2to3 python3-lib2to3 python3-toolz`
4. Clone the repo: `git clone https://github.com/fail2ban/fail2ban.git`
5. Change directory into the repo: `cd fail2ban`
6. Run python2 to python3 conversion script: `./fail2ban-2to3`
7. Output should be similar to below, as long as it outputs "Success!":
```
RefactoringTool: Skipping optional fixer: buffer
RefactoringTool: Skipping optional fixer: idioms
RefactoringTool: Skipping optional fixer: set_literal
RefactoringTool: Skipping optional fixer: ws_comma
RefactoringTool: No changes to bin/fail2ban-client
RefactoringTool: No changes to bin/fail2ban-regex
RefactoringTool: No changes to bin/fail2ban-server
RefactoringTool: No changes to bin/fail2ban-testcases
RefactoringTool: No changes to fail2ban/__init__.py
RefactoringTool: No changes to fail2ban/exceptions.py
RefactoringTool: Refactored fail2ban/helpers.py
RefactoringTool: No changes to fail2ban/protocol.py
RefactoringTool: No changes to fail2ban/setup.py
RefactoringTool: No changes to fail2ban/version.py
RefactoringTool: No changes to fail2ban/client/__init__.py
RefactoringTool: Refactored fail2ban/client/actionreader.py
RefactoringTool: No changes to fail2ban/client/beautifier.py
RefactoringTool: Refactored fail2ban/client/configparserinc.py
RefactoringTool: Refactored fail2ban/client/configreader.py
RefactoringTool: No changes to fail2ban/client/configurator.py
RefactoringTool: Refactored fail2ban/client/csocket.py
RefactoringTool: Refactored fail2ban/client/fail2banclient.py
RefactoringTool: No changes to fail2ban/client/fail2bancmdline.py
RefactoringTool: No changes to fail2ban/client/fail2banreader.py
RefactoringTool: Refactored fail2ban/client/fail2banregex.py
RefactoringTool: No changes to fail2ban/client/fail2banserver.py
RefactoringTool: Refactored fail2ban/client/filterreader.py
RefactoringTool: Refactored fail2ban/client/jailreader.py
RefactoringTool: No changes to fail2ban/client/jailsreader.py
RefactoringTool: No changes to fail2ban/server/__init__.py
RefactoringTool: Refactored fail2ban/server/action.py
RefactoringTool: Refactored fail2ban/server/actions.py
RefactoringTool: Refactored fail2ban/server/asyncserver.py
RefactoringTool: Refactored fail2ban/server/banmanager.py
RefactoringTool: Refactored fail2ban/server/database.py
RefactoringTool: No changes to fail2ban/server/datedetector.py
RefactoringTool: No changes to fail2ban/server/datetemplate.py
RefactoringTool: Refactored fail2ban/server/failmanager.py
RefactoringTool: Refactored fail2ban/server/failregex.py
RefactoringTool: Refactored fail2ban/server/filter.py
RefactoringTool: No changes to fail2ban/server/filtergamin.py
RefactoringTool: Refactored fail2ban/server/filterpoll.py
RefactoringTool: Refactored fail2ban/server/filterpyinotify.py
RefactoringTool: No changes to fail2ban/server/filtersystemd.py
RefactoringTool: Refactored fail2ban/server/ipdns.py
RefactoringTool: Refactored fail2ban/server/jail.py
RefactoringTool: No changes to fail2ban/server/jails.py
RefactoringTool: No changes to fail2ban/server/jailthread.py
RefactoringTool: Refactored fail2ban/server/mytime.py
RefactoringTool: No changes to fail2ban/server/observer.py
RefactoringTool: Refactored fail2ban/server/server.py
RefactoringTool: Refactored fail2ban/server/strptime.py
RefactoringTool: Refactored fail2ban/server/ticket.py
RefactoringTool: Refactored fail2ban/server/transmitter.py
RefactoringTool: Refactored fail2ban/server/utils.py
RefactoringTool: No changes to fail2ban/tests/__init__.py
RefactoringTool: No changes to fail2ban/tests/actionstestcase.py
RefactoringTool: Refactored fail2ban/tests/actiontestcase.py
RefactoringTool: Refactored fail2ban/tests/banmanagertestcase.py
RefactoringTool: No changes to fail2ban/tests/clientbeautifiertestcase.py
RefactoringTool: Refactored fail2ban/tests/clientreadertestcase.py
RefactoringTool: Refactored fail2ban/tests/databasetestcase.py
RefactoringTool: Refactored fail2ban/tests/datedetectortestcase.py
RefactoringTool: No changes to fail2ban/tests/dummyjail.py
RefactoringTool: Refactored fail2ban/tests/fail2banclienttestcase.py
RefactoringTool: No changes to fail2ban/tests/fail2banregextestcase.py
RefactoringTool: Refactored fail2ban/tests/failmanagertestcase.py
RefactoringTool: Refactored fail2ban/tests/filtertestcase.py
RefactoringTool: Refactored fail2ban/tests/misctestcase.py
RefactoringTool: Refactored fail2ban/tests/observertestcase.py
RefactoringTool: Refactored fail2ban/tests/samplestestcase.py
RefactoringTool: Refactored fail2ban/tests/servertestcase.py
RefactoringTool: Refactored fail2ban/tests/sockettestcase.py
RefactoringTool: No changes to fail2ban/tests/tickettestcase.py
RefactoringTool: Refactored fail2ban/tests/utils.py
RefactoringTool: No changes to fail2ban/tests/action_d/__init__.py
RefactoringTool: No changes to fail2ban/tests/action_d/test_smtp.py
RefactoringTool: No changes to fail2ban/tests/files/ignorecommand.py
RefactoringTool: No changes to fail2ban/tests/files/action.d/action.py
RefactoringTool: No changes to fail2ban/tests/files/action.d/action_checkainfo.py
RefactoringTool: No changes to fail2ban/tests/files/action.d/action_errors.py
RefactoringTool: No changes to fail2ban/tests/files/action.d/action_modifyainfo.py
RefactoringTool: Refactored fail2ban/tests/files/config/apache-auth/digest.py
RefactoringTool: Files that were modified:
RefactoringTool: bin/fail2ban-client
RefactoringTool: bin/fail2ban-regex
RefactoringTool: bin/fail2ban-server
RefactoringTool: bin/fail2ban-testcases
RefactoringTool: fail2ban/__init__.py
RefactoringTool: fail2ban/exceptions.py
RefactoringTool: fail2ban/helpers.py
RefactoringTool: fail2ban/protocol.py
RefactoringTool: fail2ban/setup.py
RefactoringTool: fail2ban/version.py
RefactoringTool: fail2ban/client/__init__.py
RefactoringTool: fail2ban/client/actionreader.py
RefactoringTool: fail2ban/client/beautifier.py
RefactoringTool: fail2ban/client/configparserinc.py
RefactoringTool: fail2ban/client/configreader.py
RefactoringTool: fail2ban/client/configurator.py
RefactoringTool: fail2ban/client/csocket.py
RefactoringTool: fail2ban/client/fail2banclient.py
RefactoringTool: fail2ban/client/fail2bancmdline.py
RefactoringTool: fail2ban/client/fail2banreader.py
RefactoringTool: fail2ban/client/fail2banregex.py
RefactoringTool: fail2ban/client/fail2banserver.py
RefactoringTool: fail2ban/client/filterreader.py
RefactoringTool: fail2ban/client/jailreader.py
RefactoringTool: fail2ban/client/jailsreader.py
RefactoringTool: fail2ban/server/__init__.py
RefactoringTool: fail2ban/server/action.py
RefactoringTool: fail2ban/server/actions.py
RefactoringTool: fail2ban/server/asyncserver.py
RefactoringTool: fail2ban/server/banmanager.py
RefactoringTool: fail2ban/server/database.py
RefactoringTool: fail2ban/server/datedetector.py
RefactoringTool: fail2ban/server/datetemplate.py
RefactoringTool: fail2ban/server/failmanager.py
RefactoringTool: fail2ban/server/failregex.py
RefactoringTool: fail2ban/server/filter.py
RefactoringTool: fail2ban/server/filtergamin.py
RefactoringTool: fail2ban/server/filterpoll.py
RefactoringTool: fail2ban/server/filterpyinotify.py
RefactoringTool: fail2ban/server/filtersystemd.py
RefactoringTool: fail2ban/server/ipdns.py
RefactoringTool: fail2ban/server/jail.py
RefactoringTool: fail2ban/server/jails.py
RefactoringTool: fail2ban/server/jailthread.py
RefactoringTool: fail2ban/server/mytime.py
RefactoringTool: fail2ban/server/observer.py
RefactoringTool: fail2ban/server/server.py
RefactoringTool: fail2ban/server/strptime.py
RefactoringTool: fail2ban/server/ticket.py
RefactoringTool: fail2ban/server/transmitter.py
RefactoringTool: fail2ban/server/utils.py
RefactoringTool: fail2ban/tests/__init__.py
RefactoringTool: fail2ban/tests/actionstestcase.py
RefactoringTool: fail2ban/tests/actiontestcase.py
RefactoringTool: fail2ban/tests/banmanagertestcase.py
RefactoringTool: fail2ban/tests/clientbeautifiertestcase.py
RefactoringTool: fail2ban/tests/clientreadertestcase.py
RefactoringTool: fail2ban/tests/databasetestcase.py
RefactoringTool: fail2ban/tests/datedetectortestcase.py
RefactoringTool: fail2ban/tests/dummyjail.py
RefactoringTool: fail2ban/tests/fail2banclienttestcase.py
RefactoringTool: fail2ban/tests/fail2banregextestcase.py
RefactoringTool: fail2ban/tests/failmanagertestcase.py
RefactoringTool: fail2ban/tests/filtertestcase.py
RefactoringTool: fail2ban/tests/misctestcase.py
RefactoringTool: fail2ban/tests/observertestcase.py
RefactoringTool: fail2ban/tests/samplestestcase.py
RefactoringTool: fail2ban/tests/servertestcase.py
RefactoringTool: fail2ban/tests/sockettestcase.py
RefactoringTool: fail2ban/tests/tickettestcase.py
RefactoringTool: fail2ban/tests/utils.py
RefactoringTool: fail2ban/tests/action_d/__init__.py
RefactoringTool: fail2ban/tests/action_d/test_smtp.py
RefactoringTool: fail2ban/tests/files/ignorecommand.py
RefactoringTool: fail2ban/tests/files/action.d/action.py
RefactoringTool: fail2ban/tests/files/action.d/action_checkainfo.py
RefactoringTool: fail2ban/tests/files/action.d/action_errors.py
RefactoringTool: fail2ban/tests/files/action.d/action_modifyainfo.py
RefactoringTool: fail2ban/tests/files/config/apache-auth/digest.py
Success!
```
8. Build fail2ban (optional): `python3 setup.py build`
9. Test a few things: `sudo ./fail2ban-testcases-all-python3`
10. Should run tests that look something like:
```
username@computer:~/theGits/fail2ban$ sudo ./fail2ban-testcases-all-python3
Testing using /usr/bin/python3.8
Fail2ban 1.0.1.dev1 test suite. Python 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]. Please wait...
.............................................2021-03-05 21:50:11,408 fail2ban.jail           [88936]: INFO    Creating new jail 'veryveryverylongname'
2021-03-05 21:50:11,408 fail2ban.jail           [88936]: INFO    Jail 'veryveryverylongname' uses pyinotify {}
2021-03-05 21:50:11,408 fail2ban.filter         [88936]: DEBUG   Setting usedns = warn for FilterPyinotify(Jail('veryveryverylongname'))
2021-03-05 21:50:11,408 fail2ban.filter         [88936]: DEBUG   Created FilterPyinotify(Jail('veryveryverylongname'))
2021-03-05 21:50:11,412 fail2ban.jail           [88936]: INFO    Initiated 'pyinotify' backend
.....................................................................................................s..........................................................................................................................................................................................................................................................................................
.....................................................................................
----------------------------------------------------------------------
Ran 514 tests in 16.215s

OK (skipped=1)
```
11. Install fail2ban: `sudo python3 setup.py install`
12. Keep reading the docs

Hope this helps someone.

PS I knew I would get it once I posted this... 🤦

**Comment by breisig** [comment]
This happened to me too.

**Comment by sebres** [comment]
FWIW, here is the detailed instruction how one can install fail2ban - https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually
