### ISSUE TITLE
Another fail2ban-regex Bug found?

### ISSUE THREAD

**Issue by cfwprpht** [fail2ban/fail2ban#3052]
Hello fail2ban Team,
for what it looks like, i stumbled around a script bug. I was on the way to secure the owncloud running on the apache2 server, with to configure a 404 ban. On the testing task python3 presentet me with a nice exception log. Since i am new to fail2ban and still getting familar with it, i thought to ask the pros about.

The apache-404.conf:
```
[apache-404]
failregex = ^<HOST> - .* "(GET|POST|HEAD).*HTTP.*" 404 .*$
ignoreregex =.*(robots.txt|favicon.ico|jpg|png)
```

The jail.local:
```
[apache-404]
enabled  = true
port     = http,https
filter   = apache-404
logpath  = /var/log/apache_404_error.log
logpath  = /var/log/apache_404_access.log
bantime  = 3600
findtime = 600
maxretry = 5
```

And last but not least, the error:
```
dstprpht@desasterpi:~ $ fail2ban-regex /var/log/apache_404_error.log /etc/fail2ban/filter.d/apache-404.conf

Running tests
=============

Use   failregex filter file : apache-404, basedir: /etc/fail2ban
Traceback (most recent call last):
  File "/usr/bin/fail2ban-regex", line 34, in <module>
    exec_command_line()
  File "/usr/lib/python3/dist-packages/fail2ban/client/fail2banregex.py", line 685, in exec_command_line
    if not fail2banRegex.start(args):
  File "/usr/lib/python3/dist-packages/fail2ban/client/fail2banregex.py", line 586, in start
    if not self.readRegex(cmd_regex, 'fail'): # pragma: no cover
  File "/usr/lib/python3/dist-packages/fail2ban/client/fail2banregex.py", line 368, in readRegex
    self.setMaxLines(optval)
  File "/usr/lib/python3/dist-packages/fail2ban/client/fail2banregex.py", line 275, in setMaxLines
    self._filter.setMaxLines(int(v))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Thank you in advanced. :)

**Comment by sebres** [comment]
The fail2ban filters must contain `Definition` section, so you've to rewrite `filter.d/apache-404.conf` like here:
```diff
-[apache-404]
+[Definition]
failregex = ...
```
BTW, your regex are extremely "vulnerable" (contains many catch-all's and/or aren't really anchored).
Better use something like that:
```ini
_ignore_uri = (?:robots\.txt|favicon\.ico|(?:[^/"]+\.(?:jpg|png)) )
failregex = ^<HOST> [^"]* "[A-Z]+ [^"]*/(?!%(_ignore_uri)s)[^/]* [^"]+" 404\b
```
(and `ignoreregex` is unneeded here, because it is a part of `failregex` implemented as a negative lookahead)
