### ISSUE TITLE
[BR]: test fail:python setup.py test fail

### ISSUE THREAD

**Issue by fubingting** [fail2ban/fail2ban#3072]
### Environment:
fail2ban version:master
commitid:10cd81552538fa950cefc32787b9f82b5ee1b998
os:centos8.4
platform:aarch64
python:2.7.18

 ### The issue:
 python test fail

#### Steps to reproduce
python setup.py test

### test log:

```
======================================================================
ERROR: test_move_into_file_after_removed (fail2ban.tests.filtertestcase.MonitorFailures<FilterPoll>(/tmp/monitorfailures_FilterPoll_aY6M3Ifail2ban))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/all_spack_env/spack_stage/root/spack-stage-py-fail2ban-master-ldpicpnqnr3jyh2yliascql6xxj32o34/spack-src/fail2ban/tests/filtertestcase.py", line 1266, in test_move_into_file_after_removed
    self._test_move_into_file(interim_kill=True)
  File "/home/all_spack_env/spack_stage/root/spack-stage-py-fail2ban-master-ldpicpnqnr3jyh2yliascql6xxj32o34/spack-src/fail2ban/tests/filtertestcase.py", line 1238, in _test_move_into_file
    _copy_lines_between_files(GetFailures.FILENAME_01, self.name).close()
  File "/home/all_spack_env/spack_stage/root/spack-stage-py-fail2ban-master-ldpicpnqnr3jyh2yliascql6xxj32o34/spack-src/fail2ban/tests/filtertestcase.py", line 226, in _copy_lines_between_files
    iDefLogSys.debug('  ++ write %d test lines', len(lines))
NameError: global name 'iDefLogSys' is not defined

======================================================================
ERROR: test_new_bogus_file (fail2ban.tests.filtertestcase.MonitorFailures<FilterPoll>(/tmp/monitorfailures_FilterPoll_aY6M3Ifail2ban))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/all_spack_env/spack_stage/root/spack-stage-py-fail2ban-master-ldpicpnqnr3jyh2yliascql6xxj32o34/spack-src/fail2ban/tests/filtertestcase.py", line 1270, in test_new_bogus_file
    _copy_lines_between_files(GetFailures.FILENAME_01, self.name, n=100).close()
  File "/home/all_spack_env/spack_stage/root/spack-stage-py-fail2ban-master-ldpicpnqnr3jyh2yliascql6xxj32o34/spack-src/fail2ban/tests/filtertestcase.py", line 226, in _copy_lines_between_files
    iDefLogSys.debug('  ++ write %d test lines', len(lines))
NameError: global name 'iDefLogSys' is not defined

======================================================================
ERROR: test_rewrite_file (fail2ban.tests.filtertestcase.MonitorFailures<FilterPoll>(/tmp/monitorfailures_FilterPoll_aY6M3Ifail2ban))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/all_spack_env/spack_stage/root/spack-stage-py-fail2ban-master-ldpicpnqnr3jyh2yliascql6xxj32o34/spack-src/fail2ban/tests/filtertestcase.py", line 1124, in test_rewrite_file
    _copy_lines_between_files(GetFailures.FILENAME_01, self.name).close()
  File "/home/all_spack_env/spack_stage/root/spack-stage-py-fail2ban-master-ldpicpnqnr3jyh2yliascql6xxj32o34/spack-src/fail2ban/tests/filtertestcase.py", line 226, in _copy_lines_between_files
    iDefLogSys.debug('  ++ write %d test lines', len(lines))
NameError: global name 'iDefLogSys' is not defined

======================================================================
FAIL: testFQDN (fail2ban.tests.filtertestcase.DNSUtilsNetworkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/all_spack_env/spack_stage/root/spack-stage-py-fail2ban-master-ldpicpnqnr3jyh2yliascql6xxj32o34/spack-src/fail2ban/tests/filtertestcase.py", line 2261, in testFQDN
    sname != 'localhost')
AssertionError: False != True

----------------------------------------------------------------------
Ran 495 tests in 31.672s

FAILED (failures=1, errors=12, skipped=5)
Test failed: <unittest.runner.TextTestResult run=495 errors=12 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=495 errors=12 failures=1>

```

### My host `/etc/hosts` contains

```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

**Comment by sebres** [comment]
Neither I can reproduce it for 10cd81552538fa950cefc32787b9f82b5ee1b998, nor this contains something related to your traceback:
```
iDefLogSys.debug('  ++ write %d test lines', len(lines))
```
https://github.com/fail2ban/fail2ban/blob/10cd81552538fa950cefc32787b9f82b5ee1b998/fail2ban/tests/filtertestcase.py#L226
for comparison as diff to your version:
```diff
-       iDefLogSys.debug('  ++ write %d test lines', len(lines))
+       DefLogSys.debug('  ++ write %d test lines', len(lines))
```
Something seemed to change the source code of your clone. Please use clean working copy.
