### ISSUE TITLE
blocklist.de causing an error 

### ISSUE THREAD

**Issue by androidloverbe** [fail2ban/fail2ban#3107]
Hello,

I'm trying to configure the blocklist.de reporting of attacks but i'm having an issue .It seems this feature is causing an error 

i opened /etc/fail2ban/fail2ban.conf and  set loglevel = DEBUG and then whenever a ban is triggerd i see this in /var/log/fail2banlog

```
2021-09-22 20:09:28,248 fail2ban.observer       [12629]: DEBUG   [sshd] Observer: ban found 2.42.11.15, 2419200
2021-09-22 20:09:28,263 fail2ban.utils          [12629]: DEBUG   7f3a68491a40 -- returned successfully 0
2021-09-22 20:09:28,273 fail2ban.utils          [12629]: DEBUG   7f3a6844ec00 -- returned successfully 0
2021-09-22 20:09:28,415 fail2ban.utils          [12629]: DEBUG   7f3a4c01e450 -- returned successfully 0
2021-09-22 20:09:28,735 fail2ban.utils          [12629]: DEBUG   7f3a684551c0 -- stdout: '{"data":{"ipAddress":"2.42.11.15","abuseConfidenceScore":54}}'
2021-09-22 20:09:28,736 fail2ban.utils          [12629]: DEBUG   7f3a684551c0 -- returned successfully 0
2021-09-22 20:09:29,212 fail2ban.utils          [12629]: ERROR   7f3a684597c0 -- exec: ['f2bV_matches=$0 \ncurl --fail --data-urlencode "server=email_here" --data "apikey=sniped" --data "service=sshd[mode=normal]" --data "ip=2.42.11.15" --data-urlencode "logs=$f2bV_matches\n" --data \'format=text\' --user-agent "Fail2Ban/0.11.2" "https://www.blocklist.de/en/httpreports.html"', 'Sep 22 20:09:27 localhost sshd[13793]: Invalid user pi from 2.42.11.15 port 34598\nSep 22 20:09:27 localhost sshd[13795]: Invalid user pi from 2.42.11.15 port 34602']
2021-09-22 20:09:29,213 fail2ban.utils          [12629]: ERROR   7f3a684597c0 -- stderr: '  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current'
2021-09-22 20:09:29,213 fail2ban.utils          [12629]: ERROR   7f3a684597c0 -- stderr: '                                 Dload  Upload   Total   Spent    Left  Speed'
2021-09-22 20:09:29,213 fail2ban.utils          [12629]: ERROR   7f3a684597c0 -- stderr: ''
2021-09-22 20:09:29,213 fail2ban.utils          [12629]: ERROR   7f3a684597c0 -- stderr: '  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0'
2021-09-22 20:09:29,213 fail2ban.utils          [12629]: ERROR   7f3a684597c0 -- stderr: '100   337    0     0  100   337      0    742 --:--:-- --:--:-- --:--:--   742'
2021-09-22 20:09:29,213 fail2ban.utils          [12629]: ERROR   7f3a684597c0 -- stderr: 'curl: (22) The requested URL returned error: 400 Bad Request'
2021-09-22 20:09:29,213 fail2ban.utils          [12629]: ERROR   7f3a684597c0 -- returned 22
2021-09-22 20:09:29,213 fail2ban.actions        [12629]: ERROR   Failed to execute ban jail 'sshd' action 'blocklist_de' info 'ActionInfo({'ip': '2.42.11.15', 'family': 'inet4', 'fid': <function Actions.ActionInfo.<lambda> at 0x7f3a68aa5dc0>, 'failures': 2, 'matches': 'Sep 22 20:09:27 localhost sshd[13793]: Invalid user pi from 2.42.11.15 port 34598\nSep 22 20:09:27 localhost sshd[13795]: Invalid user pi from 2.42.11.15 port 34602', 'F-*': {'matches': [('', 'Sep 22 20:09:27', ' localhost sshd[13793]: Invalid user pi from 2.42.11.15 port 34598'), 'Sep 22 20:09:27 localhost sshd[13795]: Invalid user pi from 2.42.11.15 port 34602'], 'failures': 2, 'mlfid': ' localhost sshd[13793]: ', 'user': 'pi', 'ip4': '2.42.11.15', 'users': {'pi'}}, 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x7f3a68aa64c0>})': Error banning 2.42.11.15
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/fail2ban/server/actions.py", line 510, in __checkBan
    action.ban(aInfo)
  File "/usr/lib/python3/dist-packages/fail2ban/server/action.py", line 565, in ban
    raise RuntimeError("Error banning %(ip)s" % aInfo)
```

it looks like the needed curl command is returning a 400 bad request error

Server os : Ubuntu Server 21.04

Fail2Ban/0.11.2

I have a feeling fail2ban is innocent here it is being caused by something i do the wrong way.

**Comment by sebres** [comment]
Same as in #2993
I can only say that you can find out how you'd supply it from shell and then we could adjust the action to match new interface (command line).
I don't use it, so cannot tell you how it is correct and what can we do.

**Comment by androidloverbe** [comment]
Hello,

Possible error cause it seems there is a minimum limit of the logs parameter (20 signs) i'm not sure what they mean by "signs" though i just increase the maxretry and see what happens.

**Comment by sebres** [comment]
Ok, then closing.
