### ISSUE TITLE
[BR]: Test failure with fail2ban 1.0.2 in EPEL7

### ISSUE THREAD

**Issue by opoplawski** [fail2ban/fail2ban#3490]
### Environment:

Building the Fedora fail2ban 1.0.2 package for EPEL7.  python-2.7.5-92.el7_9.x86_64

### The issue:

FAIL: testWrongRE (fail2ban.tests.fail2banregextestcase.Fail2banRegexTest)

#### Expected behavior
No failures.

#### Observed behavior
```
FAIL: testWrongRE (fail2ban.tests.fail2banregextestcase.Fail2banRegexTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/fail2banregextestcase.py", line 149, in testWrongRE
    self.assertLogged("unknown group name: 'typo'", "at position 23", all=False); # details of failed compilation
  File "./fail2ban/tests/utils.py", line 809, in assertLogged
    ((', waited %s' % wait) if wait else ''), logged))
AssertionError: None among ("unknown group name: 'typo'", 'at position 23') was found in the log: ===
Setting usedns = warn for Filter(None)
Created Filter(None)
output: Use   failregex line : ^(?:(?P<type>A)|B)? (?(typo)...) from <ADDR>
Unable to compile regular expression '^(?:(?P<type>A)|B)? (?(typo)...) from \[?(?:(?:::f{4,6}:)?(?P<ip4>(?:\d{1,3}\.){3}\d{1,3})|(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):)))\]?':
unknown group name
output: ERROR: Unable to compile regular expression '^(?:(?P<type>A)|B)? (?(typo)...) from \[?(?:(?:::f{4,6}:)?(?P<ip4>(?:\d{1,3}\.){3}\d{1,3})|(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):)))\]?':
unknown group name
===
```

**Comment by sebres** [comment]
Branch [gh-3490](https://github.com/fail2ban/fail2ban/tree/gh-3490) with commit 27294c4b9ee5d5568a1d5f83af744ea39d5a1acb must fix it now.
Can you confirm please? (I cannot reproduce it with my boxes with 2.x python).

**Comment by opoplawski** [comment]
That does the trick, thanks!
