### ISSUE TITLE
[BR]: Python 3.11 related fail when using auth/auth2 in postfix.conf

### ISSUE THREAD

**Issue by MeganerdNL** [fail2ban/fail2ban#3530]
### Environment:

- Fail2Ban version: 0.11.2
- Python version: 3.11.4
- OS, including release name/version : Void Linux
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase

### The issue:

When using modes in de **postfix.conf** file that are/use _auth or auth2_ fail2ban fails (see Observed Behaviour).

#### Steps to reproduce
Have Python 3.11 installed
Use a mode in the jail file that incorporates _auth/auth2_: for instance _aggressive_
```
[postfix]
enabled = true
mode    = aggressive
port    = smtp,465,submission
logpath = /var/log/socklog/mail/current
```
Or use postfix-sasl that uses _auth_ too:
```
[postfix-sasl]
enabled  = true
filter   = postfix[mode=auth]
port     = smtp,465,submission,imap,imaps,pop3,pop3s
logpath  = /var/log/socklog/mail/current
```

#### Expected behavior

It compiles. It does on my machine with **Python 3.9** with the exact same config and it works.

#### Observed behavior

Fail when doing postfix-client reload:

```
2023-06-18 10:44:33,319 fail2ban                [4385]: ERROR   NOK: ("Unable to compile regular expression '^[^[]*\\[(?:\\[?(?:(?:::f{4,6}:)?(?P<ip4>(?:\\d{1,3}\\.){3}\\d{1,3})|(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):)))\\]?|(?P<dns>[\\w\\-.^_]*\\w))\\](?::\\d+)?: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed:(?! Connection lost to authentication server)'",)
Unable to compile regular expression '^[^[]*\[(?:\[?(?:(?:::f{4,6}:)?(?P<ip4>(?:\d{1,3}\.){3}\d{1,3})|(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):)))\]?|(?P<dns>[\w\-.^_]*\w))\](?::\d+)?: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed:(?! Connection lost to authentication server)'
```

#### Any additional information

This is probably related to #3260 and/or #3314

### Configuration, dump and another helpful excerpts
jail.local:
```
[postfix]
enabled = true
mode    = aggressive
port    = smtp,465,submission
logpath = /var/log/socklog/mail/current
```
No postfix.local in filter.d and unmodified postfix.conf

#### Relevant parts of /var/log/fail2ban.log file:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/fail2ban/server/failregex.py", line 132, in __init__
    self._regexObj = re.compile(regex, re.MULTILINE if multiline else 0)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 863, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 178

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/fail2ban/server/transmitter.py", line 58, in proceed
    ret = self.__commandHandler(command)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fail2ban/server/transmitter.py", line 133, in __commandHandler
    self.__commandHandler(cmd)
  File "/usr/lib/python3.11/site-packages/fail2ban/server/transmitter.py", line 87, in __commandHandler
    return self.__commandSet(command[1:], True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fail2ban/server/transmitter.py", line 284, in __commandSet
    self.__server.addFailRegex(name, value, multiple=multiple)
  File "/usr/lib/python3.11/site-packages/fail2ban/server/server.py", line 460, in addFailRegex
    flt.addFailRegex(value)
  File "/usr/lib/python3.11/site-packages/fail2ban/server/filter.py", line 188, in addFailRegex
    raise e
  File "/usr/lib/python3.11/site-packages/fail2ban/server/filter.py", line 183, in addFailRegex
    regex = FailRegex(value, prefRegex=self.__prefRegex, multiline=multiLine,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fail2ban/server/failregex.py", line 416, in __init__
    Regex.__init__(self, regex, **kwargs)
  File "/usr/lib/python3.11/site-packages/fail2ban/server/failregex.py", line 149, in __init__
    raise RegexException("Unable to compile regular expression '%s'" %
fail2ban.server.failregex.RegexException: Unable to compile regular expression '^[^[]*\[(?:\[?(?:(?:::f{4,6}:)?(?P<ip4>(?:\d{1,3}\.){3}\d{1,3})|(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):)))\]?|(?P<dns>[\w\-.^_]*\w))\](?::\d+)?: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed:(?! Connection lost to authentication server)'
2023-06-18 11:00:10,337 fail2ban                [4736]: ERROR   NOK: ("Unable to compile regular expression '^[^[]*\\[(?:\\[?(?:(?:::f{4,6}:)?(?P<ip4>(?:\\d{1,3}\\.){3}\\d{1,3})|(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):)))\\]?|(?P<dns>[\\w\\-.^_]*\\w))\\](?::\\d+)?: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed:(?! Connection lost to authentication server)'",)
```

**Comment by sebres** [comment]
Fixed in #3267.

The solution: 
- either upgrade to 1.0
- or change the RE in filter, like:
1. global flags to local, for example:
```diff
- ^[^[]*\[<HOST>\]%(_port)s: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication ...
+ ^[^[]*\[<HOST>\]%(_port)s: SASL (?i:LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication ...
```
2. move global flags to begin of RE, for example:
```diff
- ^[^[]*\[<HOST>\]%(_port)s: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication ...
+ (?i)^[^[]*\[<HOST>\]%(_port)s: SASL (LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication ...
```

Thus closed as duplicate and obsolete.
