### ISSUE TITLE
[BR]: Runtime error on actionban

### ISSUE THREAD

**Issue by kar0v** [fail2ban/fail2ban#3608]
### Environment:

- Fail2Ban version  : Fail2Ban v0.11.2
- OS, including release name/version : Amazon Linux 2
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

When doing a test on the filter and waiting to get banned, there is a runtime error, the actionban does not work, but somehow the IP gets added to the database. 
```
# this generates a good amount of 404 errors
i=0;while true; do echo -e"\n---------$i---------\n"; curl -s -L testing.my-org.com/tests; i=$(($i+1));
```

#### Steps to reproduce
Spin up an amazon linux 2 free tier machine in AWS, install fail2ban, httpd and add the above configuration files. The ban.sh can be a trivial echo to a file for testing. 

#### Expected behavior
Expecting to run /opt/scripts/ban.sh Ban 222.222.222.222 in this case

### Configuration, dump and another helpful excerpts

**jail.local**
```
[my-jail]
enabled = true
filter = my-filter
action = my-action
  sendmail-whois[name=Fail2Ban Test, dest=my-name@my-org.de, sender=EC2-Fail2Ban@my-org.de, sendername="Fail2Ban"]
logpath = /var/log/apache2/frontend-app-my-org-com-access.log
maxretry = 4
findtime = 60
bantime = 300
journalmatch = _SYSTEMD_UNIT=httpd.service

```

**my-action.conf**
```
[Definition]

actionstart = touch /var/log/fail2ban_debug.log
actionstop = rm -f /var/log/fail2ban_debug.log

actionban = /opt/scripts/ban.sh Ban <ip>
actionunban = /opt/scripts/ban.sh Unban <ip>

```

**my-filter.conf**
```
[Definition]
failregex = ^<HOST> - - \[.*\] \".*.my-org.*\" \".*\" [4-5][0-9][0-9]
```

#### Relevant parts of /var/log/fail2ban.log file:

```
2023-10-19 12:24:14,794 fail2ban.actions        [27105]: ERROR   Failed to execute ban jail 'my-jail' action 'my-action' info 'ActionInfo({'ip': '222.222.222.222, 'fid': <function <lambda> at 0x7fb89dc18250>, 'family': 'inet4', 'raw-ticket': <function <lambda> at 0x7fb89dc18850>})': Error banning 222.222.222.222
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fail2ban/server/actions.py", line 510, in __checkBan
    action.ban(aInfo)
  File "/usr/lib/python2.7/site-packages/fail2ban/server/action.py", line 566, in ban
    raise RuntimeError("Error banning %(ip)s" % aInfo)
RuntimeError: Error banning 222.222.222.222
2023-10-19 12:24:14,795 fail2ban.actions        [27105]: DEBUG   Banned 1 / 1, 1 ticket(s) in 'my-jail'
2023-10-19 12:24:14,831 fail2ban.filterpoll     [27105]: DEBUG   /var/log/apache2/frontend-app-my-org-com-access.log has been modified
2023-10-19 12:24:14,832 fail2ban.filter         [27105]: DEBUG   Processing line with time:1697711054 and ip:85.196.157.217
2023-10-19 12:24:14,832 fail2ban.filter         [27105]: INFO    [my-jail] Found 222.222.222.222 - 2023-10-19 12:24:14
2023-10-19 12:24:14,832 fail2ban.failmanager    [27105]: DEBUG   Total # of detected failures: 5. Current failures from 1 IPs (IP:count): 222.222.222.222:1
```

**Comment by sebres** [comment]
The issue is pretty clear - the action have an error (syntax, permissions, whatever).

You have check several lines **before** the line `Failed to execute ban`. The full info why it fails is provided there. 
For example, how it may look:
```
2023-01-01 01:02:03,511 fail2ban.actions        [123]: NOTICE  [jail] Ban 192.0.2.123
2023-01-01 01:02:04,380 fail2ban.utils          [123]: ERROR   7fed01234567 -- exec: some-test-action.sh ...
2023-01-01 01:02:04,382 fail2ban.utils          [123]: ERROR   7fed01234567 -- stderr: 'iptables: Chain already exists.'
2023-01-01 01:02:04,385 fail2ban.utils          [123]: ERROR   7fed01234567 -- stderr: 'iptables: unknown option "--test" '
2023-01-01 01:02:04,385 fail2ban.utils          [123]: ERROR   7fed01234567 -- stderr: "Try `iptables -h' or 'iptables --help' for more information."
2023-01-01 01:02:04,385 fail2ban.utils          [123]: ERROR   7fed01234567 -- returned 2
2023-01-01 01:02:04,385 fail2ban.actions        [123]: ERROR   Failed to execute ban jail 'jail' action ...
```
Take a careful look at error message **before** the excerpt you provided - this contains every info you'd need.

> When doing a test on the filter and waiting to get banned, there is a runtime error, the actionban does not work

You don't need to generate failure in that way - it would be enough to invoke this to test action:
`?sudo? fail2ban-client set "$jail" banip "192.0.2.123"`

> but somehow the IP gets added to the database.

Sure... Moreover fail2ban internally thinks it is banned, despite the action failed. 
This is because banning action **must always work** normally. 
However fail2ban has several precautions that would try to restore sane environment and reban the IP (or invoke `actionrepair` if specified), it still generate attempts... There are also several other tags (like `actioncheck`) that may check the environment is sane or some repairs are needed.

**Comment by kar0v** [comment]
Thank you @sebres for pointing this out, as I have missed it. As it turned out the bash script was not executable (facepalm).
