### ISSUE TITLE
[BR]: test_del_file sporadically fails (in GHA)

### ISSUE THREAD

**Issue by sebres** [fail2ban/fail2ban#3635]
### Environment:

last master branch, GHA, python 3.11

### The issue:

Test suite sporadically [failed in GHA](https://github.com/fail2ban/fail2ban/actions/runs/6956937098/job/18928819566#step:8:541).

#### Any additional information

This looks like an aftereffect of "unhandled" exception in main cycle of filter (pyinotify backend).

However related to this code:
https://github.com/fail2ban/fail2ban/blob/9fc754ceeac900f2480694ccf941d20791c3d039/fail2ban/tests/filtertestcase.py#L1063-L1065
it should log critical error with a traceback, but for some reason it doesn't happen in GHA, so doesn't show the real error.

#### Tasks:
- [x] - fix error handler so the traceback would be visible in GHA
- [x] - fix the reason caused "unhandled" exception in main cycle of pyinotify backend.

**Comment by sebres** [comment]
1. The issue with a missing logging is found: it happens because mistaken double invocation of inherited class setup here:
https://github.com/fail2ban/fail2ban/blob/22ce0c0536c06445e0060cfc7c2bddcf6df162af/fail2ban/tests/sockettestcase.py#L57-L58
causes that no restore of log-handler takes place in `tearDown` later, so after that tests it remains by `LogCaptureTestCase._MemHandler`, so every future logged message disappear in nirvana.

2. Case with a failure reproduced with a script repeating tests in cycle:
```
$ tclsh <<< 'timerate { puts [exec python bin/fail2ban-testcases -fn -vv test_del.*Pyinotify >&@stdout] } 10000'
...
Fail2ban 1.1.0.dev1 test suite. Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]. Please wait...
test_delLogPath (fail2ban.tests.filtertestcase.MonitorFailures<FilterPyinotify>(/tmp/monitorfailures_FilterPyinotify_5yl3j0lbfail2ban).test_delLogPath) ... ok
test_del_file (fail2ban.tests.filtertestcase.MonitorFailures<FilterPyinotify>(/tmp/monitorfailures_FilterPyinotify_5yl3j0lbfail2ban).test_del_file) ...  

2023-11-22 16:50:23,528 7FE7ECDB56C0 CRITI Caught unhandled exception in main cycle of FilterPyinotify(DummyJail('DummyJail')) : KeyError('/tmp/monitorfailures_FilterPyinotify_5yl3j0lbfail2ban-1')
Traceback (most recent call last):
  File "/Projects/fail2ban.master/fail2ban/server/filterpyinotify.py", line 359, in run
    self._checkPending()
  File "/Projects/fail2ban.master/fail2ban/server/filterpyinotify.py", line 176, in _checkPending
    self.__pending[path][0] = retardTM
    ~~~~~~~~~~~~~~^^^^^^
KeyError: '/tmp/monitorfailures_FilterPyinotify_5yl3j0lbfail2ban-1'
FAIL

======================================================================
FAIL: test_del_file (fail2ban.tests.filtertestcase.MonitorFailures<FilterPyinotify>(/tmp/monitorfailures_FilterPyinotify_5yl3j0lbfail2ban).test_del_file)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Projects/fail2ban.master/fail2ban/tests/filtertestcase.py", line 1114, in tearDown
    super(MonitorFailures, self).tearDown()
  File "/Projects/fail2ban.master/fail2ban/tests/filtertestcase.py", line 1031, in tearDown
    self.assertFalse(hasattr(self, "_unexpectedError"))
AssertionError: True is not false

----------------------------------------------------------------------
Ran 2 tests in 0.056s
```
what shows that an issue going to missing lock around `__pending` dict, so an entry goes deleted by `_delPending` with 1st thread, while 2nd thread in filter doing `_checkPending` where it still got this key in iterator, but later fails in the cycle because `__pending[path]` was deleted by 1st thread inbetween:
https://github.com/fail2ban/fail2ban/blob/22ce0c0536c06445e0060cfc7c2bddcf6df162af/fail2ban/server/filterpyinotify.py#L168-L176

Can be simply fixed with:
```diff
-       self.__pending[path][0] = retardTM
+       try:
+         self.__pending[path][0] = retardTM
+       except KeyError: pass
```
