### ISSUE TITLE
[BR]: wont run

### ISSUE THREAD

**Issue by TeemSucks** [fail2ban/fail2ban#3675]
### Environment:

- Fail2Ban version  : 
- OS, including release name/version : 1.0.2
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

after runing setup.py and running fail2ban i got this error

```
❯ fail2ban-client
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/fail2ban-client", line 34, in <module>
    from fail2ban.client.fail2banclient import exec_command_line, sys
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fail2ban/client/fail2banclient.py", line 35, in <module>
    from .beautifier import Beautifier
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fail2ban/client/beautifier.py", line 25, in <module>
    from ..helpers import getLogger, logging
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fail2ban/helpers.py", line 291
    return {**x, **y}
             ^
SyntaxError: invalid syntax
```

#### Relevant parts of /var/log/fail2ban.log file:
```
❯ open /var/log/fail2ban.log
The file /var/log/fail2ban.log does not exist.
```

**Comment by sebres** [comment]
Shortly: the version seems to be python-3.x-bassed, but installed for python 2.x.
No idea how it was possible (if you really do that "via OS/distribution mechanisms"). Which distro/platform? Which fail2ban version?

See https://github.com/fail2ban/fail2ban/issues/1259#issuecomment-675914763, https://github.com/fail2ban/fail2ban/issues/3202#issuecomment-1018756968 and https://github.com/fail2ban/fail2ban/issues/3193#issuecomment-1001619134 for similar issues.
