### ISSUE TITLE
[BR]: curl: (22) The requested URL returned error: 422

### ISSUE THREAD

**Issue by IgorLytkin** [fail2ban/fail2ban#3804]
### Environment:
- Fail2Ban version  : 1.1.0-1~upstream1
- OS, including release name/version : 
- [x ] Fail2Ban installed via OS/distribution mechanisms
- [ x] You have not applied any additional foreign patches to the codebase
- [ x] Some customizations were done to the configuration (provide details below is so)

### The issue:

I see errors in fail2ban.log.

#### Steps to reproduce
`liv@singularity:~$ sudo lnav /var/log/fail2ban.log /var/log/auth.log /var/log/postgresql/`
#### Expected behavior
No such errors
#### Any customizations done to /etc/fail2ban/ configuration
jail.local

[DEFAULT]
action = %(action_)s
         abuseipdb[abuseipdb_apikey=...]
bantime.increment = true
bantime.rndtime = 30m
bantime.maxtime = 60d
bantime.factor = 2
bantime.formula = ban.Time * math.exp(float(ban.Count+1)*banFactor)/math.exp(1*banFactor)
bantime.overalljails = true
banaction = nftables
banaction_allports = nftables[type=allports]

#### Relevant parts of /var/log/fail2ban.log file:
```
```

#### Relevant lines from monitored log files:

```
2024-07-25 05:47:34,695 fail2ban.utils ERROR   7bfebb502ec0 -- exec: ['f2bV_matches=$0 \nlgm=$(printf \'%.1000s\\n...\' "$f2bV_matches"); curl -sSf "https://api.abuseipdb.com/api/v2/report"...
2024-07-25 05:47:34,696 fail2ban.utils          [958]: ERROR   7bfebb502ec0 -- stderr: 'curl: (22) The requested URL returned error: 422' 
2024-07-25 05:47:34,696 fail2ban.utils          [958]: ERROR   7bfebb502ec0 -- returned 22
│2024-07-25 05:47:35,063 fail2ban.utils          [958]: ERROR   7bfebb4f9900 -- exec: ['f2bV_matches=$0 \nlgm=$(printf \'%.1000s\\n...\' "$f2bV_matches"); curl -sSf "https://api.abuseipdb.com/api/v2/report"
2024-07-25 05:47:35,064 fail2ban.utils          [958]: ERROR   7bfebb4f9900 -- stderr: 'curl: (22) The requested URL returned error: 422'
2024-07-25 05:47:35,064 fail2ban.utils          [958]: ERROR   7bfebb4f9900 -- returned 22`

2024-07-25 05:47:35,064 fail2ban.actions        [958]: ERROR   Failed to execute ban jail 'sshd' action 'abuseipdb' info 'ActionInfo({'ip': '43.133.57.239', 'family': 'inet4', 'fid': <function Actions.Action
│Traceback (most recent call last):                                                                                                                                                                             ┤│  File "/usr/local/lib/python3.10/dist-packages/fail2ban/server/actions.py", line 513, in __checkBan                                                                                                           ┤│    action.ban(aInfo)                                                                                                                                                                                          ┤│  File "/usr/local/lib/python3.10/dist-packages/fail2ban/server/action.py", line 568, in ban                                                                                                                   ┤│    raise RuntimeError("Error banning %(ip)s" % aInfo)                                                                                                                                                         ┤│RuntimeError: Error banning 43.133.57.239                                                            
```

**Comment by sebres** [comment]
Hmm... Dup of #2468 ?

Anyway it is pretty 3rd party issue, I don't think we may be responsible for that.

By the way, you seemed to publish your apikey in the issue description (I removed it there, but)... time to change it now (as "compromised"). And next time simply blacking/x-ing it.

**Comment by IgorLytkin** [comment]
Deleted the compromised key. The strange thing is that the banned hosts do not appear in the list of Abuseipdb reports.

**Comment by sebres** [comment]
> The strange thing is that the banned hosts do not appear in the list of Abuseipdb reports.

Well, it's no wonder since it answers with 422 response... Just I have no clue what it can be.
You could try that errored curls from the console (e. g. possibly it'd provide more info or you'd find the reason why it does that) or seek for the help by abuseipdb.
My guess - it could be something like a limit exhaustion, quote from abuseipdb description:
>> *Due to limited resources, free accounts currently have 1,000 requests/day for both IP check and report actions through our free API. Verified webmasters are allowed 3,000 requests/day. Supports are allowed 5,000 requests/day.*

**Comment by IgorLytkin** [comment]
@sebres I don't think so. Because i don't exceed my API counter. It's value about 150/1000 per day.

**Comment by IgorLytkin** [comment]
Here last error in fail2ban.log:
`2024-07-29 04:37:56,563 fail2ban.utils          [245148]: ERROR   7c967dab2bc0 -- exec: ['f2bV_matches=$0 \nlgm=$(printf \'%.1000s\\n...\' "$f2bV_matches"); curl -sSf "https://api.abuseipdb.com/api/v2/report" -H "Accept: application/json" -H "Key: fdxxxe1" --data-urlencode "comment=$lgm" --data-urlencode "ip=47.92.132.66" --data "categories=<abuseipdb_category>"', '2024-07-29T04:37:53.422182 singularity sshd[632518]: Connection closed by 47.92.132.66 port 45264 [preauth]\n2024-07-29T04:37:53.708390 singularity sshd[632520]: Connection from 47.92.132.66 port 48784 on 62.113.107.38 port 2222 rdomain ""\n2024-07-29T04:37:54.238794 singularity sshd[632520]: Connection closed by 47.92.132.66 port 48784 [preauth]\n2024-07-29T04:37:54.737156 singularity sshd[632522]: Connection from 47.92.132.66 port 50020 on 62.113.107.38 port 2222 rdomain ""\n2024-07-29T04:37:55.236937 singularity sshd[632522]: Connection closed by 47.92.132.66 port 50020 [preauth]']
2024-07-29 04:37:56,563 fail2ban.utils          [245148]: ERROR   7c967dab2bc0 -- stderr: 'curl: (22) The requested URL returned error: 422'
2024-07-29 04:37:56,563 fail2ban.utils          [245148]: ERROR   7c967dab2bc0 -- returned 22
2024-07-29 04:37:56,911 fail2ban.utils          [245148]: ERROR   7c967dab3600 -- exec: ['f2bV_matches=$0 \nlgm=$(printf \'%.1000s\\n...\' "$f2bV_matches"); curl -sSf "https://api.abuseipdb.com/api/v2/report" -H "Accept: application/json" -H "Key: fdxxxe1" --data-urlencode "comment=$lgm" --data-urlencode "ip=47.92.132.66" --data "categories=<abuseipdb_category>"', '2024-07-29T04:37:53.422182 singularity sshd[632518]: Connection closed by 47.92.132.66 port 45264 [preauth]\n2024-07-29T04:37:53.708390 singularity sshd[632520]: Connection from 47.92.132.66 port 48784 on 62.113.107.38 port 2222 rdomain ""\n2024-07-29T04:37:54.238794 singularity sshd[632520]: Connection closed by 47.92.132.66 port 48784 [preauth]\n2024-07-29T04:37:54.737156 singularity sshd[632522]: Connection from 47.92.132.66 port 50020 on 62.113.107.38 port 2222 rdomain ""\n2024-07-29T04:37:55.236937 singularity sshd[632522]: Connection closed by 47.92.132.66 port 50020 [preauth]']
2024-07-29 04:37:56,911 fail2ban.utils          [245148]: ERROR   7c967dab3600 -- stderr: 'curl: (22) The requested URL returned error: 422'
2024-07-29 04:37:56,911 fail2ban.utils          [245148]: ERROR   7c967dab3600 -- returned 22
2024-07-29 04:37:56,911 fail2ban.actions        [245148]: ERROR   Failed to execute ban jail 'sshd' action 'abuseipdb' info 'ActionInfo({'ip': '47.92.132.66', 'family': 'inet4', 'fid': <function Actions.ActionInfo.<lambda> at 0x7c967f651f30>, 'matches': '2024-07-29T04:37:53.422182 singularity sshd[632518]: Connection closed by 47.92.132.66 port 45264 [preauth]\n2024-07-29T04:37:53.708390 singularity sshd[632520]: Connection from 47.92.132.66 port 48784 on 62.113.107.38 port 2222 rdomain ""\n2024-07-29T04:37:54.238794 singularity sshd[632520]: Connection closed by 47.92.132.66 port 48784 [preauth]\n2024-07-29T04:37:54.737156 singularity sshd[632522]: Connection from 47.92.132.66 port 50020 on 62.113.107.38 port 2222 rdomain ""\n2024-07-29T04:37:55.236937 singularity sshd[632522]: Connection closed by 47.92.132.66 port 50020 [preauth]', 'F-*': {'matches': ['2024-07-29T04:37:53.422182 singularity sshd[632518]: Connection closed by 47.92.132.66 port 45264 [preauth]', '2024-07-29T04:37:53.708390 singularity sshd[632520]: Connection from 47.92.132.66 port 48784 on 62.113.107.38 port 2222 rdomain ""', '2024-07-29T04:37:54.238794 singularity sshd[632520]: Connection closed by 47.92.132.66 port 48784 [preauth]', '2024-07-29T04:37:54.737156 singularity sshd[632522]: Connection from 47.92.132.66 port 50020 on 62.113.107.38 port 2222 rdomain ""', '2024-07-29T04:37:55.236937 singularity sshd[632522]: Connection closed by 47.92.132.66 port 50020 [preauth]'], 'failures': 5, 'mlfid': 'singularity sshd[632504]: ', 'ip4': '47.92.132.66'}, 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x7c967f6525f0>})': Error banning 47.92.132.66
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fail2ban/server/actions.py", line 513, in __checkBan
    action.ban(aInfo)
  File "/usr/local/lib/python3.10/dist-packages/fail2ban/server/action.py", line 568, in ban
    raise RuntimeError("Error banning %(ip)s" % aInfo)
RuntimeError: Error banning 47.92.132.66
`

**Comment by sebres** [comment]
It looks like tag `abuseipdb_category` is not replaced in the command. Maybe this is the issue.

See for example the action description:
https://github.com/fail2ban/fail2ban/blob/7fd097d73fb995daa39a834879b553a53d1f64ca/config/action.d/abuseipdb.conf#L22-L45

**Comment by IgorLytkin** [comment]
Thank you. I added the specified jail.local change on both VPS. I am observing the consequences of the change.

**Comment by IgorLytkin** [comment]
Add all codes 1-23. Let's play!
