### ISSUE TITLE
systemd filter test failures on Debian system(s)

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#728]
2.6.8 - 215 all OK
2.7.3 - 217 failures=2, skipped=1
2.6.8dbg - 215 all OK
2.7.6 in /opt/python - 208 skipped=2

Could you help me where to begin debugging?

I have backported systemd and python-systemd 204-8 which is only for 2.7
Could it be that 2.7.6 does not _see_ python-systemd and executes only 208 test and that is why it is OK?

```
./fail2ban-testcases-all --no-network
Testing using /usr/bin/python2.6
Fail2ban 0.9.0 test suite. Python 2.6.8 (unknown, Jan 26 2013, 14:35:25) [GCC 4.7.2]. Please wait...
.......................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 215 tests in 85.904s

OK
Testing using /usr/bin/python2.7
Fail2ban 0.9.0 test suite. Python 2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]. Please wait...
..........................................................................................s........................................................................................................................FF....
======================================================================
FAIL: MonitorJournalFailures<class 'fail2ban.server.filtersystemd.FilterSystemd'>(monitorjournalfailures-818bbbea-a6ff-49ba-ab64-ccf145996899)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/filtertestcase.py", line 761, in test_delJournalMatch
    self.assert_correct_ban("193.168.0.128", 3)
  File "./fail2ban/tests/filtertestcase.py", line 716, in assert_correct_ban
    self.assertTrue(self.isFilled(10)) # give Filter a chance to react
AssertionError: False is not true

======================================================================
FAIL: MonitorJournalFailures<class 'fail2ban.server.filtersystemd.FilterSystemd'>(monitorjournalfailures-f0ed1c30-c03f-4a3c-81e1-42d8f984216c)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/filtertestcase.py", line 739, in test_grow_file
    self.assertTrue(self.isFilled(6))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 217 tests in 100.498s

FAILED (failures=2, skipped=1)
Testing using /usr/bin/python2.6-dbg
Fail2ban 0.9.0 test suite. Python 2.6.8 (unknown, Jan 26 2013, 15:33:28) [GCC 4.7.2]. Please wait...
.......................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 215 tests in 86.025s

OK
[110407 refs]
Testing using /usr/local/bin/python2.7.6
Fail2ban 0.9.0 test suite. Python 2.7.6 (default, May 17 2014, 21:57:42) [GCC 4.7.2]. Please wait...
.....................s....................................................................s.....................................................................................................................
----------------------------------------------------------------------
Ran 208 tests in 72.414s

OK (skipped=2)
E: Failed with  /usr/bin/python2.7
make[1]: *** [override_dh_auto_test] Error 1
make[1]: Leaving directory `/home/viktor/fail2ban-debian-0.9.0-git48-gabcab00-1'
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

**Comment by opoplawski** [comment]
For the record - hitting this on RHEL7 as well which uses volatile storage by default.
