### ISSUE TITLE
Various CallingMap errors and Segmentation fault with python2.7

### ISSUE THREAD

**Issue by ache** [fail2ban/fail2ban#960]
CallingMap errors look like this:
```
2015-02-14 07:16:25,499 fail2ban.actions        [624]: ERROR   Failed to execute ban jail 'recidive' action 'bsd-ipfw' info 'CallingMap({'ipjailmatches': <function <lambda> at 0x291dd56c>, 'matches': u'2015-02-08 23:52:42,428 fail2ban.actions        [15380]: NOTICE  [sshd-ipfw] Ban 103.41.124.34\n2015-02-09 03:40:14,114 fail2ban.actions        [15380]: NOTICE  [sshd-ipfw] Ban 103.41.124.34\n2015-02-09 19:16:59,179 fail2ban.actions        [21602]: NOTICE  [sshd-ipfw] Ban 103.41.124.34', 'ip': '103.41.124.34', 'ipmatches': <function <lambda> at 0x291a1144>, 'ipfailures': <function <lambda> at 0x291dd5a4>, 'time': 1423887385.498615, 'failures': 3, 'ipjailfailures': <function <lambda> at 0x291dd534>})': Error binding parameter 0 - probably unsupported type
```
Notice the very last words, they may changes, other versions are:
```
'NoneType' object has no attribute '__getitem__'
need more than 0 values to unpack
```
Perhaps it is related to fail2ban "Segmentation fault" core dump in py-sqlite3 module but I am not sure. Usually in this place:
```
#0  0x290a82e6 in sqlite3_column_int64 () from /usr/local/lib/libsqlite3.so.0
#1  0x2908da6b in _pysqlite_fetch_one_row ()
   from /usr/local/lib/python2.7/lib-dynload/_sqlite3.so
#2  0x2908eb55 in pysqlite_cursor_iternext ()
   from /usr/local/lib/python2.7/lib-dynload/_sqlite3.so
```
It does not happens often, once in few days. Removing fail2ban database helps only temporary, then it starts again.
This is sort of regression because I never saw errors mentioned in pre-sqlite fail2ban version.
Python 2.7.9, sqlite 3.8.8.2, fail2ban itself used to read logs (I try gamin too), FreeBSD-stable 32bit

**Comment by yarikoptic** [comment]
since no fail2ban version is stated I assume it is released 0.9.1.
presumably current master should be already mitigating these both issues, we should just cut a release (search does wonders): #838 #844

**Comment by ache** [comment]
Yes, I mean latest released code. Roll out new release with those fixes please. Crashes are critical and mitigating them with monit is just dirty.

**Comment by yarikoptic** [comment]
I agree -- release should come soon.  With your help it will come even sooner ;)
