### ISSUE TITLE
CRITICAL Unhandled exception in Fail2Ban

### ISSUE THREAD

**Issue by tarampampam** [fail2ban/fail2ban#973]
**In `/var/log/fail2ban.log`:**
```
2015-02-24 16:29:03,190 fail2ban.filter         [13436]: INFO    [nginx-http-auth] Found 178.72.80.156
2015-02-24 16:29:03,192 fail2ban                [13436]: CRITICAL Unhandled exception in Fail2Ban:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fail2ban/server/jailthread.py", line 64, in run_with_except_hook
    run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fail2ban/server/filterpoll.py", line 102, in run
    self.jail.putFailTicket(ticket)
  File "/usr/lib/python2.7/site-packages/fail2ban/server/jail.py", line 193, in putFailTicket
    self.database.addBan(self, ticket)
  File "/usr/lib/python2.7/site-packages/fail2ban/server/database.py", line 57, in wrapper
    return f(self, self._db.cursor(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fail2ban/server/database.py", line 373, in addBan
    "failures": ticket.getAttempt()}))
InterfaceError: Error binding parameter 3 - probably unsupported type.
2015-02-24 16:29:03,404 fail2ban.actions        [13436]: NOTICE  [nginx-http-auth] Ban 178.72.80.156
2015-02-24 16:29:03,508 fail2ban.actions        [13436]: ERROR   Failed to execute ban jail 'nginx-http-auth' action 'iptables-multiport' info 'CallingMap({'ipjailmatches': <function <lambda> at 0x2647578>, 'matches': '2015/02/24 16:28:56 [error] 12237#0: *16072 user "\xe8\xeb\xfc\xe4\xe0\xf0" was not found in "/home/htpasswd/domain1.ru-yeah-servetpassword", client: 178.72.80.156, server: domain1.ru, request: "GET /somefile.txt HTTP/1.1", host: "domain1.ru"\n2015/02/24 16:29:02 [error] 12237#0: *16073 user "\xe8\xeb\xfc\xe4\xe0\xf0" was not found in "/home/htpasswd/domain1.ru-yeah-servetpassword", client: 178.72.80.156, server: domain1.ru, request: "GET /somefile.txt HTTP/1.1", host: "domain1.ru"', 'ip': '178.72.80.156', 'ipmatches': <function <lambda> at 0x2647500>, 'ipfailures': <function <lambda> at 0x26475f0>, 'time': 1424784543.404882, 'failures': 2, 'ipjailfailures': <function <lambda> at 0x2647668>})': 'NoneType' object has no attribute 'getAttempt'
2015-02-24 16:32:32,728 fail2ban.actions        [13436]: NOTICE  [nginx-http-auth] Unban 89.236.194.114
2015-02-24 16:39:04,205 fail2ban.actions        [13436]: NOTICE  [nginx-http-auth] Unban 178.72.80.156
2015-02-24 16:39:04,314 fail2ban.action         [13436]: ERROR   iptables -D f2b-default -s 178.72.80.156 -j REJECT --reject-with icmp-port-unreachable -- stdout: ''
2015-02-24 16:39:04,314 fail2ban.action         [13436]: ERROR   iptables -D f2b-default -s 178.72.80.156 -j REJECT --reject-with icmp-port-unreachable -- stderr: 'iptables: No chain/target/match by that name.\n'
2015-02-24 16:39:04,314 fail2ban.action         [13436]: ERROR   iptables -D f2b-default -s 178.72.80.156 -j REJECT --reject-with icmp-port-unreachable -- returned 1
2015-02-24 16:39:04,314 fail2ban.actions        [13436]: ERROR   Failed to execute unban jail 'nginx-http-auth' action 'iptables-multiport' info '{'matches': '2015/02/24 16:28:56 [error] 12237#0: *16072 user "\xe8\xeb\xfc\xe4\xe0\xf0" was not found in "/home/htpasswd/domain1.ru-yeah-servetpassword", client: 178.72.80.156, server: domain1.ru, request: "GET /somefile.txt HTTP/1.1", host: "domain1.ru"2015/02/24 16:29:02 [error] 12237#0: *16073 user "\xe8\xeb\xfc\xe4\xe0\xf0" was not found in "/home/htpasswd/domain1.ru-yeah-servetpassword", client: 178.72.80.156, server: domain1.ru, request: "GET /somefile.txt HTTP/1.1", host: "domain1.ru"', 'ip': '178.72.80.156', 'time': 1424784543.404882, 'failures': 2}': Error unbanning 178.72.80.156
```

**From `/etc/fail2ban/jail.local`:**
```
[nginx-http-auth]
enabled  = true
logencoding = utf-8
action   = iptables-multiport[port="http,https"]
port     = http,https
maxretry = 2
bantime  = 300 # 5 minutes
logpath  = /home/domain1.ru/log/*nginx*error*.log
           /home/domain2.ru/log/*nginx*error*.log
           /home/domain3.ru/log/*nginx*error*.log
```

**`$ cat /etc/fail2ban/filter.d/nginx-http-auth.conf`:**
```
# fail2ban filter configuration for nginx
[Definition]
failregex = ^ \[error\] \d+#\d+: \*\d+ user "\S+":? (password mismatch|was not found in ".*"), client: <HOST>, server: \S*, request: "\S+ \S+ HTTP/\d+\.\d+", host: "\S+"(, referrer: "\S+")?\s*$
ignoreregex =
```

**`$ cat /proc/version`:**
```
Linux version 3.10.0-123.20.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ) #1 SMP Thu Jan 29 18:05:33 UTC 2015
```

**`$ python -V`:**
```
Python 2.7.5
```

**`$ fail2ban-client -V`:**
```
Fail2Ban v0.9.1

Copyright (c) 2004-2008 Cyril Jaquier, 2008- Fail2Ban Contributors
Copyright of modifications held by their respective authors.
Licensed under the GNU General Public License v2 (GPL).

Written by Cyril Jaquier <cyril.jaquier@fail2ban.org>.
Many contributions by Yaroslav O. Halchenko <debian@onerussian.com>.
```

**How can i fix whis critical error?**

**Comment by leeclemens** [comment]
As a stop gap, can you disable the database (you won't be able to use the recidive jail - which you may not be) and see if this error stops occurring?

**Comment by tarampampam** [comment]
This error happens at random time, and now i restart fail2ban service once in 2 hours by crontab. Can you say some steps what i must to do?

_ps. sorry for my bad english_

**Comment by sebres** [comment]
If you can, please try a current master - i think we had already fixed it (#838 #844)

**Comment by tarampampam** [comment]
For update i must move files from `master.zip/fail2ban/` to `/usr/lib/python2.7/site-packages/fail2ban/` and only?

**Comment by sebres** [comment]
see bellow https://github.com/fail2ban/fail2ban/issues/878#issuecomment-65732113.

**Comment by tarampampam** [comment]
Yeah, f2b updated, thx. Give me some time for feedback.

**Comment by tarampampam** [comment]
Nope, error not fixed:
```
2015-02-25 09:17:36,168 fail2ban.filter         [6253]: INFO    [nginx-http-auth] Found 89.236.194.114
2015-02-25 09:18:29,235 fail2ban.filter         [6253]: INFO    [nginx-http-auth] Found 89.236.194.114
2015-02-25 09:18:29,596 fail2ban.actions        [6253]: NOTICE  [nginx-http-auth] Ban 89.236.194.114
2015-02-25 09:18:36,254 fail2ban.filter         [6253]: WARNING Error decoding line from '/home/domain1.ru/log/nginx.error.log' with 'utf-8'. Consider setting logencoding=utf-8 (or another appropriate encoding) for this jail. Continuing to process line ignoring invalid characters: '2015/02/25 09:18:35 [error] 3554#0: *6664 user "\xd1\xe2\xe5\xf2\xe0" was not found in "/home/htpasswd/domain1.ru-yeah-servetpassword", client: 178.121.176.34, server: domain1.ru, request: "GET /update.ver HTTP/1.1", host: "domain1.ru"\n'
2015-02-25 09:18:36,254 fail2ban.filter         [6253]: INFO    [nginx-http-auth] Found 178.121.176.34
2015-02-25 09:19:00,287 fail2ban.filter         [6253]: WARNING Error decoding line from '/home/domain1.ru/log/nginx.error.log' with 'utf-8'. Consider setting logencoding=utf-8 (or another appropriate encoding) for this jail. Continuing to process line ignoring invalid characters: '2015/02/25 09:18:59 [error] 3554#0: *6674 user "\xd1\xe2\xe5\xf2\xe0" was not found in "/home/htpasswd/domain1.ru-yeah-servetpassword", client: 178.121.176.34, server: domain1.ru, request: "GET /update.ver HTTP/1.1", host: "domain1.ru"\n'
2015-02-25 09:19:00,287 fail2ban.filter         [6253]: INFO    [nginx-http-auth] Found 178.121.176.34
2015-02-25 09:19:00,292 fail2ban                [6253]: CRITICAL Unhandled exception in Fail2Ban:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fail2ban-0.9.1.dev-py2.7.egg/fail2ban/server/jailthread.py", line 64, in run_with_except_hook
    run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fail2ban-0.9.1.dev-py2.7.egg/fail2ban/server/filterpoll.py", line 102, in run
    self.jail.putFailTicket(ticket)
  File "/usr/lib/python2.7/site-packages/fail2ban-0.9.1.dev-py2.7.egg/fail2ban/server/jail.py", line 192, in putFailTicket
    self.database.addBan(self, ticket)
  File "/usr/lib/python2.7/site-packages/fail2ban-0.9.1.dev-py2.7.egg/fail2ban/server/database.py", line 57, in wrapper
    return f(self, self._db.cursor(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fail2ban-0.9.1.dev-py2.7.egg/fail2ban/server/database.py", line 377, in addBan
    "failures": ticket.getAttempt()}))
InterfaceError: Error binding parameter 3 - probably unsupported type.
2015-02-25 09:19:00,753 fail2ban.actions        [6253]: NOTICE  [nginx-http-auth] Ban 178.121.176.34
2015-02-25 09:28:30,275 fail2ban.actions        [6253]: NOTICE  [nginx-http-auth] Unban 89.236.194.114
2015-02-25 09:29:01,421 fail2ban.actions        [6253]: NOTICE  [nginx-http-auth] Unban 178.121.176.34
```

After this - fail2ban stop working.

**Comment by sebres** [comment]
gotcha... good catch, thanks.

it is a problem with not decoded line in matches `... user "\xd1\xe2\xe5\xf2\xe0" ...`.
I think, sqlite3 expected legal utf-8 in JSON field, but this line was not correct decoded (not legal utf-8), so by deserializing into json we have an exception.

Test case below...

```python
import sqlite3
import json

sqlite3.register_adapter(dict, json.dumps)
sqlite3.register_converter("JSON", json.loads)

db = sqlite3.connect(':memory:', check_same_thread=False, detect_types=sqlite3.PARSE_DECLTYPES)
cur = db.cursor(); cur.execute('PRAGMA foreign_keys = ON;');

#cur = db.cursor(); cur.execute("DROP TABLE bans")

cur = db.cursor(); cur.execute("CREATE TABLE bans(jail TEXT NOT NULL, ip TEXT, timeofban INTEGER NOT NULL, data JSON)");
cur = db.cursor(); cur.execute("CREATE INDEX bans_jail_timeofban_ip ON bans(jail, timeofban);")
cur = db.cursor(); cur.execute("CREATE INDEX bans_jail_ip ON bans(jail, ip);")
cur = db.cursor(); cur.execute("CREATE INDEX bans_ip ON bans(ip);")

# OK:
tjs = {'m': ['... user "test"  ...'], 'a': 1}
cur = db.cursor(); cur.execute("INSERT INTO bans(jail, ip, timeofban, data) VALUES(?, ?, ?, ?)", 
  ('test', '1.2.3.4', int(round(54645664.54)), tjs))

# BOOM:
tjs = {'m': ['... user "\xd1\xe2\xe5\xf2\xe0"  ...'], 'a': 1}
cur = db.cursor(); cur.execute("INSERT INTO bans(jail, ip, timeofban, data) VALUES(?, ?, ?, ?)", 
  ('test', '1.2.3.4', int(round(54645664.54)), tjs))
```
the last one throws :boom: 

I try to fix it soon.

**Comment by sebres** [comment]
Original problem is as already said a invalid utf-8 string together with `json.dumps`:
```
>>> json.dumps({'m': ['... user "\xd1\xe2\xe5\xf2\xe0"  ...'], 'a': 1})
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd1 in position 10: invalid continuation byte
```

**Comment by sebres** [comment]
@tarampampam you can try a <a href="https://github.com/sebres/fail2ban/tree/gh-973-fix">sebres:gh-973-fix</a> resp. #975, that fix this issue.

**Comment by tarampampam** [comment]
Now i must update from `https://github.com/fail2ban/fail2ban/archive/master.zip` - right?

**Comment by sebres** [comment]
No, it was still not merged into master, so in the meantime you can use https://github.com/sebres/fail2ban/archive/gh-973-fix.zip

**Comment by tarampampam** [comment]
Update installed, give me some time again for feedback.

**Comment by sebres** [comment]
Only if you'll see `WARNING Error decoding line from ...` but no error/exception after ban for this failures, then we have won :) But I'm confident.

**Comment by tarampampam** [comment]
And after a day - all looks ok. Great, thx!

**Comment by tarampampam** [comment]
```
2015-02-27 08:34:40,649 fail2ban.server         [28522]: INFO    Stopping all jails
2015-02-27 08:34:41,537 fail2ban.action         [28522]: ERROR   iptables -D INPUT -p tcp --dport 22122 -j f2b-SSH
iptables -F f2b-SSH
iptables -X f2b-SSH -- stdout: ''
2015-02-27 08:34:41,537 fail2ban.action         [28522]: ERROR   iptables -D INPUT -p tcp --dport 22122 -j f2b-SSH
iptables -F f2b-SSH
iptables -X f2b-SSH -- stderr: 'iptables: Too many links.\n'
2015-02-27 08:34:41,537 fail2ban.action         [28522]: ERROR   iptables -D INPUT -p tcp --dport 22122 -j f2b-SSH
iptables -F f2b-SSH
iptables -X f2b-SSH -- returned 1
2015-02-27 08:34:41,538 fail2ban.actions        [28522]: ERROR   Failed to stop jail 'sshd' action 'iptables': Error stopping action
2015-02-27 08:34:41,538 fail2ban.jail           [28522]: INFO    Jail 'sshd' stopped
2015-02-27 08:34:41,778 fail2ban.actions        [28522]: NOTICE  [nginx-http-auth] Unban 89.236.194.114
2015-02-27 08:34:41,995 fail2ban.action         [28522]: ERROR   iptables -D INPUT -p tcp -m multiport --dports http,https -j f2b-default
iptables -F f2b-default
iptables -X f2b-default -- stdout: ''
2015-02-27 08:34:41,996 fail2ban.action         [28522]: ERROR   iptables -D INPUT -p tcp -m multiport --dports http,https -j f2b-default
iptables -F f2b-default
iptables -X f2b-default -- stderr: 'iptables: Too many links.\n'
2015-02-27 08:34:41,996 fail2ban.action         [28522]: ERROR   iptables -D INPUT -p tcp -m multiport --dports http,https -j f2b-default
iptables -F f2b-default
iptables -X f2b-default -- returned 1
2015-02-27 08:34:41,996 fail2ban.actions        [28522]: ERROR   Failed to stop jail 'nginx-http-auth' action 'iptables-multiport': Error stopping action
2015-02-27 08:34:42,106 fail2ban.jail           [28522]: INFO    Jail 'nginx-http-auth' stopped
2015-02-27 08:34:42,110 fail2ban.server         [28522]: INFO    Exiting Fail2ban
```

After this a remove fail2ban from my system.

**Comment by sebres** [comment]
This is another known issue - because of some errors by banning previously / after stop of fail2ban some rules in iptables was not removed, and chain can not be easy deleted. Just stop f2b and remove all of `f2b-...` entries manually with iptables or restart your "firewall".
